use super::CharClassification;

pub static CHAR_CLASSIFICATION: [(u32, CharClassification); 650] = [
    (0, CharClassification::Ignore),
    (' ' as u32, CharClassification::Space),
    ('!' as u32, CharClassification::Closing),
    ('!' as u32 + 1, CharClassification::Ignore),
    ('#' as u32, CharClassification::Normal),
    ('&' as u32 + 1, CharClassification::Ignore),
    ('(' as u32, CharClassification::Opening),
    (')' as u32, CharClassification::Closing),
    ('*' as u32, CharClassification::Normal),
    ('+' as u32, CharClassification::Binary),
    (',' as u32, CharClassification::Punct),
    ('-' as u32, CharClassification::Normal),
    (':' as u32, CharClassification::Punct),
    ('<' as u32, CharClassification::Relation),
    ('?' as u32, CharClassification::Normal),
    ('A' as u32, CharClassification::Alphabetic),
    ('[' as u32, CharClassification::Opening),
    ('\\' as u32, CharClassification::Normal),
    (']' as u32, CharClassification::Closing),
    ('^' as u32, CharClassification::Normal),
    ('`' as u32, CharClassification::Diacritic),
    ('a' as u32, CharClassification::Alphabetic),
    ('{' as u32, CharClassification::Opening),
    ('|' as u32, CharClassification::Fence),
    ('}' as u32, CharClassification::Closing),
    ('~' as u32, CharClassification::Normal),
    ('~' as u32 + 1, CharClassification::Ignore),
    ('\u{a0}' as u32, CharClassification::Space),
    ('¡' as u32, CharClassification::Punct),
    ('¢' as u32, CharClassification::Normal),
    ('¨' as u32, CharClassification::Diacritic),
    ('¨' as u32 + 1, CharClassification::Ignore),
    ('¬' as u32, CharClassification::Normal),
    ('¬' as u32 + 1, CharClassification::Ignore),
    ('¯' as u32, CharClassification::Diacritic),
    ('°' as u32, CharClassification::Normal),
    ('±' as u32, CharClassification::Binary),
    ('²' as u32, CharClassification::Normal),
    ('·' as u32, CharClassification::Binary),
    ('·' as u32 + 1, CharClassification::Ignore),
    ('¹' as u32, CharClassification::Normal),
    ('¹' as u32 + 1, CharClassification::Ignore),
    ('¼' as u32, CharClassification::Normal),
    ('¿' as u32, CharClassification::Punct),
    ('¿' as u32 + 1, CharClassification::Ignore),
    ('×' as u32, CharClassification::Binary),
    ('×' as u32 + 1, CharClassification::Ignore),
    ('ð' as u32, CharClassification::Alphabetic),
    ('ð' as u32 + 1, CharClassification::Ignore),
    ('÷' as u32, CharClassification::Binary),
    ('÷' as u32 + 1, CharClassification::Ignore),
    ('ı' as u32, CharClassification::Alphabetic),
    ('ı' as u32 + 1, CharClassification::Ignore),
    ('Ƶ' as u32, CharClassification::Normal),
    ('Ƶ' as u32 + 1, CharClassification::Ignore),
    ('ȷ' as u32, CharClassification::Alphabetic),
    ('ȷ' as u32 + 1, CharClassification::Ignore),
    ('ˆ' as u32, CharClassification::Diacritic),
    ('ˇ' as u32 + 1, CharClassification::Ignore),
    ('˘' as u32, CharClassification::Diacritic),
    ('˚' as u32 + 1, CharClassification::Ignore),
    ('˜' as u32, CharClassification::Diacritic),
    ('˜' as u32 + 1, CharClassification::Ignore),
    ('\u{300}' as u32, CharClassification::Diacritic),
    ('\u{30a}' as u32 + 1, CharClassification::Ignore),
    ('\u{30c}' as u32, CharClassification::Diacritic),
    ('\u{30c}' as u32 + 1, CharClassification::Ignore),
    ('\u{310}' as u32, CharClassification::Diacritic),
    ('\u{312}' as u32 + 1, CharClassification::Ignore),
    ('\u{315}' as u32, CharClassification::Diacritic),
    ('\u{315}' as u32 + 1, CharClassification::Ignore),
    ('\u{31a}' as u32, CharClassification::Diacritic),
    ('\u{31a}' as u32 + 1, CharClassification::Ignore),
    ('\u{323}' as u32, CharClassification::Diacritic),
    ('\u{323}' as u32 + 1, CharClassification::Ignore),
    ('\u{32c}' as u32, CharClassification::Diacritic),
    ('\u{333}' as u32 + 1, CharClassification::Ignore),
    ('\u{338}' as u32, CharClassification::Diacritic),
    ('\u{338}' as u32 + 1, CharClassification::Ignore),
    ('\u{33a}' as u32, CharClassification::Diacritic),
    ('\u{33a}' as u32 + 1, CharClassification::Ignore),
    ('\u{33f}' as u32, CharClassification::Diacritic),
    ('\u{33f}' as u32 + 1, CharClassification::Ignore),
    ('\u{346}' as u32, CharClassification::Diacritic),
    ('\u{346}' as u32 + 1, CharClassification::Ignore),
    ('\u{34d}' as u32, CharClassification::Diacritic),
    ('\u{34d}' as u32 + 1, CharClassification::Ignore),
    ('Α' as u32, CharClassification::Alphabetic),
    ('Ρ' as u32 + 1, CharClassification::Ignore),
    ('Σ' as u32, CharClassification::Alphabetic),
    ('Ω' as u32 + 1, CharClassification::Ignore),
    ('α' as u32, CharClassification::Alphabetic),
    ('ω' as u32 + 1, CharClassification::Ignore),
    ('ϐ' as u32, CharClassification::Alphabetic),
    ('ϒ' as u32 + 1, CharClassification::Ignore),
    ('ϕ' as u32, CharClassification::Alphabetic),
    ('ϖ' as u32 + 1, CharClassification::Ignore),
    ('Ϙ' as u32, CharClassification::Normal),
    ('Ϛ' as u32, CharClassification::Alphabetic),
    ('ϝ' as u32 + 1, CharClassification::Ignore),
    ('Ϡ' as u32, CharClassification::Alphabetic),
    ('ϡ' as u32 + 1, CharClassification::Ignore),
    ('ϰ' as u32, CharClassification::Alphabetic),
    ('ϱ' as u32 + 1, CharClassification::Ignore),
    ('ϴ' as u32, CharClassification::Alphabetic),
    ('϶' as u32, CharClassification::Normal),
    ('϶' as u32 + 1, CharClassification::Ignore),
    ('Ш' as u32, CharClassification::Alphabetic),
    ('Ш' as u32 + 1, CharClassification::Ignore),
    ('؆' as u32, CharClassification::Large),
    ('؈' as u32, CharClassification::Alphabetic),
    ('؈' as u32 + 1, CharClassification::Ignore),
    ('\u{2000}' as u32, CharClassification::Space),
    ('\u{2007}' as u32 + 1, CharClassification::Ignore),
    ('\u{2009}' as u32, CharClassification::Space),
    ('\u{200b}' as u32 + 1, CharClassification::Ignore),
    ('‐' as u32, CharClassification::Alphabetic),
    ('‐' as u32 + 1, CharClassification::Ignore),
    ('‒' as u32, CharClassification::Punct),
    ('―' as u32, CharClassification::Normal),
    ('‖' as u32, CharClassification::Fence),
    ('‗' as u32, CharClassification::Normal),
    ('‗' as u32 + 1, CharClassification::Ignore),
    ('†' as u32, CharClassification::Binary),
    ('•' as u32 + 1, CharClassification::Ignore),
    ('‥' as u32, CharClassification::Normal),
    ('…' as u32 + 1, CharClassification::Ignore),
    ('′' as u32, CharClassification::Normal),
    ('‸' as u32 + 1, CharClassification::Ignore),
    ('※' as u32, CharClassification::Normal),
    ('‼' as u32 + 1, CharClassification::Ignore),
    ('⁀' as u32, CharClassification::Binary),
    ('⁀' as u32 + 1, CharClassification::Ignore),
    ('⁃' as u32, CharClassification::Normal),
    ('⁄' as u32, CharClassification::Binary),
    ('⁄' as u32 + 1, CharClassification::Ignore),
    ('⁇' as u32, CharClassification::Normal),
    ('⁇' as u32 + 1, CharClassification::Ignore),
    ('⁎' as u32, CharClassification::Binary),
    ('⁏' as u32, CharClassification::Relation),
    ('⁑' as u32, CharClassification::Normal),
    ('⁒' as u32 + 1, CharClassification::Ignore),
    ('⁗' as u32, CharClassification::Normal),
    ('⁗' as u32 + 1, CharClassification::Ignore),
    ('\u{205f}' as u32, CharClassification::Space),
    ('\u{205f}' as u32 + 1, CharClassification::Ignore),
    ('\u{2061}' as u32, CharClassification::Binary),
    ('\u{2063}' as u32, CharClassification::Punct),
    ('\u{2064}' as u32, CharClassification::Special),
    ('\u{2064}' as u32 + 1, CharClassification::Ignore),
    ('⁺' as u32, CharClassification::Normal),
    ('⁾' as u32 + 1, CharClassification::Ignore),
    ('₊' as u32, CharClassification::Normal),
    ('₎' as u32 + 1, CharClassification::Ignore),
    ('€' as u32, CharClassification::Normal),
    ('€' as u32 + 1, CharClassification::Ignore),
    ('\u{20d0}' as u32, CharClassification::Diacritic),
    ('\u{20d3}' as u32, CharClassification::Special),
    ('\u{20d4}' as u32, CharClassification::Diacritic),
    ('\u{20dd}' as u32, CharClassification::Normal),
    ('\u{20df}' as u32 + 1, CharClassification::Ignore),
    ('\u{20e1}' as u32, CharClassification::Diacritic),
    ('\u{20e1}' as u32 + 1, CharClassification::Ignore),
    ('\u{20e4}' as u32, CharClassification::Normal),
    ('\u{20e5}' as u32, CharClassification::Diacritic),
    ('\u{20f0}' as u32 + 1, CharClassification::Ignore),
    ('ℂ' as u32, CharClassification::Alphabetic),
    ('ℂ' as u32 + 1, CharClassification::Ignore),
    ('ℇ' as u32, CharClassification::Normal),
    ('ℇ' as u32 + 1, CharClassification::Ignore),
    ('ℊ' as u32, CharClassification::Alphabetic),
    ('ℎ' as u32, CharClassification::Normal),
    ('ℏ' as u32, CharClassification::Alphabetic),
    ('ℓ' as u32 + 1, CharClassification::Ignore),
    ('ℕ' as u32, CharClassification::Alphabetic),
    ('ℕ' as u32 + 1, CharClassification::Ignore),
    ('℘' as u32, CharClassification::Alphabetic),
    ('ℝ' as u32 + 1, CharClassification::Ignore),
    ('ℤ' as u32, CharClassification::Alphabetic),
    ('ℤ' as u32 + 1, CharClassification::Ignore),
    ('Ω' as u32, CharClassification::Normal),
    ('ℨ' as u32, CharClassification::Alphabetic),
    ('℩' as u32 + 1, CharClassification::Ignore),
    ('Å' as u32, CharClassification::Alphabetic),
    ('ℭ' as u32 + 1, CharClassification::Ignore),
    ('ℯ' as u32, CharClassification::Alphabetic),
    ('Ⅎ' as u32, CharClassification::Normal),
    ('ℳ' as u32, CharClassification::Alphabetic),
    ('ℸ' as u32 + 1, CharClassification::Ignore),
    ('ℼ' as u32, CharClassification::Normal),
    ('ℽ' as u32, CharClassification::Alphabetic),
    ('⅀' as u32, CharClassification::Large),
    ('⅁' as u32, CharClassification::Normal),
    ('⅋' as u32, CharClassification::Binary),
    ('⅋' as u32 + 1, CharClassification::Ignore),
    ('←' as u32, CharClassification::Relation),
    ('↨' as u32, CharClassification::Normal),
    ('↩' as u32, CharClassification::Relation),
    ('↴' as u32, CharClassification::Normal),
    ('↶' as u32, CharClassification::Relation),
    ('↸' as u32, CharClassification::Normal),
    ('↼' as u32, CharClassification::Relation),
    ('⇞' as u32, CharClassification::Normal),
    ('⇤' as u32, CharClassification::Relation),
    ('⇦' as u32, CharClassification::Normal),
    ('⇫' as u32, CharClassification::Relation),
    ('∀' as u32, CharClassification::Normal),
    ('∂' as u32, CharClassification::Alphabetic),
    ('∃' as u32, CharClassification::Normal),
    ('∇' as u32, CharClassification::Alphabetic),
    ('∈' as u32, CharClassification::Relation),
    ('∎' as u32, CharClassification::Normal),
    ('∏' as u32, CharClassification::Large),
    ('−' as u32, CharClassification::Binary),
    ('√' as u32, CharClassification::Normal),
    ('∛' as u32, CharClassification::Opening),
    ('∝' as u32, CharClassification::Relation),
    ('∞' as u32, CharClassification::Normal),
    ('∣' as u32, CharClassification::Relation),
    ('∧' as u32, CharClassification::Binary),
    ('∫' as u32, CharClassification::Large),
    ('∴' as u32, CharClassification::Normal),
    ('∶' as u32, CharClassification::Relation),
    ('∸' as u32, CharClassification::Binary),
    ('∹' as u32, CharClassification::Relation),
    ('∾' as u32, CharClassification::Binary),
    ('∿' as u32, CharClassification::Normal),
    ('≀' as u32, CharClassification::Binary),
    ('≁' as u32, CharClassification::Relation),
    ('⊌' as u32, CharClassification::Binary),
    ('⊏' as u32, CharClassification::Relation),
    ('⊓' as u32, CharClassification::Binary),
    ('⊢' as u32, CharClassification::Relation),
    ('⊤' as u32, CharClassification::Normal),
    ('⊦' as u32, CharClassification::Relation),
    ('⊹' as u32, CharClassification::Normal),
    ('⊺' as u32, CharClassification::Binary),
    ('⊾' as u32, CharClassification::Normal),
    ('⋀' as u32, CharClassification::Large),
    ('⋄' as u32, CharClassification::Binary),
    ('⋈' as u32, CharClassification::Relation),
    ('⋉' as u32, CharClassification::Binary),
    ('⋍' as u32, CharClassification::Relation),
    ('⋎' as u32, CharClassification::Binary),
    ('⋐' as u32, CharClassification::Relation),
    ('⋒' as u32, CharClassification::Binary),
    ('⋔' as u32, CharClassification::Relation),
    ('⋯' as u32, CharClassification::Normal),
    ('⋰' as u32, CharClassification::Relation),
    ('⌀' as u32, CharClassification::Normal),
    ('⌀' as u32 + 1, CharClassification::Ignore),
    ('⌂' as u32, CharClassification::Normal),
    ('⌂' as u32 + 1, CharClassification::Ignore),
    ('⌅' as u32, CharClassification::Binary),
    ('⌆' as u32 + 1, CharClassification::Ignore),
    ('⌈' as u32, CharClassification::Opening),
    ('⌉' as u32, CharClassification::Closing),
    ('⌊' as u32, CharClassification::Opening),
    ('⌋' as u32, CharClassification::Closing),
    ('⌋' as u32 + 1, CharClassification::Ignore),
    ('⌐' as u32, CharClassification::Normal),
    ('⌓' as u32 + 1, CharClassification::Ignore),
    ('⌗' as u32, CharClassification::Normal),
    ('⌗' as u32 + 1, CharClassification::Ignore),
    ('⌙' as u32, CharClassification::Normal),
    ('⌙' as u32 + 1, CharClassification::Ignore),
    ('⌜' as u32, CharClassification::Opening),
    ('⌝' as u32, CharClassification::Closing),
    ('⌞' as u32, CharClassification::Opening),
    ('⌟' as u32, CharClassification::Closing),
    ('⌠' as u32, CharClassification::Normal),
    ('⌢' as u32, CharClassification::Relation),
    ('⌣' as u32 + 1, CharClassification::Ignore),
    ('⌬' as u32, CharClassification::Normal),
    ('⌬' as u32 + 1, CharClassification::Ignore),
    ('⌲' as u32, CharClassification::Normal),
    ('⌲' as u32 + 1, CharClassification::Ignore),
    ('⌶' as u32, CharClassification::Normal),
    ('⌶' as u32 + 1, CharClassification::Ignore),
    ('⌽' as u32, CharClassification::Binary),
    ('⌽' as u32 + 1, CharClassification::Ignore),
    ('⌿' as u32, CharClassification::Relation),
    ('⍀' as u32, CharClassification::Normal),
    ('⍀' as u32 + 1, CharClassification::Ignore),
    ('⍓' as u32, CharClassification::Normal),
    ('⍓' as u32 + 1, CharClassification::Ignore),
    ('⍰' as u32, CharClassification::Normal),
    ('⍰' as u32 + 1, CharClassification::Ignore),
    ('⍼' as u32, CharClassification::Normal),
    ('⍼' as u32 + 1, CharClassification::Ignore),
    ('⎔' as u32, CharClassification::Normal),
    ('⎔' as u32 + 1, CharClassification::Ignore),
    ('⎛' as u32, CharClassification::Normal),
    ('⎰' as u32, CharClassification::Opening),
    ('⎱' as u32, CharClassification::Closing),
    ('⎲' as u32, CharClassification::Normal),
    ('⎴' as u32, CharClassification::Diacritic),
    ('⎶' as u32, CharClassification::Normal),
    ('⎹' as u32 + 1, CharClassification::Ignore),
    ('⏎' as u32, CharClassification::Normal),
    ('⏎' as u32 + 1, CharClassification::Ignore),
    ('⏐' as u32, CharClassification::GlyphPart),
    ('⏐' as u32 + 1, CharClassification::Ignore),
    ('⏜' as u32, CharClassification::Diacritic),
    ('⏠' as u32, CharClassification::Normal),
    ('⏧' as u32 + 1, CharClassification::Ignore),
    ('␢' as u32, CharClassification::Normal),
    ('␣' as u32 + 1, CharClassification::Ignore),
    ('Ⓢ' as u32, CharClassification::Normal),
    ('Ⓢ' as u32 + 1, CharClassification::Ignore),
    ('┆' as u32, CharClassification::Normal),
    ('┆' as u32 + 1, CharClassification::Ignore),
    ('▀' as u32, CharClassification::Normal),
    ('▀' as u32 + 1, CharClassification::Ignore),
    ('▄' as u32, CharClassification::Normal),
    ('▄' as u32 + 1, CharClassification::Ignore),
    ('█' as u32, CharClassification::Normal),
    ('█' as u32 + 1, CharClassification::Ignore),
    ('▌' as u32, CharClassification::Normal),
    ('▌' as u32 + 1, CharClassification::Ignore),
    ('▐' as u32, CharClassification::Normal),
    ('▓' as u32 + 1, CharClassification::Ignore),
    ('■' as u32, CharClassification::Normal),
    ('△' as u32, CharClassification::Binary),
    ('▴' as u32, CharClassification::Normal),
    ('▵' as u32, CharClassification::Relation),
    ('▶' as u32, CharClassification::Normal),
    ('▷' as u32, CharClassification::Binary),
    ('▸' as u32, CharClassification::Normal),
    ('◁' as u32, CharClassification::Binary),
    ('◂' as u32, CharClassification::Normal),
    ('○' as u32, CharClassification::Binary),
    ('◌' as u32, CharClassification::Normal),
    ('◫' as u32, CharClassification::Binary),
    ('◬' as u32, CharClassification::Normal),
    ('◿' as u32 + 1, CharClassification::Ignore),
    ('★' as u32, CharClassification::Normal),
    ('☆' as u32 + 1, CharClassification::Ignore),
    ('☉' as u32, CharClassification::Normal),
    ('☉' as u32 + 1, CharClassification::Ignore),
    ('☌' as u32, CharClassification::Normal),
    ('☌' as u32 + 1, CharClassification::Ignore),
    ('☡' as u32, CharClassification::Normal),
    ('☡' as u32 + 1, CharClassification::Ignore),
    ('☻' as u32, CharClassification::Normal),
    ('♄' as u32 + 1, CharClassification::Ignore),
    ('♆' as u32, CharClassification::Normal),
    ('♉' as u32 + 1, CharClassification::Ignore),
    ('♠' as u32, CharClassification::Normal),
    ('♧' as u32 + 1, CharClassification::Ignore),
    ('♩' as u32, CharClassification::Normal),
    ('♫' as u32 + 1, CharClassification::Ignore),
    ('♭' as u32, CharClassification::Normal),
    ('♯' as u32 + 1, CharClassification::Ignore),
    ('♾' as u32, CharClassification::Normal),
    ('♾' as u32 + 1, CharClassification::Ignore),
    ('⚀' as u32, CharClassification::Normal),
    ('⚉' as u32 + 1, CharClassification::Ignore),
    ('⚥' as u32, CharClassification::Normal),
    ('⚥' as u32 + 1, CharClassification::Ignore),
    ('⚪' as u32, CharClassification::Normal),
    ('⚬' as u32 + 1, CharClassification::Ignore),
    ('⚲' as u32, CharClassification::Normal),
    ('⚲' as u32 + 1, CharClassification::Ignore),
    ('✓' as u32, CharClassification::Normal),
    ('✓' as u32 + 1, CharClassification::Ignore),
    ('✗' as u32, CharClassification::Normal),
    ('✗' as u32 + 1, CharClassification::Ignore),
    ('✠' as u32, CharClassification::Normal),
    ('✠' as u32 + 1, CharClassification::Ignore),
    ('✪' as u32, CharClassification::Normal),
    ('✪' as u32 + 1, CharClassification::Ignore),
    ('✶' as u32, CharClassification::Normal),
    ('✶' as u32 + 1, CharClassification::Ignore),
    ('✽' as u32, CharClassification::Normal),
    ('✽' as u32 + 1, CharClassification::Ignore),
    ('❲' as u32, CharClassification::Opening),
    ('❳' as u32, CharClassification::Closing),
    ('❳' as u32 + 1, CharClassification::Ignore),
    ('➛' as u32, CharClassification::Normal),
    ('➛' as u32 + 1, CharClassification::Ignore),
    ('⟀' as u32, CharClassification::Normal),
    ('⟂' as u32, CharClassification::Relation),
    ('⟃' as u32, CharClassification::Normal),
    ('⟅' as u32, CharClassification::Opening),
    ('⟆' as u32, CharClassification::Closing),
    ('⟇' as u32, CharClassification::Binary),
    ('⟈' as u32, CharClassification::Relation),
    ('⟌' as u32, CharClassification::Opening),
    ('⟍' as u32, CharClassification::Relation),
    ('⟎' as u32, CharClassification::Binary),
    ('⟐' as u32, CharClassification::Normal),
    ('⟑' as u32, CharClassification::Binary),
    ('⟒' as u32, CharClassification::Relation),
    ('⟕' as u32, CharClassification::Large),
    ('⟚' as u32, CharClassification::Relation),
    ('⟠' as u32, CharClassification::Binary),
    ('⟦' as u32, CharClassification::Opening),
    ('⟧' as u32, CharClassification::Closing),
    ('⟨' as u32, CharClassification::Opening),
    ('⟩' as u32, CharClassification::Closing),
    ('⟪' as u32, CharClassification::Opening),
    ('⟫' as u32, CharClassification::Closing),
    ('⟬' as u32, CharClassification::Opening),
    ('⟭' as u32, CharClassification::Closing),
    ('⟮' as u32, CharClassification::Opening),
    ('⟯' as u32, CharClassification::Closing),
    ('⟰' as u32, CharClassification::Relation),
    ('⟿' as u32 + 1, CharClassification::Ignore),
    ('⤀' as u32, CharClassification::Relation),
    ('⤫' as u32, CharClassification::Normal),
    ('⤳' as u32, CharClassification::Relation),
    ('⤴' as u32, CharClassification::Normal),
    ('⤶' as u32, CharClassification::Relation),
    ('⦀' as u32, CharClassification::Fence),
    ('⦁' as u32, CharClassification::Normal),
    ('⦂' as u32, CharClassification::Relation),
    ('⦃' as u32, CharClassification::Opening),
    ('⦄' as u32, CharClassification::Closing),
    ('⦅' as u32, CharClassification::Opening),
    ('⦆' as u32, CharClassification::Closing),
    ('⦇' as u32, CharClassification::Opening),
    ('⦈' as u32, CharClassification::Closing),
    ('⦉' as u32, CharClassification::Opening),
    ('⦊' as u32, CharClassification::Closing),
    ('⦋' as u32, CharClassification::Opening),
    ('⦌' as u32, CharClassification::Closing),
    ('⦍' as u32, CharClassification::Opening),
    ('⦎' as u32, CharClassification::Closing),
    ('⦏' as u32, CharClassification::Opening),
    ('⦐' as u32, CharClassification::Closing),
    ('⦑' as u32, CharClassification::Opening),
    ('⦒' as u32, CharClassification::Closing),
    ('⦓' as u32, CharClassification::Opening),
    ('⦔' as u32, CharClassification::Closing),
    ('⦕' as u32, CharClassification::Opening),
    ('⦖' as u32, CharClassification::Closing),
    ('⦗' as u32, CharClassification::Opening),
    ('⦘' as u32, CharClassification::Closing),
    ('⦙' as u32, CharClassification::Normal),
    ('⦵' as u32, CharClassification::Binary),
    ('⦺' as u32, CharClassification::Normal),
    ('⧀' as u32, CharClassification::Binary),
    ('⧂' as u32, CharClassification::Normal),
    ('⧄' as u32, CharClassification::Binary),
    ('⧉' as u32, CharClassification::Normal),
    ('⧍' as u32, CharClassification::Binary),
    ('⧎' as u32, CharClassification::Relation),
    ('⧖' as u32, CharClassification::Binary),
    ('⧘' as u32, CharClassification::Opening),
    ('⧙' as u32, CharClassification::Closing),
    ('⧚' as u32, CharClassification::Opening),
    ('⧛' as u32, CharClassification::Closing),
    ('⧜' as u32, CharClassification::Normal),
    ('⧟' as u32, CharClassification::Relation),
    ('⧠' as u32, CharClassification::Normal),
    ('⧡' as u32, CharClassification::Relation),
    ('⧢' as u32, CharClassification::Binary),
    ('⧣' as u32, CharClassification::Relation),
    ('⧧' as u32, CharClassification::Normal),
    ('⧫' as u32, CharClassification::Binary),
    ('⧬' as u32, CharClassification::Normal),
    ('⧴' as u32, CharClassification::Relation),
    ('⧵' as u32, CharClassification::Binary),
    ('⧸' as u32, CharClassification::Large),
    ('⧺' as u32, CharClassification::Binary),
    ('⧼' as u32, CharClassification::Opening),
    ('⧽' as u32, CharClassification::Closing),
    ('⧾' as u32, CharClassification::Binary),
    ('⨀' as u32, CharClassification::Large),
    ('⨢' as u32, CharClassification::Binary),
    ('⩙' as u32, CharClassification::Relation),
    ('⩚' as u32, CharClassification::Binary),
    ('⩦' as u32, CharClassification::Relation),
    ('⩱' as u32, CharClassification::Binary),
    ('⩳' as u32, CharClassification::Relation),
    ('⫡' as u32, CharClassification::Normal),
    ('⫢' as u32, CharClassification::Relation),
    ('⫱' as u32, CharClassification::Normal),
    ('⫲' as u32, CharClassification::Relation),
    ('⫴' as u32, CharClassification::Binary),
    ('⫷' as u32, CharClassification::Relation),
    ('⫻' as u32, CharClassification::Binary),
    ('⫼' as u32, CharClassification::Large),
    ('⫽' as u32, CharClassification::Binary),
    ('⫿' as u32, CharClassification::Large),
    ('⬀' as u32, CharClassification::Relation),
    ('⬒' as u32, CharClassification::Normal),
    ('⬰' as u32, CharClassification::Relation),
    ('⭌' as u32 + 1, CharClassification::Ignore),
    ('⭐' as u32, CharClassification::Normal),
    ('⭔' as u32 + 1, CharClassification::Ignore),
    ('⮕' as u32, CharClassification::Relation),
    ('⮕' as u32 + 1, CharClassification::Ignore),
    ('⯂' as u32, CharClassification::Normal),
    ('⯈' as u32 + 1, CharClassification::Ignore),
    ('⯊' as u32, CharClassification::Normal),
    ('⯋' as u32 + 1, CharClassification::Ignore),
    ('〈' as u32, CharClassification::Special),
    ('〉' as u32 + 1, CharClassification::Ignore),
    ('〒' as u32, CharClassification::Normal),
    ('〒' as u32 + 1, CharClassification::Ignore),
    ('〚' as u32, CharClassification::Special),
    ('〛' as u32 + 1, CharClassification::Ignore),
    ('〰' as u32, CharClassification::Normal),
    ('〰' as u32 + 1, CharClassification::Ignore),
    ('の' as u32, CharClassification::Normal),
    ('の' as u32 + 1, CharClassification::Ignore),
    ('﬩' as u32, CharClassification::Special),
    ('﬩' as u32 + 1, CharClassification::Ignore),
    ('\u{fe00}' as u32, CharClassification::Diacritic),
    ('\u{fe00}' as u32 + 1, CharClassification::Ignore),
    ('﹡' as u32, CharClassification::Special),
    ('﹦' as u32 + 1, CharClassification::Ignore),
    ('﹨' as u32, CharClassification::Special),
    ('﹨' as u32 + 1, CharClassification::Ignore),
    ('＋' as u32, CharClassification::Special),
    ('＋' as u32 + 1, CharClassification::Ignore),
    ('＜' as u32, CharClassification::Special),
    ('＞' as u32 + 1, CharClassification::Ignore),
    ('＼' as u32, CharClassification::Special),
    ('＼' as u32 + 1, CharClassification::Ignore),
    ('＾' as u32, CharClassification::Special),
    ('＾' as u32 + 1, CharClassification::Ignore),
    ('｜' as u32, CharClassification::Special),
    ('｜' as u32 + 1, CharClassification::Ignore),
    ('～' as u32, CharClassification::Special),
    ('～' as u32 + 1, CharClassification::Ignore),
    ('￢' as u32, CharClassification::Special),
    ('￢' as u32 + 1, CharClassification::Ignore),
    ('￩' as u32, CharClassification::Special),
    ('￬' as u32 + 1, CharClassification::Ignore),
    ('𝐀' as u32, CharClassification::Alphabetic),
    ('𝑔' as u32 + 1, CharClassification::Ignore),
    ('𝑖' as u32, CharClassification::Alphabetic),
    ('𝒜' as u32 + 1, CharClassification::Ignore),
    ('𝒞' as u32, CharClassification::Alphabetic),
    ('𝒟' as u32 + 1, CharClassification::Ignore),
    ('𝒢' as u32, CharClassification::Alphabetic),
    ('𝒢' as u32 + 1, CharClassification::Ignore),
    ('𝒥' as u32, CharClassification::Alphabetic),
    ('𝒦' as u32 + 1, CharClassification::Ignore),
    ('𝒩' as u32, CharClassification::Alphabetic),
    ('𝒬' as u32 + 1, CharClassification::Ignore),
    ('𝒮' as u32, CharClassification::Alphabetic),
    ('𝒹' as u32 + 1, CharClassification::Ignore),
    ('𝒻' as u32, CharClassification::Alphabetic),
    ('𝒻' as u32 + 1, CharClassification::Ignore),
    ('𝒽' as u32, CharClassification::Alphabetic),
    ('𝓃' as u32 + 1, CharClassification::Ignore),
    ('𝓅' as u32, CharClassification::Alphabetic),
    ('𝔅' as u32 + 1, CharClassification::Ignore),
    ('𝔇' as u32, CharClassification::Alphabetic),
    ('𝔊' as u32 + 1, CharClassification::Ignore),
    ('𝔍' as u32, CharClassification::Alphabetic),
    ('𝔔' as u32 + 1, CharClassification::Ignore),
    ('𝔖' as u32, CharClassification::Alphabetic),
    ('𝔜' as u32 + 1, CharClassification::Ignore),
    ('𝔞' as u32, CharClassification::Alphabetic),
    ('𝔹' as u32 + 1, CharClassification::Ignore),
    ('𝔻' as u32, CharClassification::Alphabetic),
    ('𝔾' as u32 + 1, CharClassification::Ignore),
    ('𝕀' as u32, CharClassification::Alphabetic),
    ('𝕄' as u32 + 1, CharClassification::Ignore),
    ('𝕆' as u32, CharClassification::Alphabetic),
    ('𝕆' as u32 + 1, CharClassification::Ignore),
    ('𝕊' as u32, CharClassification::Alphabetic),
    ('𝕐' as u32 + 1, CharClassification::Ignore),
    ('𝕒' as u32, CharClassification::Alphabetic),
    ('𝚥' as u32 + 1, CharClassification::Ignore),
    ('𝚨' as u32, CharClassification::Alphabetic),
    ('𝟋' as u32 + 1, CharClassification::Ignore),
    ('𝟎' as u32, CharClassification::Normal),
    ('𝟿' as u32 + 1, CharClassification::Ignore),
    ('𞸀' as u32, CharClassification::Alphabetic),
    ('𞸃' as u32 + 1, CharClassification::Ignore),
    ('𞸅' as u32, CharClassification::Alphabetic),
    ('𞸟' as u32 + 1, CharClassification::Ignore),
    ('𞸡' as u32, CharClassification::Alphabetic),
    ('𞸢' as u32 + 1, CharClassification::Ignore),
    ('𞸤' as u32, CharClassification::Alphabetic),
    ('𞸤' as u32 + 1, CharClassification::Ignore),
    ('𞸧' as u32, CharClassification::Alphabetic),
    ('𞸧' as u32 + 1, CharClassification::Ignore),
    ('𞸩' as u32, CharClassification::Alphabetic),
    ('𞸲' as u32 + 1, CharClassification::Ignore),
    ('𞸴' as u32, CharClassification::Alphabetic),
    ('𞸷' as u32 + 1, CharClassification::Ignore),
    ('𞸹' as u32, CharClassification::Alphabetic),
    ('𞸹' as u32 + 1, CharClassification::Ignore),
    ('𞸻' as u32, CharClassification::Alphabetic),
    ('𞸻' as u32 + 1, CharClassification::Ignore),
    ('𞹂' as u32, CharClassification::Alphabetic),
    ('𞹂' as u32 + 1, CharClassification::Ignore),
    ('𞹇' as u32, CharClassification::Alphabetic),
    ('𞹇' as u32 + 1, CharClassification::Ignore),
    ('𞹉' as u32, CharClassification::Alphabetic),
    ('𞹉' as u32 + 1, CharClassification::Ignore),
    ('𞹋' as u32, CharClassification::Alphabetic),
    ('𞹋' as u32 + 1, CharClassification::Ignore),
    ('𞹍' as u32, CharClassification::Alphabetic),
    ('𞹏' as u32 + 1, CharClassification::Ignore),
    ('𞹑' as u32, CharClassification::Alphabetic),
    ('𞹒' as u32 + 1, CharClassification::Ignore),
    ('𞹔' as u32, CharClassification::Alphabetic),
    ('𞹔' as u32 + 1, CharClassification::Ignore),
    ('𞹗' as u32, CharClassification::Alphabetic),
    ('𞹗' as u32 + 1, CharClassification::Ignore),
    ('𞹙' as u32, CharClassification::Alphabetic),
    ('𞹙' as u32 + 1, CharClassification::Ignore),
    ('𞹛' as u32, CharClassification::Alphabetic),
    ('𞹛' as u32 + 1, CharClassification::Ignore),
    ('𞹝' as u32, CharClassification::Alphabetic),
    ('𞹝' as u32 + 1, CharClassification::Ignore),
    ('𞹟' as u32, CharClassification::Alphabetic),
    ('𞹟' as u32 + 1, CharClassification::Ignore),
    ('𞹡' as u32, CharClassification::Alphabetic),
    ('𞹢' as u32 + 1, CharClassification::Ignore),
    ('𞹤' as u32, CharClassification::Alphabetic),
    ('𞹤' as u32 + 1, CharClassification::Ignore),
    ('𞹧' as u32, CharClassification::Alphabetic),
    ('𞹪' as u32 + 1, CharClassification::Ignore),
    ('𞹬' as u32, CharClassification::Alphabetic),
    ('𞹲' as u32 + 1, CharClassification::Ignore),
    ('𞹴' as u32, CharClassification::Alphabetic),
    ('𞹷' as u32 + 1, CharClassification::Ignore),
    ('𞹹' as u32, CharClassification::Alphabetic),
    ('𞹼' as u32 + 1, CharClassification::Ignore),
    ('𞹾' as u32, CharClassification::Alphabetic),
    ('𞹾' as u32 + 1, CharClassification::Ignore),
    ('𞺀' as u32, CharClassification::Alphabetic),
    ('𞺉' as u32 + 1, CharClassification::Ignore),
    ('𞺋' as u32, CharClassification::Alphabetic),
    ('𞺛' as u32 + 1, CharClassification::Ignore),
    ('𞺡' as u32, CharClassification::Alphabetic),
    ('𞺣' as u32 + 1, CharClassification::Ignore),
    ('𞺥' as u32, CharClassification::Alphabetic),
    ('𞺩' as u32 + 1, CharClassification::Ignore),
    ('𞺫' as u32, CharClassification::Alphabetic),
    ('𞺻' as u32 + 1, CharClassification::Ignore),
    ('𞻰' as u32, CharClassification::Large),
    ('𞻱' as u32 + 1, CharClassification::Ignore),
    ('🞄' as u32, CharClassification::Normal),
    ('🞄' as u32 + 1, CharClassification::Ignore),
    ('🞌' as u32, CharClassification::Normal),
    ('🞍' as u32 + 1, CharClassification::Ignore),
    ('🞗' as u32, CharClassification::Normal),
    ('🞙' as u32 + 1, CharClassification::Ignore),
    ('🞝' as u32, CharClassification::Normal),
    ('🞟' as u32 + 1, CharClassification::Ignore),
];

pub static CHAR_COMMANDS: [(&'static str, char); 2446] = [
    ("APLboxquestion", '⍰'),
    ("APLboxupcaret", '⍓'),
    ("APLnotbackslash", '⍀'),
    ("APLnotslash", '⌿'),
    ("Angstrom", 'Å'),
    ("Barv", '⫧'),
    ("BbbA", '𝔸'),
    ("BbbB", '𝔹'),
    ("BbbC", 'ℂ'),
    ("BbbD", '𝔻'),
    ("BbbE", '𝔼'),
    ("BbbF", '𝔽'),
    ("BbbG", '𝔾'),
    ("BbbGamma", 'ℾ'),
    ("BbbH", 'ℍ'),
    ("BbbI", '𝕀'),
    ("BbbJ", '𝕁'),
    ("BbbK", '𝕂'),
    ("BbbL", '𝕃'),
    ("BbbM", '𝕄'),
    ("BbbN", 'ℕ'),
    ("BbbO", '𝕆'),
    ("BbbP", 'ℙ'),
    ("BbbPi", 'ℿ'),
    ("BbbQ", 'ℚ'),
    ("BbbR", 'ℝ'),
    ("BbbS", '𝕊'),
    ("BbbT", '𝕋'),
    ("BbbU", '𝕌'),
    ("BbbV", '𝕍'),
    ("BbbW", '𝕎'),
    ("BbbX", '𝕏'),
    ("BbbY", '𝕐'),
    ("BbbZ", 'ℤ'),
    ("Bbba", '𝕒'),
    ("Bbbb", '𝕓'),
    ("Bbbc", '𝕔'),
    ("Bbbd", '𝕕'),
    ("Bbbe", '𝕖'),
    ("Bbbeight", '𝟠'),
    ("Bbbf", '𝕗'),
    ("Bbbfive", '𝟝'),
    ("Bbbfour", '𝟜'),
    ("Bbbg", '𝕘'),
    ("Bbbgamma", 'ℽ'),
    ("Bbbh", '𝕙'),
    ("Bbbi", '𝕚'),
    ("Bbbj", '𝕛'),
    ("Bbbk", '𝕜'),
    ("Bbbl", '𝕝'),
    ("Bbbm", '𝕞'),
    ("Bbbn", '𝕟'),
    ("Bbbnine", '𝟡'),
    ("Bbbo", '𝕠'),
    ("Bbbone", '𝟙'),
    ("Bbbp", '𝕡'),
    ("Bbbpi", 'ℼ'),
    ("Bbbq", '𝕢'),
    ("Bbbr", '𝕣'),
    ("Bbbs", '𝕤'),
    ("Bbbseven", '𝟟'),
    ("Bbbsix", '𝟞'),
    ("Bbbsum", '⅀'),
    ("Bbbt", '𝕥'),
    ("Bbbthree", '𝟛'),
    ("Bbbtwo", '𝟚'),
    ("Bbbu", '𝕦'),
    ("Bbbv", '𝕧'),
    ("Bbbw", '𝕨'),
    ("Bbbx", '𝕩'),
    ("Bbby", '𝕪'),
    ("Bbbz", '𝕫'),
    ("Bbbzero", '𝟘'),
    ("Bumpeq", '≎'),
    ("Cap", '⋒'),
    ("Colon", '∷'),
    ("Coloneq", '⩴'),
    ("Cup", '⋓'),
    ("DDownarrow", '⟱'),
    ("DashV", '⫥'),
    ("DashVDash", '⟚'),
    ("Dashv", '⫤'),
    ("Ddownarrow", '⤋'),
    ("Doteq", '≑'),
    ("Downarrow", '⇓'),
    ("Equiv", '≣'),
    ("Eulerconst", 'ℇ'),
    ("Exclam", '‼'),
    ("Finv", 'Ⅎ'),
    ("Game", '⅁'),
    ("Gt", '⪢'),
    ("Hermaphrodite", '⚥'),
    ("Im", 'ℑ'),
    ("Join", '⨝'),
    ("LLeftarrow", '⭅'),
    ("Lbrbrak", '⟬'),
    ("Ldsh", '↲'),
    ("Leftarrow", '⇐'),
    ("Leftrightarrow", '⇔'),
    ("Lleftarrow", '⇚'),
    ("Longleftarrow", '⟸'),
    ("Longleftrightarrow", '⟺'),
    ("Longmapsfrom", '⟽'),
    ("Longmapsto", '⟾'),
    ("Longrightarrow", '⟹'),
    ("Lparengtr", '⦕'),
    ("Lsh", '↰'),
    ("Lt", '⪡'),
    ("Lvzigzag", '⧚'),
    ("Mapsfrom", '⤆'),
    ("Mapsto", '⤇'),
    ("Nearrow", '⇗'),
    ("Not", '⫬'),
    ("Nwarrow", '⇖'),
    ("Otimes", '⨷'),
    ("Planckconst", 'ℎ'),
    ("Prec", '⪻'),
    ("PropertyLine", '⅊'),
    ("QED", '∎'),
    ("Question", '⁇'),
    ("RRightarrow", '⭆'),
    ("Rbrbrak", '⟭'),
    ("Rdsh", '↳'),
    ("Re", 'ℜ'),
    ("Rightarrow", '⇒'),
    ("Rparenless", '⦖'),
    ("Rrightarrow", '⇛'),
    ("Rsh", '↱'),
    ("Rvzigzag", '⧛'),
    ("Searrow", '⇘'),
    ("Sqcap", '⩎'),
    ("Sqcup", '⩏'),
    ("Subset", '⋐'),
    ("Succ", '⪼'),
    ("Supset", '⋑'),
    ("Swarrow", '⇙'),
    ("UUparrow", '⟰'),
    ("Uparrow", '⇑'),
    ("Updownarrow", '⇕'),
    ("Uuparrow", '⤊'),
    ("VDash", '⊫'),
    ("Vbar", '⫫'),
    ("Vdash", '⊩'),
    ("Vee", '⩔'),
    ("Vert", '‖'),
    ("Vvdash", '⊪'),
    ("Vvert", '⦀'),
    ("Wedge", '⩓'),
    ("Yup", '⅄'),
    ("Zbar", 'Ƶ'),
    ("accurrent", '⏦'),
    ("acidfree", '♾'),
    ("acute", '\u{301}'),
    ("acwcirclearrow", '⥀'),
    ("acwgapcirclearrow", '⟲'),
    ("acwleftarcarrow", '⤹'),
    ("acwopencirclearrow", '↺'),
    ("acwoverarcarrow", '⤺'),
    ("acwunderarcarrow", '⤻'),
    ("adots", '⋰'),
    ("aleph", 'ℵ'),
    ("amalg", '⨿'),
    ("angdnr", '⦟'),
    ("angle", '∠'),
    ("angles", '⦞'),
    ("angleubar", '⦤'),
    ("annuity", '\u{20e7}'),
    ("approx", '≈'),
    ("approxeq", '≊'),
    ("approxeqq", '⩰'),
    ("approxident", '≋'),
    ("arabichad", '𞻱'),
    ("arabicmaj", '𞻰'),
    ("arceq", '≘'),
    ("assert", '⊦'),
    ("ast", '∗'),
    ("asteq", '⩮'),
    ("asteraccent", '\u{20f0}'),
    ("astrosun", '☉'),
    ("asymp", '≍'),
    ("awint", '⨑'),
    ("bNot", '⫭'),
    ("backcong", '≌'),
    ("backdprime", '‶'),
    ("backprime", '‵'),
    ("backsim", '∽'),
    ("backsimeq", '⋍'),
    ("backslash", '\\'),
    ("backtrprime", '‷'),
    ("bagmember", '⋿'),
    ("bar", '\u{304}'),
    ("barV", '⫪'),
    ("barcap", '⩃'),
    ("barcup", '⩂'),
    ("bardownharpoonleft", '⥡'),
    ("bardownharpoonright", '⥝'),
    ("barleftarrow", '⇤'),
    ("barleftarrowrightarrowbar", '↹'),
    ("barleftharpoondown", '⥖'),
    ("barleftharpoonup", '⥒'),
    ("barovernorthwestarrow", '↸'),
    ("barrightarrowdiamond", '⤠'),
    ("barrightharpoondown", '⥟'),
    ("barrightharpoonup", '⥛'),
    ("baruparrow", '⤒'),
    ("barupharpoonleft", '⥘'),
    ("barupharpoonright", '⥔'),
    ("barvee", '⊽'),
    ("barwedge", '⊼'),
    ("bbrktbrk", '⎶'),
    ("bdtriplevdash", '┆'),
    ("because", '∵'),
    ("benzenr", '⏣'),
    ("beth", 'ℶ'),
    ("between", '≬'),
    ("bigblacktriangledown", '▼'),
    ("bigblacktriangleup", '▲'),
    ("bigbot", '⟘'),
    ("bigcap", '⋂'),
    ("bigcup", '⋃'),
    ("bigcupdot", '⨃'),
    ("biginterleave", '⫼'),
    ("bigodot", '⨀'),
    ("bigoplus", '⨁'),
    ("bigotimes", '⨂'),
    ("bigslopedvee", '⩗'),
    ("bigslopedwedge", '⩘'),
    ("bigsqcap", '⨅'),
    ("bigsqcup", '⨆'),
    ("bigstar", '★'),
    ("bigtalloblong", '⫿'),
    ("bigtimes", '⨉'),
    ("bigtop", '⟙'),
    ("bigtriangledown", '▽'),
    ("bigtriangleleft", '⨞'),
    ("bigtriangleup", '△'),
    ("biguplus", '⨄'),
    ("bigvee", '⋁'),
    ("bigwedge", '⋀'),
    ("bigwhitestar", '☆'),
    ("blackcircledownarrow", '⧭'),
    ("blackcircledrightdot", '⚈'),
    ("blackcircledtwodots", '⚉'),
    ("blackcircleulquadwhite", '◕'),
    ("blackdiamonddownarrow", '⧪'),
    ("blackhourglass", '⧗'),
    ("blackinwhitediamond", '◈'),
    ("blackinwhitesquare", '▣'),
    ("blacklefthalfcircle", '◖'),
    ("blackpointerleft", '◄'),
    ("blackpointerright", '►'),
    ("blackrighthalfcircle", '◗'),
    ("blacksmiley", '☻'),
    ("blacktriangle", '▴'),
    ("blacktriangledown", '▾'),
    ("blacktriangleleft", '◀'),
    ("blacktriangleright", '▶'),
    ("blanksymbol", '␢'),
    ("blkhorzoval", '⬬'),
    ("blkvertoval", '⬮'),
    ("blockfull", '█'),
    ("blockhalfshaded", '▒'),
    ("blocklefthalf", '▌'),
    ("blocklowhalf", '▄'),
    ("blockqtrshaded", '░'),
    ("blockrighthalf", '▐'),
    ("blockthreeqtrshaded", '▓'),
    ("blockuphalf", '▀'),
    ("bot", '⊥'),
    ("botsemicircle", '◡'),
    ("bowtie", '⋈'),
    ("boxast", '⧆'),
    ("boxbar", '◫'),
    ("boxbox", '⧈'),
    ("boxbslash", '⧅'),
    ("boxcircle", '⧇'),
    ("boxdiag", '⧄'),
    ("boxdot", '⊡'),
    ("boxminus", '⊟'),
    ("boxonbox", '⧉'),
    ("boxplus", '⊞'),
    ("boxtimes", '⊠'),
    ("breve", '\u{306}'),
    ("bsimilarleftarrow", '⭁'),
    ("bsimilarrightarrow", '⭇'),
    ("bsolhsub", '⟈'),
    ("btimes", '⨲'),
    ("bullseye", '◎'),
    ("bumpeq", '≏'),
    ("bumpeqq", '⪮'),
    ("candra", '\u{310}'),
    ("cap", '∩'),
    ("capbarcup", '⩉'),
    ("capdot", '⩀'),
    ("capovercup", '⩇'),
    ("capwedge", '⩄'),
    ("caretinsert", '‸'),
    ("carriagereturn", '↵'),
    ("ccwundercurvearrow", '⤿'),
    ("cdot", '⋅'),
    ("cdotp", '·'),
    ("check", '\u{30c}'),
    ("checkmark", '✓'),
    ("cirE", '⧃'),
    ("cirbot", '⟟'),
    ("circeq", '≗'),
    ("circlebottomhalfblack", '◒'),
    ("circledast", '⊛'),
    ("circledbullet", '⦿'),
    ("circledcirc", '⊚'),
    ("circleddash", '⊝'),
    ("circledequal", '⊜'),
    ("circledownarrow", '⧬'),
    ("circledparallel", '⦷'),
    ("circledrightdot", '⚆'),
    ("circledstar", '✪'),
    ("circledtwodots", '⚇'),
    ("circledvert", '⦶'),
    ("circledwhitebullet", '⦾'),
    ("circlehbar", '⦵'),
    ("circlelefthalfblack", '◐'),
    ("circlellquad", '◵'),
    ("circlelrquad", '◶'),
    ("circleonleftarrow", '⬰'),
    ("circleonrightarrow", '⇴'),
    ("circlerighthalfblack", '◑'),
    ("circletophalfblack", '◓'),
    ("circleulquad", '◴'),
    ("circleurquad", '◷'),
    ("circleurquadblack", '◔'),
    ("circlevertfill", '◍'),
    ("cirfnint", '⨐'),
    ("cirmid", '⫯'),
    ("cirscir", '⧂'),
    ("closedvarcap", '⩍'),
    ("closedvarcup", '⩌'),
    ("closedvarcupsmashprod", '⩐'),
    ("closure", '⁐'),
    ("clubsuit", '♣'),
    ("coloneq", '≔'),
    ("commaminus", '⨩'),
    ("complement", '∁'),
    ("concavediamond", '⟡'),
    ("concavediamondtickleft", '⟢'),
    ("concavediamondtickright", '⟣'),
    ("cong", '≅'),
    ("congdot", '⩭'),
    ("conictaper", '⌲'),
    ("conjquant", '⨇'),
    ("coprod", '∐'),
    ("csub", '⫏'),
    ("csube", '⫑'),
    ("csup", '⫐'),
    ("csupe", '⫒'),
    ("cuberoot", '∛'),
    ("cup", '∪'),
    ("cupbarcap", '⩈'),
    ("cupdot", '⊍'),
    ("cupleftarrow", '⊌'),
    ("cupovercap", '⩆'),
    ("cupvee", '⩅'),
    ("curlyeqprec", '⋞'),
    ("curlyeqsucc", '⋟'),
    ("curlyvee", '⋎'),
    ("curlywedge", '⋏'),
    ("curvearrowleft", '↶'),
    ("curvearrowleftplus", '⤽'),
    ("curvearrowright", '↷'),
    ("curvearrowrightminus", '⤼'),
    ("cwcirclearrow", '⥁'),
    ("cwgapcirclearrow", '⟳'),
    ("cwopencirclearrow", '↻'),
    ("cwrightarcarrow", '⤸'),
    ("cwundercurvearrow", '⤾'),
    ("dagger", '†'),
    ("daleth", 'ℸ'),
    ("danger", '☡'),
    ("dashV", '⫣'),
    ("dashVdash", '⟛'),
    ("dashcolon", '∹'),
    ("dashleftharpoondown", '⥫'),
    ("dashrightharpoondown", '⥭'),
    ("dashv", '⊣'),
    ("dbkarrow", '⤏'),
    ("ddagger", '‡'),
    ("ddddot", '\u{20dc}'),
    ("dddot", '\u{20db}'),
    ("ddot", '\u{308}'),
    ("ddots", '⋱'),
    ("ddotseq", '⩷'),
    ("diameter", '⌀'),
    ("diamondbotblack", '⬙'),
    ("diamondcdot", '⟐'),
    ("diamondleftarrow", '⤝'),
    ("diamondleftarrowbar", '⤟'),
    ("diamondleftblack", '⬖'),
    ("diamondrightblack", '⬗'),
    ("diamondsuit", '♢'),
    ("diamondtopblack", '⬘'),
    ("dicei", '⚀'),
    ("diceii", '⚁'),
    ("diceiii", '⚂'),
    ("diceiv", '⚃'),
    ("dicev", '⚄'),
    ("dicevi", '⚅'),
    ("dingasterisk", '✽'),
    ("disin", '⋲'),
    ("disjquant", '⨈'),
    ("div", '÷'),
    ("divideontimes", '⋇'),
    ("divslash", '∕'),
    ("dot", '\u{307}'),
    ("doteq", '≐'),
    ("dotequiv", '⩧'),
    ("dotminus", '∸'),
    ("dotplus", '∔'),
    ("dotsim", '⩪'),
    ("dotsminusdots", '∺'),
    ("dottedcircle", '◌'),
    ("dottedsquare", '⬚'),
    ("dottimes", '⨰'),
    ("doublebarvee", '⩢'),
    ("doublebarwedge", '⩞'),
    ("doubleplus", '⧺'),
    ("downarrow", '↓'),
    ("downarrowbar", '⤓'),
    ("downarrowbarred", '⤈'),
    ("downdasharrow", '⇣'),
    ("downdownarrows", '⇊'),
    ("downfishtail", '⥿'),
    ("downharpoonleft", '⇃'),
    ("downharpoonleftbar", '⥙'),
    ("downharpoonright", '⇂'),
    ("downharpoonrightbar", '⥕'),
    ("downharpoonsleftright", '⥥'),
    ("downrightcurvedarrow", '⤵'),
    ("downtriangleleftblack", '⧨'),
    ("downtrianglerightblack", '⧩'),
    ("downuparrows", '⇵'),
    ("downupharpoonsleftright", '⥯'),
    ("downwhitearrow", '⇩'),
    ("downzigzagarrow", '↯'),
    ("dprime", '″'),
    ("draftingarrow", '➛'),
    ("drbkarrow", '⤐'),
    ("droang", '\u{31a}'),
    ("dsol", '⧶'),
    ("dsub", '⩤'),
    ("dualmap", '⧟'),
    ("egsdot", '⪘'),
    ("eighthnote", '♪'),
    ("elinters", '⏧'),
    ("ell", 'ℓ'),
    ("elsdot", '⪗'),
    ("emptysetoarr", '⦳'),
    ("emptysetoarrl", '⦴'),
    ("emptysetobar", '⦱'),
    ("emptysetocirc", '⦲'),
    ("enclosecircle", '\u{20dd}'),
    ("enclosediamond", '\u{20df}'),
    ("enclosesquare", '\u{20de}'),
    ("enclosetriangle", '\u{20e4}'),
    ("enleadertwodots", '‥'),
    ("eparsl", '⧣'),
    ("eqcirc", '≖'),
    ("eqcolon", '≕'),
    ("eqdef", '≝'),
    ("eqdot", '⩦'),
    ("eqeq", '⩵'),
    ("eqeqeq", '⩶'),
    ("eqgtr", '⋝'),
    ("eqless", '⋜'),
    ("eqqgtr", '⪚'),
    ("eqqless", '⪙'),
    ("eqqplus", '⩱'),
    ("eqqsim", '⩳'),
    ("eqqslantgtr", '⪜'),
    ("eqqslantless", '⪛'),
    ("eqsim", '≂'),
    ("eqslantgtr", '⪖'),
    ("eqslantless", '⪕'),
    ("equal", '='),
    ("equalleftarrow", '⭀'),
    ("equalparallel", '⋕'),
    ("equalrightarrow", '⥱'),
    ("equiv", '≡'),
    ("equivDD", '⩸'),
    ("equivVert", '⩨'),
    ("equivVvert", '⩩'),
    ("eqvparsl", '⧥'),
    ("errbarblackcircle", '⧳'),
    ("errbarblackdiamond", '⧱'),
    ("errbarblacksquare", '⧯'),
    ("errbarcircle", '⧲'),
    ("errbardiamond", '⧰'),
    ("errbarsquare", '⧮'),
    ("euro", '€'),
    ("exists", '∃'),
    ("fallingdotseq", '≒'),
    ("fbowtie", '⧓'),
    ("fcmp", '⨾'),
    ("fdiagovnearrow", '⤯'),
    ("fdiagovrdiag", '⤬'),
    ("female", '♀'),
    ("fint", '⨏'),
    ("fisheye", '◉'),
    ("flat", '♭'),
    ("fltns", '⏥'),
    ("forall", '∀'),
    ("forks", '⫝̸'),
    ("forksnot", '⫝'),
    ("forkv", '⫙'),
    ("fourthroot", '∜'),
    ("fourvdots", '⦙'),
    ("fracslash", '⁄'),
    ("frown", '⌢'),
    ("fullouterjoin", '⟗'),
    ("geq", '≥'),
    ("geqq", '≧'),
    ("geqqslant", '⫺'),
    ("geqslant", '⩾'),
    ("gescc", '⪩'),
    ("gesdot", '⪀'),
    ("gesdoto", '⪂'),
    ("gesdotol", '⪄'),
    ("gesles", '⪔'),
    ("gg", '≫'),
    ("ggg", '⋙'),
    ("gggnest", '⫸'),
    ("gimel", 'ℷ'),
    ("glE", '⪒'),
    ("gla", '⪥'),
    ("gleichstark", '⧦'),
    ("glj", '⪤'),
    ("gnapprox", '⪊'),
    ("gneq", '⪈'),
    ("gneqq", '≩'),
    ("gnsim", '⋧'),
    ("grave", '\u{300}'),
    ("greater", '>'),
    ("gsime", '⪎'),
    ("gsiml", '⪐'),
    ("gtcc", '⪧'),
    ("gtcir", '⩺'),
    ("gtlpar", '⦠'),
    ("gtquest", '⩼'),
    ("gtrapprox", '⪆'),
    ("gtrarr", '⥸'),
    ("gtrdot", '⋗'),
    ("gtreqless", '⋛'),
    ("gtreqqless", '⪌'),
    ("gtrless", '≷'),
    ("gtrsim", '≳'),
    ("harrowextender", '⎯'),
    ("hat", '\u{302}'),
    ("hatapprox", '⩯'),
    ("heartsuit", '♡'),
    ("hermitmatrix", '⊹'),
    ("hexagon", '⎔'),
    ("hexagonblack", '⬣'),
    ("hknearrow", '⤤'),
    ("hknwarrow", '⤣'),
    ("hksearrow", '⤥'),
    ("hkswarrow", '⤦'),
    ("hookleftarrow", '↩'),
    ("hookrightarrow", '↪'),
    ("horizbar", '―'),
    ("hourglass", '⧖'),
    ("house", '⌂'),
    ("hrectangle", '▭'),
    ("hrectangleblack", '▬'),
    ("hslash", 'ℏ'),
    ("hyphenbullet", '⁃'),
    ("hzigzag", '〰'),
    ("iiiint", '⨌'),
    ("iiint", '∭'),
    ("iinfin", '⧜'),
    ("iint", '∬'),
    ("imageof", '⊷'),
    ("imath", '𝚤'),
    ("in", '∈'),
    ("increment", '∆'),
    ("infty", '∞'),
    ("int", '∫'),
    ("intBar", '⨎'),
    ("intbar", '⨍'),
    ("intbottom", '⌡'),
    ("intcap", '⨙'),
    ("intclockwise", '∱'),
    ("intcup", '⨚'),
    ("intercal", '⊺'),
    ("interleave", '⫴'),
    ("intextender", '⎮'),
    ("intlarhk", '⨗'),
    ("intprod", '⨼'),
    ("intprodr", '⨽'),
    ("inttop", '⌠'),
    ("intx", '⨘'),
    ("inversebullet", '◘'),
    ("inversewhitecircle", '◙'),
    ("invlazys", '∾'),
    ("invnot", '⌐'),
    ("invwhitelowerhalfcircle", '◛'),
    ("invwhiteupperhalfcircle", '◚'),
    ("isinE", '⋹'),
    ("isindot", '⋵'),
    ("isinobar", '⋷'),
    ("isins", '⋴'),
    ("isinvb", '⋸'),
    ("jmath", '𝚥'),
    ("kernelcontraction", '∻'),
    ("lAngle", '⟪'),
    ("lBrace", '⦃'),
    ("lBrack", '⟦'),
    ("lParen", '⦅'),
    ("langle", '⟨'),
    ("langledot", '⦑'),
    ("laplac", '⧠'),
    ("lat", '⪫'),
    ("late", '⪭'),
    ("lbag", '⟅'),
    ("lblkbrbrak", '⦗'),
    ("lbrace", '{'),
    ("lbracelend", '⎩'),
    ("lbracemid", '⎨'),
    ("lbraceuend", '⎧'),
    ("lbrack", '['),
    ("lbrackextender", '⎢'),
    ("lbracklend", '⎣'),
    ("lbracklltick", '⦏'),
    ("lbrackubar", '⦋'),
    ("lbrackuend", '⎡'),
    ("lbrackultick", '⦍'),
    ("lbrbrak", '❲'),
    ("lceil", '⌈'),
    ("lcurvyangle", '⧼'),
    ("leftarrow", '←'),
    ("leftarrowapprox", '⭊'),
    ("leftarrowbackapprox", '⭂'),
    ("leftarrowbsimilar", '⭋'),
    ("leftarrowless", '⥷'),
    ("leftarrowonoplus", '⬲'),
    ("leftarrowplus", '⥆'),
    ("leftarrowshortrightarrow", '⥃'),
    ("leftarrowsimilar", '⥳'),
    ("leftarrowsubset", '⥺'),
    ("leftarrowtail", '↢'),
    ("leftarrowtriangle", '⇽'),
    ("leftarrowx", '⬾'),
    ("leftbkarrow", '⤌'),
    ("leftcurvedarrow", '⬿'),
    ("leftdasharrow", '⇠'),
    ("leftdbkarrow", '⤎'),
    ("leftdbltail", '⤛'),
    ("leftdotarrow", '⬸'),
    ("leftdowncurvedarrow", '⤶'),
    ("leftfishtail", '⥼'),
    ("leftharpoonaccent", '\u{20d0}'),
    ("leftharpoondown", '↽'),
    ("leftharpoondownbar", '⥞'),
    ("leftharpoonsupdown", '⥢'),
    ("leftharpoonup", '↼'),
    ("leftharpoonupbar", '⥚'),
    ("leftharpoonupdash", '⥪'),
    ("leftleftarrows", '⇇'),
    ("leftmoon", '☾'),
    ("leftouterjoin", '⟕'),
    ("leftrightarrow", '↔'),
    ("leftrightarrowcircle", '⥈'),
    ("leftrightarrows", '⇆'),
    ("leftrightarrowtriangle", '⇿'),
    ("leftrightharpoondowndown", '⥐'),
    ("leftrightharpoondownup", '⥋'),
    ("leftrightharpoons", '⇋'),
    ("leftrightharpoonsdown", '⥧'),
    ("leftrightharpoonsup", '⥦'),
    ("leftrightharpoonupdown", '⥊'),
    ("leftrightharpoonupup", '⥎'),
    ("leftrightsquigarrow", '↭'),
    ("leftsquigarrow", '⇜'),
    ("lefttail", '⤙'),
    ("leftthreearrows", '⬱'),
    ("leftthreetimes", '⋋'),
    ("leftwavearrow", '↜'),
    ("leftwhitearrow", '⇦'),
    ("leq", '≤'),
    ("leqq", '≦'),
    ("leqqslant", '⫹'),
    ("leqslant", '⩽'),
    ("lescc", '⪨'),
    ("lesdot", '⩿'),
    ("lesdoto", '⪁'),
    ("lesdotor", '⪃'),
    ("lesges", '⪓'),
    ("less", '<'),
    ("lessapprox", '⪅'),
    ("lessdot", '⋖'),
    ("lesseqgtr", '⋚'),
    ("lesseqqgtr", '⪋'),
    ("lessgtr", '≶'),
    ("lesssim", '≲'),
    ("lfbowtie", '⧑'),
    ("lfloor", '⌊'),
    ("lftimes", '⧔'),
    ("lgE", '⪑'),
    ("lgblkcircle", '⬤'),
    ("lgblksquare", '⬛'),
    ("lgroup", '⟮'),
    ("lgwhtcircle", '◯'),
    ("lgwhtsquare", '⬜'),
    ("linefeed", '↴'),
    ("ll", '≪'),
    ("llangle", '⦉'),
    ("llarc", '◟'),
    ("llblacktriangle", '◣'),
    ("llcorner", '⌞'),
    ("lll", '⋘'),
    ("lllnest", '⫷'),
    ("llparenthesis", '⦇'),
    ("lltriangle", '◺'),
    ("lmoustache", '⎰'),
    ("lnapprox", '⪉'),
    ("lneq", '⪇'),
    ("lneqq", '≨'),
    ("lnsim", '⋦'),
    ("longdashv", '⟞'),
    ("longdivision", '⟌'),
    ("longleftarrow", '⟵'),
    ("longleftrightarrow", '⟷'),
    ("longleftsquigarrow", '⬳'),
    ("longmapsfrom", '⟻'),
    ("longmapsto", '⟼'),
    ("longrightarrow", '⟶'),
    ("longrightsquigarrow", '⟿'),
    ("looparrowleft", '↫'),
    ("looparrowright", '↬'),
    ("lowint", '⨜'),
    ("lozengeminus", '⟠'),
    ("lparen", '('),
    ("lparenextender", '⎜'),
    ("lparenlend", '⎝'),
    ("lparenless", '⦓'),
    ("lparenuend", '⎛'),
    ("lrarc", '◞'),
    ("lrblacktriangle", '◢'),
    ("lrcorner", '⌟'),
    ("lrtriangle", '◿'),
    ("lrtriangleeq", '⧡'),
    ("lsime", '⪍'),
    ("lsimg", '⪏'),
    ("lsqhook", '⫍'),
    ("ltcc", '⪦'),
    ("ltcir", '⩹'),
    ("ltimes", '⋉'),
    ("ltlarr", '⥶'),
    ("ltquest", '⩻'),
    ("ltrivb", '⧏'),
    ("lvboxline", '⎸'),
    ("lvzigzag", '⧘'),
    ("male", '♂'),
    ("maltese", '✠'),
    ("mapsdown", '↧'),
    ("mapsfrom", '↤'),
    ("mapsto", '↦'),
    ("mapsup", '↥'),
    ("mathampersand", '&'),
    ("mathatsign", '@'),
    ("mathcolon", ':'),
    ("mathcomma", ','),
    ("mathdollar", '$'),
    ("matheth", 'ð'),
    ("mathexclam", '!'),
    ("mathhyphen", '‐'),
    ("mathoctothorpe", '#'),
    ("mathparagraph", '¶'),
    ("mathpercent", '%'),
    ("mathperiod", '.'),
    ("mathplus", '+'),
    ("mathquestion", '?'),
    ("mathratio", '∶'),
    ("mathsection", '§'),
    ("mathsemicolon", ';'),
    ("mathslash", '/'),
    ("mathsterling", '£'),
    ("mathunderbar", '\u{332}'),
    ("mathvisiblespace", '␣'),
    ("mathyen", '¥'),
    ("mbfA", '𝐀'),
    ("mbfAlpha", '𝚨'),
    ("mbfB", '𝐁'),
    ("mbfBeta", '𝚩'),
    ("mbfC", '𝐂'),
    ("mbfChi", '𝚾'),
    ("mbfD", '𝐃'),
    ("mbfDelta", '𝚫'),
    ("mbfDigamma", '𝟊'),
    ("mbfE", '𝐄'),
    ("mbfEpsilon", '𝚬'),
    ("mbfEta", '𝚮'),
    ("mbfF", '𝐅'),
    ("mbfG", '𝐆'),
    ("mbfGamma", '𝚪'),
    ("mbfH", '𝐇'),
    ("mbfI", '𝐈'),
    ("mbfIota", '𝚰'),
    ("mbfJ", '𝐉'),
    ("mbfK", '𝐊'),
    ("mbfKappa", '𝚱'),
    ("mbfL", '𝐋'),
    ("mbfLambda", '𝚲'),
    ("mbfM", '𝐌'),
    ("mbfMu", '𝚳'),
    ("mbfN", '𝐍'),
    ("mbfNu", '𝚴'),
    ("mbfO", '𝐎'),
    ("mbfOmega", '𝛀'),
    ("mbfOmicron", '𝚶'),
    ("mbfP", '𝐏'),
    ("mbfPhi", '𝚽'),
    ("mbfPi", '𝚷'),
    ("mbfPsi", '𝚿'),
    ("mbfQ", '𝐐'),
    ("mbfR", '𝐑'),
    ("mbfRho", '𝚸'),
    ("mbfS", '𝐒'),
    ("mbfSigma", '𝚺'),
    ("mbfT", '𝐓'),
    ("mbfTau", '𝚻'),
    ("mbfTheta", '𝚯'),
    ("mbfU", '𝐔'),
    ("mbfUpsilon", '𝚼'),
    ("mbfV", '𝐕'),
    ("mbfW", '𝐖'),
    ("mbfX", '𝐗'),
    ("mbfXi", '𝚵'),
    ("mbfY", '𝐘'),
    ("mbfZ", '𝐙'),
    ("mbfZeta", '𝚭'),
    ("mbfa", '𝐚'),
    ("mbfalpha", '𝛂'),
    ("mbfb", '𝐛'),
    ("mbfbeta", '𝛃'),
    ("mbfc", '𝐜'),
    ("mbfchi", '𝛘'),
    ("mbfd", '𝐝'),
    ("mbfdelta", '𝛅'),
    ("mbfdigamma", '𝟋'),
    ("mbfe", '𝐞'),
    ("mbfeight", '𝟖'),
    ("mbfepsilon", '𝛜'),
    ("mbfeta", '𝛈'),
    ("mbff", '𝐟'),
    ("mbffive", '𝟓'),
    ("mbffour", '𝟒'),
    ("mbffrakA", '𝕬'),
    ("mbffrakB", '𝕭'),
    ("mbffrakC", '𝕮'),
    ("mbffrakD", '𝕯'),
    ("mbffrakE", '𝕰'),
    ("mbffrakF", '𝕱'),
    ("mbffrakG", '𝕲'),
    ("mbffrakH", '𝕳'),
    ("mbffrakI", '𝕴'),
    ("mbffrakJ", '𝕵'),
    ("mbffrakK", '𝕶'),
    ("mbffrakL", '𝕷'),
    ("mbffrakM", '𝕸'),
    ("mbffrakN", '𝕹'),
    ("mbffrakO", '𝕺'),
    ("mbffrakP", '𝕻'),
    ("mbffrakQ", '𝕼'),
    ("mbffrakR", '𝕽'),
    ("mbffrakS", '𝕾'),
    ("mbffrakT", '𝕿'),
    ("mbffrakU", '𝖀'),
    ("mbffrakV", '𝖁'),
    ("mbffrakW", '𝖂'),
    ("mbffrakX", '𝖃'),
    ("mbffrakY", '𝖄'),
    ("mbffrakZ", '𝖅'),
    ("mbffraka", '𝖆'),
    ("mbffrakb", '𝖇'),
    ("mbffrakc", '𝖈'),
    ("mbffrakd", '𝖉'),
    ("mbffrake", '𝖊'),
    ("mbffrakf", '𝖋'),
    ("mbffrakg", '𝖌'),
    ("mbffrakh", '𝖍'),
    ("mbffraki", '𝖎'),
    ("mbffrakj", '𝖏'),
    ("mbffrakk", '𝖐'),
    ("mbffrakl", '𝖑'),
    ("mbffrakm", '𝖒'),
    ("mbffrakn", '𝖓'),
    ("mbffrako", '𝖔'),
    ("mbffrakp", '𝖕'),
    ("mbffrakq", '𝖖'),
    ("mbffrakr", '𝖗'),
    ("mbffraks", '𝖘'),
    ("mbffrakt", '𝖙'),
    ("mbffraku", '𝖚'),
    ("mbffrakv", '𝖛'),
    ("mbffrakw", '𝖜'),
    ("mbffrakx", '𝖝'),
    ("mbffraky", '𝖞'),
    ("mbffrakz", '𝖟'),
    ("mbfg", '𝐠'),
    ("mbfgamma", '𝛄'),
    ("mbfh", '𝐡'),
    ("mbfi", '𝐢'),
    ("mbfiota", '𝛊'),
    ("mbfitA", '𝑨'),
    ("mbfitAlpha", '𝜜'),
    ("mbfitB", '𝑩'),
    ("mbfitBeta", '𝜝'),
    ("mbfitC", '𝑪'),
    ("mbfitChi", '𝜲'),
    ("mbfitD", '𝑫'),
    ("mbfitDelta", '𝜟'),
    ("mbfitE", '𝑬'),
    ("mbfitEpsilon", '𝜠'),
    ("mbfitEta", '𝜢'),
    ("mbfitF", '𝑭'),
    ("mbfitG", '𝑮'),
    ("mbfitGamma", '𝜞'),
    ("mbfitH", '𝑯'),
    ("mbfitI", '𝑰'),
    ("mbfitIota", '𝜤'),
    ("mbfitJ", '𝑱'),
    ("mbfitK", '𝑲'),
    ("mbfitKappa", '𝜥'),
    ("mbfitL", '𝑳'),
    ("mbfitLambda", '𝜦'),
    ("mbfitM", '𝑴'),
    ("mbfitMu", '𝜧'),
    ("mbfitN", '𝑵'),
    ("mbfitNu", '𝜨'),
    ("mbfitO", '𝑶'),
    ("mbfitOmega", '𝜴'),
    ("mbfitOmicron", '𝜪'),
    ("mbfitP", '𝑷'),
    ("mbfitPhi", '𝜱'),
    ("mbfitPi", '𝜫'),
    ("mbfitPsi", '𝜳'),
    ("mbfitQ", '𝑸'),
    ("mbfitR", '𝑹'),
    ("mbfitRho", '𝜬'),
    ("mbfitS", '𝑺'),
    ("mbfitSigma", '𝜮'),
    ("mbfitT", '𝑻'),
    ("mbfitTau", '𝜯'),
    ("mbfitTheta", '𝜣'),
    ("mbfitU", '𝑼'),
    ("mbfitUpsilon", '𝜰'),
    ("mbfitV", '𝑽'),
    ("mbfitW", '𝑾'),
    ("mbfitX", '𝑿'),
    ("mbfitXi", '𝜩'),
    ("mbfitY", '𝒀'),
    ("mbfitZ", '𝒁'),
    ("mbfitZeta", '𝜡'),
    ("mbfita", '𝒂'),
    ("mbfitalpha", '𝜶'),
    ("mbfitb", '𝒃'),
    ("mbfitbeta", '𝜷'),
    ("mbfitc", '𝒄'),
    ("mbfitchi", '𝝌'),
    ("mbfitd", '𝒅'),
    ("mbfitdelta", '𝜹'),
    ("mbfite", '𝒆'),
    ("mbfitepsilon", '𝝐'),
    ("mbfiteta", '𝜼'),
    ("mbfitf", '𝒇'),
    ("mbfitg", '𝒈'),
    ("mbfitgamma", '𝜸'),
    ("mbfith", '𝒉'),
    ("mbfiti", '𝒊'),
    ("mbfitiota", '𝜾'),
    ("mbfitj", '𝒋'),
    ("mbfitk", '𝒌'),
    ("mbfitkappa", '𝜿'),
    ("mbfitl", '𝒍'),
    ("mbfitlambda", '𝝀'),
    ("mbfitm", '𝒎'),
    ("mbfitmu", '𝝁'),
    ("mbfitn", '𝒏'),
    ("mbfitnabla", '𝜵'),
    ("mbfitnu", '𝝂'),
    ("mbfito", '𝒐'),
    ("mbfitomega", '𝝎'),
    ("mbfitomicron", '𝝄'),
    ("mbfitp", '𝒑'),
    ("mbfitpartial", '𝝏'),
    ("mbfitphi", '𝝓'),
    ("mbfitpi", '𝝅'),
    ("mbfitpsi", '𝝍'),
    ("mbfitq", '𝒒'),
    ("mbfitr", '𝒓'),
    ("mbfitrho", '𝝆'),
    ("mbfits", '𝒔'),
    ("mbfitsansA", '𝘼'),
    ("mbfitsansAlpha", '𝞐'),
    ("mbfitsansB", '𝘽'),
    ("mbfitsansBeta", '𝞑'),
    ("mbfitsansC", '𝘾'),
    ("mbfitsansChi", '𝞦'),
    ("mbfitsansD", '𝘿'),
    ("mbfitsansDelta", '𝞓'),
    ("mbfitsansE", '𝙀'),
    ("mbfitsansEpsilon", '𝞔'),
    ("mbfitsansEta", '𝞖'),
    ("mbfitsansF", '𝙁'),
    ("mbfitsansG", '𝙂'),
    ("mbfitsansGamma", '𝞒'),
    ("mbfitsansH", '𝙃'),
    ("mbfitsansI", '𝙄'),
    ("mbfitsansIota", '𝞘'),
    ("mbfitsansJ", '𝙅'),
    ("mbfitsansK", '𝙆'),
    ("mbfitsansKappa", '𝞙'),
    ("mbfitsansL", '𝙇'),
    ("mbfitsansLambda", '𝞚'),
    ("mbfitsansM", '𝙈'),
    ("mbfitsansMu", '𝞛'),
    ("mbfitsansN", '𝙉'),
    ("mbfitsansNu", '𝞜'),
    ("mbfitsansO", '𝙊'),
    ("mbfitsansOmega", '𝞨'),
    ("mbfitsansOmicron", '𝞞'),
    ("mbfitsansP", '𝙋'),
    ("mbfitsansPhi", '𝞥'),
    ("mbfitsansPi", '𝞟'),
    ("mbfitsansPsi", '𝞧'),
    ("mbfitsansQ", '𝙌'),
    ("mbfitsansR", '𝙍'),
    ("mbfitsansRho", '𝞠'),
    ("mbfitsansS", '𝙎'),
    ("mbfitsansSigma", '𝞢'),
    ("mbfitsansT", '𝙏'),
    ("mbfitsansTau", '𝞣'),
    ("mbfitsansTheta", '𝞗'),
    ("mbfitsansU", '𝙐'),
    ("mbfitsansUpsilon", '𝞤'),
    ("mbfitsansV", '𝙑'),
    ("mbfitsansW", '𝙒'),
    ("mbfitsansX", '𝙓'),
    ("mbfitsansXi", '𝞝'),
    ("mbfitsansY", '𝙔'),
    ("mbfitsansZ", '𝙕'),
    ("mbfitsansZeta", '𝞕'),
    ("mbfitsansa", '𝙖'),
    ("mbfitsansalpha", '𝞪'),
    ("mbfitsansb", '𝙗'),
    ("mbfitsansbeta", '𝞫'),
    ("mbfitsansc", '𝙘'),
    ("mbfitsanschi", '𝟀'),
    ("mbfitsansd", '𝙙'),
    ("mbfitsansdelta", '𝞭'),
    ("mbfitsanse", '𝙚'),
    ("mbfitsansepsilon", '𝟄'),
    ("mbfitsanseta", '𝞰'),
    ("mbfitsansf", '𝙛'),
    ("mbfitsansg", '𝙜'),
    ("mbfitsansgamma", '𝞬'),
    ("mbfitsansh", '𝙝'),
    ("mbfitsansi", '𝙞'),
    ("mbfitsansiota", '𝞲'),
    ("mbfitsansj", '𝙟'),
    ("mbfitsansk", '𝙠'),
    ("mbfitsanskappa", '𝞳'),
    ("mbfitsansl", '𝙡'),
    ("mbfitsanslambda", '𝞴'),
    ("mbfitsansm", '𝙢'),
    ("mbfitsansmu", '𝞵'),
    ("mbfitsansn", '𝙣'),
    ("mbfitsansnabla", '𝞩'),
    ("mbfitsansnu", '𝞶'),
    ("mbfitsanso", '𝙤'),
    ("mbfitsansomega", '𝟂'),
    ("mbfitsansomicron", '𝞸'),
    ("mbfitsansp", '𝙥'),
    ("mbfitsanspartial", '𝟃'),
    ("mbfitsansphi", '𝟇'),
    ("mbfitsanspi", '𝞹'),
    ("mbfitsanspsi", '𝟁'),
    ("mbfitsansq", '𝙦'),
    ("mbfitsansr", '𝙧'),
    ("mbfitsansrho", '𝞺'),
    ("mbfitsanss", '𝙨'),
    ("mbfitsanssigma", '𝞼'),
    ("mbfitsanst", '𝙩'),
    ("mbfitsanstau", '𝞽'),
    ("mbfitsanstheta", '𝞱'),
    ("mbfitsansu", '𝙪'),
    ("mbfitsansupsilon", '𝞾'),
    ("mbfitsansv", '𝙫'),
    ("mbfitsansvarTheta", '𝞡'),
    ("mbfitsansvarepsilon", '𝞮'),
    ("mbfitsansvarkappa", '𝟆'),
    ("mbfitsansvarphi", '𝞿'),
    ("mbfitsansvarpi", '𝟉'),
    ("mbfitsansvarrho", '𝟈'),
    ("mbfitsansvarsigma", '𝞻'),
    ("mbfitsansvartheta", '𝟅'),
    ("mbfitsansw", '𝙬'),
    ("mbfitsansx", '𝙭'),
    ("mbfitsansxi", '𝞷'),
    ("mbfitsansy", '𝙮'),
    ("mbfitsansz", '𝙯'),
    ("mbfitsanszeta", '𝞯'),
    ("mbfitsigma", '𝝈'),
    ("mbfitt", '𝒕'),
    ("mbfittau", '𝝉'),
    ("mbfittheta", '𝜽'),
    ("mbfitu", '𝒖'),
    ("mbfitupsilon", '𝝊'),
    ("mbfitv", '𝒗'),
    ("mbfitvarTheta", '𝜭'),
    ("mbfitvarepsilon", '𝜺'),
    ("mbfitvarkappa", '𝝒'),
    ("mbfitvarphi", '𝝋'),
    ("mbfitvarpi", '𝝕'),
    ("mbfitvarrho", '𝝔'),
    ("mbfitvarsigma", '𝝇'),
    ("mbfitvartheta", '𝝑'),
    ("mbfitw", '𝒘'),
    ("mbfitx", '𝒙'),
    ("mbfitxi", '𝝃'),
    ("mbfity", '𝒚'),
    ("mbfitz", '𝒛'),
    ("mbfitzeta", '𝜻'),
    ("mbfj", '𝐣'),
    ("mbfk", '𝐤'),
    ("mbfkappa", '𝛋'),
    ("mbfl", '𝐥'),
    ("mbflambda", '𝛌'),
    ("mbfm", '𝐦'),
    ("mbfmu", '𝛍'),
    ("mbfn", '𝐧'),
    ("mbfnabla", '𝛁'),
    ("mbfnine", '𝟗'),
    ("mbfnu", '𝛎'),
    ("mbfo", '𝐨'),
    ("mbfomega", '𝛚'),
    ("mbfomicron", '𝛐'),
    ("mbfone", '𝟏'),
    ("mbfp", '𝐩'),
    ("mbfpartial", '𝛛'),
    ("mbfphi", '𝛟'),
    ("mbfpi", '𝛑'),
    ("mbfpsi", '𝛙'),
    ("mbfq", '𝐪'),
    ("mbfr", '𝐫'),
    ("mbfrho", '𝛒'),
    ("mbfs", '𝐬'),
    ("mbfsansA", '𝗔'),
    ("mbfsansAlpha", '𝝖'),
    ("mbfsansB", '𝗕'),
    ("mbfsansBeta", '𝝗'),
    ("mbfsansC", '𝗖'),
    ("mbfsansChi", '𝝬'),
    ("mbfsansD", '𝗗'),
    ("mbfsansDelta", '𝝙'),
    ("mbfsansE", '𝗘'),
    ("mbfsansEpsilon", '𝝚'),
    ("mbfsansEta", '𝝜'),
    ("mbfsansF", '𝗙'),
    ("mbfsansG", '𝗚'),
    ("mbfsansGamma", '𝝘'),
    ("mbfsansH", '𝗛'),
    ("mbfsansI", '𝗜'),
    ("mbfsansIota", '𝝞'),
    ("mbfsansJ", '𝗝'),
    ("mbfsansK", '𝗞'),
    ("mbfsansKappa", '𝝟'),
    ("mbfsansL", '𝗟'),
    ("mbfsansLambda", '𝝠'),
    ("mbfsansM", '𝗠'),
    ("mbfsansMu", '𝝡'),
    ("mbfsansN", '𝗡'),
    ("mbfsansNu", '𝝢'),
    ("mbfsansO", '𝗢'),
    ("mbfsansOmega", '𝝮'),
    ("mbfsansOmicron", '𝝤'),
    ("mbfsansP", '𝗣'),
    ("mbfsansPhi", '𝝫'),
    ("mbfsansPi", '𝝥'),
    ("mbfsansPsi", '𝝭'),
    ("mbfsansQ", '𝗤'),
    ("mbfsansR", '𝗥'),
    ("mbfsansRho", '𝝦'),
    ("mbfsansS", '𝗦'),
    ("mbfsansSigma", '𝝨'),
    ("mbfsansT", '𝗧'),
    ("mbfsansTau", '𝝩'),
    ("mbfsansTheta", '𝝝'),
    ("mbfsansU", '𝗨'),
    ("mbfsansUpsilon", '𝝪'),
    ("mbfsansV", '𝗩'),
    ("mbfsansW", '𝗪'),
    ("mbfsansX", '𝗫'),
    ("mbfsansXi", '𝝣'),
    ("mbfsansY", '𝗬'),
    ("mbfsansZ", '𝗭'),
    ("mbfsansZeta", '𝝛'),
    ("mbfsansa", '𝗮'),
    ("mbfsansalpha", '𝝰'),
    ("mbfsansb", '𝗯'),
    ("mbfsansbeta", '𝝱'),
    ("mbfsansc", '𝗰'),
    ("mbfsanschi", '𝞆'),
    ("mbfsansd", '𝗱'),
    ("mbfsansdelta", '𝝳'),
    ("mbfsanse", '𝗲'),
    ("mbfsanseight", '𝟴'),
    ("mbfsansepsilon", '𝞊'),
    ("mbfsanseta", '𝝶'),
    ("mbfsansf", '𝗳'),
    ("mbfsansfive", '𝟱'),
    ("mbfsansfour", '𝟰'),
    ("mbfsansg", '𝗴'),
    ("mbfsansgamma", '𝝲'),
    ("mbfsansh", '𝗵'),
    ("mbfsansi", '𝗶'),
    ("mbfsansiota", '𝝸'),
    ("mbfsansj", '𝗷'),
    ("mbfsansk", '𝗸'),
    ("mbfsanskappa", '𝝹'),
    ("mbfsansl", '𝗹'),
    ("mbfsanslambda", '𝝺'),
    ("mbfsansm", '𝗺'),
    ("mbfsansmu", '𝝻'),
    ("mbfsansn", '𝗻'),
    ("mbfsansnabla", '𝝯'),
    ("mbfsansnine", '𝟵'),
    ("mbfsansnu", '𝝼'),
    ("mbfsanso", '𝗼'),
    ("mbfsansomega", '𝞈'),
    ("mbfsansomicron", '𝝾'),
    ("mbfsansone", '𝟭'),
    ("mbfsansp", '𝗽'),
    ("mbfsanspartial", '𝞉'),
    ("mbfsansphi", '𝞍'),
    ("mbfsanspi", '𝝿'),
    ("mbfsanspsi", '𝞇'),
    ("mbfsansq", '𝗾'),
    ("mbfsansr", '𝗿'),
    ("mbfsansrho", '𝞀'),
    ("mbfsanss", '𝘀'),
    ("mbfsansseven", '𝟳'),
    ("mbfsanssigma", '𝞂'),
    ("mbfsanssix", '𝟲'),
    ("mbfsanst", '𝘁'),
    ("mbfsanstau", '𝞃'),
    ("mbfsanstheta", '𝝷'),
    ("mbfsansthree", '𝟯'),
    ("mbfsanstwo", '𝟮'),
    ("mbfsansu", '𝘂'),
    ("mbfsansupsilon", '𝞄'),
    ("mbfsansv", '𝘃'),
    ("mbfsansvarTheta", '𝝧'),
    ("mbfsansvarepsilon", '𝝴'),
    ("mbfsansvarkappa", '𝞌'),
    ("mbfsansvarphi", '𝞅'),
    ("mbfsansvarpi", '𝞏'),
    ("mbfsansvarrho", '𝞎'),
    ("mbfsansvarsigma", '𝞁'),
    ("mbfsansvartheta", '𝞋'),
    ("mbfsansw", '𝘄'),
    ("mbfsansx", '𝘅'),
    ("mbfsansxi", '𝝽'),
    ("mbfsansy", '𝘆'),
    ("mbfsansz", '𝘇'),
    ("mbfsanszero", '𝟬'),
    ("mbfsanszeta", '𝝵'),
    ("mbfscrA", '𝓐'),
    ("mbfscrB", '𝓑'),
    ("mbfscrC", '𝓒'),
    ("mbfscrD", '𝓓'),
    ("mbfscrE", '𝓔'),
    ("mbfscrF", '𝓕'),
    ("mbfscrG", '𝓖'),
    ("mbfscrH", '𝓗'),
    ("mbfscrI", '𝓘'),
    ("mbfscrJ", '𝓙'),
    ("mbfscrK", '𝓚'),
    ("mbfscrL", '𝓛'),
    ("mbfscrM", '𝓜'),
    ("mbfscrN", '𝓝'),
    ("mbfscrO", '𝓞'),
    ("mbfscrP", '𝓟'),
    ("mbfscrQ", '𝓠'),
    ("mbfscrR", '𝓡'),
    ("mbfscrS", '𝓢'),
    ("mbfscrT", '𝓣'),
    ("mbfscrU", '𝓤'),
    ("mbfscrV", '𝓥'),
    ("mbfscrW", '𝓦'),
    ("mbfscrX", '𝓧'),
    ("mbfscrY", '𝓨'),
    ("mbfscrZ", '𝓩'),
    ("mbfscra", '𝓪'),
    ("mbfscrb", '𝓫'),
    ("mbfscrc", '𝓬'),
    ("mbfscrd", '𝓭'),
    ("mbfscre", '𝓮'),
    ("mbfscrf", '𝓯'),
    ("mbfscrg", '𝓰'),
    ("mbfscrh", '𝓱'),
    ("mbfscri", '𝓲'),
    ("mbfscrj", '𝓳'),
    ("mbfscrk", '𝓴'),
    ("mbfscrl", '𝓵'),
    ("mbfscrm", '𝓶'),
    ("mbfscrn", '𝓷'),
    ("mbfscro", '𝓸'),
    ("mbfscrp", '𝓹'),
    ("mbfscrq", '𝓺'),
    ("mbfscrr", '𝓻'),
    ("mbfscrs", '𝓼'),
    ("mbfscrt", '𝓽'),
    ("mbfscru", '𝓾'),
    ("mbfscrv", '𝓿'),
    ("mbfscrw", '𝔀'),
    ("mbfscrx", '𝔁'),
    ("mbfscry", '𝔂'),
    ("mbfscrz", '𝔃'),
    ("mbfseven", '𝟕'),
    ("mbfsigma", '𝛔'),
    ("mbfsix", '𝟔'),
    ("mbft", '𝐭'),
    ("mbftau", '𝛕'),
    ("mbftheta", '𝛉'),
    ("mbfthree", '𝟑'),
    ("mbftwo", '𝟐'),
    ("mbfu", '𝐮'),
    ("mbfupsilon", '𝛖'),
    ("mbfv", '𝐯'),
    ("mbfvarTheta", '𝚹'),
    ("mbfvarepsilon", '𝛆'),
    ("mbfvarkappa", '𝛞'),
    ("mbfvarphi", '𝛗'),
    ("mbfvarpi", '𝛡'),
    ("mbfvarrho", '𝛠'),
    ("mbfvarsigma", '𝛓'),
    ("mbfvartheta", '𝛝'),
    ("mbfw", '𝐰'),
    ("mbfx", '𝐱'),
    ("mbfxi", '𝛏'),
    ("mbfy", '𝐲'),
    ("mbfz", '𝐳'),
    ("mbfzero", '𝟎'),
    ("mbfzeta", '𝛇'),
    ("mdblkcircle", '⚫'),
    ("mdblkdiamond", '⬥'),
    ("mdblklozenge", '⬧'),
    ("mdblksquare", '◼'),
    ("mdlgblkcircle", '●'),
    ("mdlgblkdiamond", '◆'),
    ("mdlgblklozenge", '⧫'),
    ("mdlgblksquare", '■'),
    ("mdlgwhtcircle", '○'),
    ("mdlgwhtdiamond", '◇'),
    ("mdlgwhtlozenge", '◊'),
    ("mdlgwhtsquare", '□'),
    ("mdsmblkcircle", '⦁'),
    ("mdsmblksquare", '◾'),
    ("mdsmwhtcircle", '⚬'),
    ("mdsmwhtsquare", '◽'),
    ("mdwhtcircle", '⚪'),
    ("mdwhtdiamond", '⬦'),
    ("mdwhtlozenge", '⬨'),
    ("mdwhtsquare", '◻'),
    ("measangledltosw", '⦯'),
    ("measangledrtose", '⦮'),
    ("measangleldtosw", '⦫'),
    ("measanglelutonw", '⦩'),
    ("measanglerdtose", '⦪'),
    ("measanglerutone", '⦨'),
    ("measangleultonw", '⦭'),
    ("measangleurtone", '⦬'),
    ("measeq", '≞'),
    ("measuredangle", '∡'),
    ("measuredangleleft", '⦛'),
    ("measuredrightangle", '⊾'),
    ("medblackstar", '⭑'),
    ("medwhitestar", '⭐'),
    ("mfrakA", '𝔄'),
    ("mfrakB", '𝔅'),
    ("mfrakC", 'ℭ'),
    ("mfrakD", '𝔇'),
    ("mfrakE", '𝔈'),
    ("mfrakF", '𝔉'),
    ("mfrakG", '𝔊'),
    ("mfrakH", 'ℌ'),
    ("mfrakJ", '𝔍'),
    ("mfrakK", '𝔎'),
    ("mfrakL", '𝔏'),
    ("mfrakM", '𝔐'),
    ("mfrakN", '𝔑'),
    ("mfrakO", '𝔒'),
    ("mfrakP", '𝔓'),
    ("mfrakQ", '𝔔'),
    ("mfrakS", '𝔖'),
    ("mfrakT", '𝔗'),
    ("mfrakU", '𝔘'),
    ("mfrakV", '𝔙'),
    ("mfrakW", '𝔚'),
    ("mfrakX", '𝔛'),
    ("mfrakY", '𝔜'),
    ("mfrakZ", 'ℨ'),
    ("mfraka", '𝔞'),
    ("mfrakb", '𝔟'),
    ("mfrakc", '𝔠'),
    ("mfrakd", '𝔡'),
    ("mfrake", '𝔢'),
    ("mfrakf", '𝔣'),
    ("mfrakg", '𝔤'),
    ("mfrakh", '𝔥'),
    ("mfraki", '𝔦'),
    ("mfrakj", '𝔧'),
    ("mfrakk", '𝔨'),
    ("mfrakl", '𝔩'),
    ("mfrakm", '𝔪'),
    ("mfrakn", '𝔫'),
    ("mfrako", '𝔬'),
    ("mfrakp", '𝔭'),
    ("mfrakq", '𝔮'),
    ("mfrakr", '𝔯'),
    ("mfraks", '𝔰'),
    ("mfrakt", '𝔱'),
    ("mfraku", '𝔲'),
    ("mfrakv", '𝔳'),
    ("mfrakw", '𝔴'),
    ("mfrakx", '𝔵'),
    ("mfraky", '𝔶'),
    ("mfrakz", '𝔷'),
    ("mho", '℧'),
    ("mid", '∣'),
    ("midbarvee", '⩝'),
    ("midbarwedge", '⩜'),
    ("midcir", '⫰'),
    ("minus", '−'),
    ("minusdot", '⨪'),
    ("minusfdots", '⨫'),
    ("minusrdots", '⨬'),
    ("mitA", '𝐴'),
    ("mitAlpha", '𝛢'),
    ("mitB", '𝐵'),
    ("mitBbbD", 'ⅅ'),
    ("mitBbbd", 'ⅆ'),
    ("mitBbbe", 'ⅇ'),
    ("mitBbbi", 'ⅈ'),
    ("mitBbbj", 'ⅉ'),
    ("mitBeta", '𝛣'),
    ("mitC", '𝐶'),
    ("mitChi", '𝛸'),
    ("mitD", '𝐷'),
    ("mitDelta", '𝛥'),
    ("mitE", '𝐸'),
    ("mitEpsilon", '𝛦'),
    ("mitEta", '𝛨'),
    ("mitF", '𝐹'),
    ("mitG", '𝐺'),
    ("mitGamma", '𝛤'),
    ("mitH", '𝐻'),
    ("mitI", '𝐼'),
    ("mitIota", '𝛪'),
    ("mitJ", '𝐽'),
    ("mitK", '𝐾'),
    ("mitKappa", '𝛫'),
    ("mitL", '𝐿'),
    ("mitLambda", '𝛬'),
    ("mitM", '𝑀'),
    ("mitMu", '𝛭'),
    ("mitN", '𝑁'),
    ("mitNu", '𝛮'),
    ("mitO", '𝑂'),
    ("mitOmega", '𝛺'),
    ("mitOmicron", '𝛰'),
    ("mitP", '𝑃'),
    ("mitPhi", '𝛷'),
    ("mitPi", '𝛱'),
    ("mitPsi", '𝛹'),
    ("mitQ", '𝑄'),
    ("mitR", '𝑅'),
    ("mitRho", '𝛲'),
    ("mitS", '𝑆'),
    ("mitSigma", '𝛴'),
    ("mitT", '𝑇'),
    ("mitTau", '𝛵'),
    ("mitTheta", '𝛩'),
    ("mitU", '𝑈'),
    ("mitUpsilon", '𝛶'),
    ("mitV", '𝑉'),
    ("mitW", '𝑊'),
    ("mitX", '𝑋'),
    ("mitXi", '𝛯'),
    ("mitY", '𝑌'),
    ("mitZ", '𝑍'),
    ("mitZeta", '𝛧'),
    ("mita", '𝑎'),
    ("mitalpha", '𝛼'),
    ("mitb", '𝑏'),
    ("mitbeta", '𝛽'),
    ("mitc", '𝑐'),
    ("mitchi", '𝜒'),
    ("mitd", '𝑑'),
    ("mitdelta", '𝛿'),
    ("mite", '𝑒'),
    ("mitepsilon", '𝜖'),
    ("miteta", '𝜂'),
    ("mitf", '𝑓'),
    ("mitg", '𝑔'),
    ("mitgamma", '𝛾'),
    ("miti", '𝑖'),
    ("mitiota", '𝜄'),
    ("mitj", '𝑗'),
    ("mitk", '𝑘'),
    ("mitkappa", '𝜅'),
    ("mitl", '𝑙'),
    ("mitlambda", '𝜆'),
    ("mitm", '𝑚'),
    ("mitmu", '𝜇'),
    ("mitn", '𝑛'),
    ("mitnabla", '𝛻'),
    ("mitnu", '𝜈'),
    ("mito", '𝑜'),
    ("mitomega", '𝜔'),
    ("mitomicron", '𝜊'),
    ("mitp", '𝑝'),
    ("mitpartial", '𝜕'),
    ("mitphi", '𝜙'),
    ("mitpi", '𝜋'),
    ("mitpsi", '𝜓'),
    ("mitq", '𝑞'),
    ("mitr", '𝑟'),
    ("mitrho", '𝜌'),
    ("mits", '𝑠'),
    ("mitsansA", '𝘈'),
    ("mitsansB", '𝘉'),
    ("mitsansC", '𝘊'),
    ("mitsansD", '𝘋'),
    ("mitsansE", '𝘌'),
    ("mitsansF", '𝘍'),
    ("mitsansG", '𝘎'),
    ("mitsansH", '𝘏'),
    ("mitsansI", '𝘐'),
    ("mitsansJ", '𝘑'),
    ("mitsansK", '𝘒'),
    ("mitsansL", '𝘓'),
    ("mitsansM", '𝘔'),
    ("mitsansN", '𝘕'),
    ("mitsansO", '𝘖'),
    ("mitsansP", '𝘗'),
    ("mitsansQ", '𝘘'),
    ("mitsansR", '𝘙'),
    ("mitsansS", '𝘚'),
    ("mitsansT", '𝘛'),
    ("mitsansU", '𝘜'),
    ("mitsansV", '𝘝'),
    ("mitsansW", '𝘞'),
    ("mitsansX", '𝘟'),
    ("mitsansY", '𝘠'),
    ("mitsansZ", '𝘡'),
    ("mitsansa", '𝘢'),
    ("mitsansb", '𝘣'),
    ("mitsansc", '𝘤'),
    ("mitsansd", '𝘥'),
    ("mitsanse", '𝘦'),
    ("mitsansf", '𝘧'),
    ("mitsansg", '𝘨'),
    ("mitsansh", '𝘩'),
    ("mitsansi", '𝘪'),
    ("mitsansj", '𝘫'),
    ("mitsansk", '𝘬'),
    ("mitsansl", '𝘭'),
    ("mitsansm", '𝘮'),
    ("mitsansn", '𝘯'),
    ("mitsanso", '𝘰'),
    ("mitsansp", '𝘱'),
    ("mitsansq", '𝘲'),
    ("mitsansr", '𝘳'),
    ("mitsanss", '𝘴'),
    ("mitsanst", '𝘵'),
    ("mitsansu", '𝘶'),
    ("mitsansv", '𝘷'),
    ("mitsansw", '𝘸'),
    ("mitsansx", '𝘹'),
    ("mitsansy", '𝘺'),
    ("mitsansz", '𝘻'),
    ("mitsigma", '𝜎'),
    ("mitt", '𝑡'),
    ("mittau", '𝜏'),
    ("mittheta", '𝜃'),
    ("mitu", '𝑢'),
    ("mitupsilon", '𝜐'),
    ("mitv", '𝑣'),
    ("mitvarTheta", '𝛳'),
    ("mitvarepsilon", '𝜀'),
    ("mitvarkappa", '𝜘'),
    ("mitvarphi", '𝜑'),
    ("mitvarpi", '𝜛'),
    ("mitvarrho", '𝜚'),
    ("mitvarsigma", '𝜍'),
    ("mitvartheta", '𝜗'),
    ("mitw", '𝑤'),
    ("mitx", '𝑥'),
    ("mitxi", '𝜉'),
    ("mity", '𝑦'),
    ("mitz", '𝑧'),
    ("mitzeta", '𝜁'),
    ("mlcp", '⫛'),
    ("models", '⊧'),
    ("modtwosum", '⨊'),
    ("mp", '∓'),
    ("msansA", '𝖠'),
    ("msansB", '𝖡'),
    ("msansC", '𝖢'),
    ("msansD", '𝖣'),
    ("msansE", '𝖤'),
    ("msansF", '𝖥'),
    ("msansG", '𝖦'),
    ("msansH", '𝖧'),
    ("msansI", '𝖨'),
    ("msansJ", '𝖩'),
    ("msansK", '𝖪'),
    ("msansL", '𝖫'),
    ("msansM", '𝖬'),
    ("msansN", '𝖭'),
    ("msansO", '𝖮'),
    ("msansP", '𝖯'),
    ("msansQ", '𝖰'),
    ("msansR", '𝖱'),
    ("msansS", '𝖲'),
    ("msansT", '𝖳'),
    ("msansU", '𝖴'),
    ("msansV", '𝖵'),
    ("msansW", '𝖶'),
    ("msansX", '𝖷'),
    ("msansY", '𝖸'),
    ("msansZ", '𝖹'),
    ("msansa", '𝖺'),
    ("msansb", '𝖻'),
    ("msansc", '𝖼'),
    ("msansd", '𝖽'),
    ("msanse", '𝖾'),
    ("msanseight", '𝟪'),
    ("msansf", '𝖿'),
    ("msansfive", '𝟧'),
    ("msansfour", '𝟦'),
    ("msansg", '𝗀'),
    ("msansh", '𝗁'),
    ("msansi", '𝗂'),
    ("msansj", '𝗃'),
    ("msansk", '𝗄'),
    ("msansl", '𝗅'),
    ("msansm", '𝗆'),
    ("msansn", '𝗇'),
    ("msansnine", '𝟫'),
    ("msanso", '𝗈'),
    ("msansone", '𝟣'),
    ("msansp", '𝗉'),
    ("msansq", '𝗊'),
    ("msansr", '𝗋'),
    ("msanss", '𝗌'),
    ("msansseven", '𝟩'),
    ("msanssix", '𝟨'),
    ("msanst", '𝗍'),
    ("msansthree", '𝟥'),
    ("msanstwo", '𝟤'),
    ("msansu", '𝗎'),
    ("msansv", '𝗏'),
    ("msansw", '𝗐'),
    ("msansx", '𝗑'),
    ("msansy", '𝗒'),
    ("msansz", '𝗓'),
    ("msanszero", '𝟢'),
    ("mscrA", '𝒜'),
    ("mscrB", 'ℬ'),
    ("mscrC", '𝒞'),
    ("mscrD", '𝒟'),
    ("mscrE", 'ℰ'),
    ("mscrF", 'ℱ'),
    ("mscrG", '𝒢'),
    ("mscrH", 'ℋ'),
    ("mscrI", 'ℐ'),
    ("mscrJ", '𝒥'),
    ("mscrK", '𝒦'),
    ("mscrL", 'ℒ'),
    ("mscrM", 'ℳ'),
    ("mscrN", '𝒩'),
    ("mscrO", '𝒪'),
    ("mscrP", '𝒫'),
    ("mscrQ", '𝒬'),
    ("mscrR", 'ℛ'),
    ("mscrS", '𝒮'),
    ("mscrT", '𝒯'),
    ("mscrU", '𝒰'),
    ("mscrV", '𝒱'),
    ("mscrW", '𝒲'),
    ("mscrX", '𝒳'),
    ("mscrY", '𝒴'),
    ("mscrZ", '𝒵'),
    ("mscra", '𝒶'),
    ("mscrb", '𝒷'),
    ("mscrc", '𝒸'),
    ("mscrd", '𝒹'),
    ("mscre", 'ℯ'),
    ("mscrf", '𝒻'),
    ("mscrg", 'ℊ'),
    ("mscrh", '𝒽'),
    ("mscri", '𝒾'),
    ("mscrj", '𝒿'),
    ("mscrk", '𝓀'),
    ("mscrl", '𝓁'),
    ("mscrm", '𝓂'),
    ("mscrn", '𝓃'),
    ("mscro", 'ℴ'),
    ("mscrp", '𝓅'),
    ("mscrq", '𝓆'),
    ("mscrr", '𝓇'),
    ("mscrs", '𝓈'),
    ("mscrt", '𝓉'),
    ("mscru", '𝓊'),
    ("mscrv", '𝓋'),
    ("mscrw", '𝓌'),
    ("mscrx", '𝓍'),
    ("mscry", '𝓎'),
    ("mscrz", '𝓏'),
    ("mttA", '𝙰'),
    ("mttB", '𝙱'),
    ("mttC", '𝙲'),
    ("mttD", '𝙳'),
    ("mttE", '𝙴'),
    ("mttF", '𝙵'),
    ("mttG", '𝙶'),
    ("mttH", '𝙷'),
    ("mttI", '𝙸'),
    ("mttJ", '𝙹'),
    ("mttK", '𝙺'),
    ("mttL", '𝙻'),
    ("mttM", '𝙼'),
    ("mttN", '𝙽'),
    ("mttO", '𝙾'),
    ("mttP", '𝙿'),
    ("mttQ", '𝚀'),
    ("mttR", '𝚁'),
    ("mttS", '𝚂'),
    ("mttT", '𝚃'),
    ("mttU", '𝚄'),
    ("mttV", '𝚅'),
    ("mttW", '𝚆'),
    ("mttX", '𝚇'),
    ("mttY", '𝚈'),
    ("mttZ", '𝚉'),
    ("mtta", '𝚊'),
    ("mttb", '𝚋'),
    ("mttc", '𝚌'),
    ("mttd", '𝚍'),
    ("mtte", '𝚎'),
    ("mtteight", '𝟾'),
    ("mttf", '𝚏'),
    ("mttfive", '𝟻'),
    ("mttfour", '𝟺'),
    ("mttg", '𝚐'),
    ("mtth", '𝚑'),
    ("mtti", '𝚒'),
    ("mttj", '𝚓'),
    ("mttk", '𝚔'),
    ("mttl", '𝚕'),
    ("mttm", '𝚖'),
    ("mttn", '𝚗'),
    ("mttnine", '𝟿'),
    ("mtto", '𝚘'),
    ("mttone", '𝟷'),
    ("mttp", '𝚙'),
    ("mttq", '𝚚'),
    ("mttr", '𝚛'),
    ("mtts", '𝚜'),
    ("mttseven", '𝟽'),
    ("mttsix", '𝟼'),
    ("mttt", '𝚝'),
    ("mttthree", '𝟹'),
    ("mtttwo", '𝟸'),
    ("mttu", '𝚞'),
    ("mttv", '𝚟'),
    ("mttw", '𝚠'),
    ("mttx", '𝚡'),
    ("mtty", '𝚢'),
    ("mttz", '𝚣'),
    ("mttzero", '𝟶'),
    ("multimap", '⊸'),
    ("multimapinv", '⟜'),
    ("mupAlpha", 'Α'),
    ("mupBeta", 'Β'),
    ("mupChi", 'Χ'),
    ("mupDelta", 'Δ'),
    ("mupEpsilon", 'Ε'),
    ("mupEta", 'Η'),
    ("mupGamma", 'Γ'),
    ("mupIota", 'Ι'),
    ("mupKappa", 'Κ'),
    ("mupLambda", 'Λ'),
    ("mupMu", 'Μ'),
    ("mupNu", 'Ν'),
    ("mupOmega", 'Ω'),
    ("mupOmicron", 'Ο'),
    ("mupPhi", 'Φ'),
    ("mupPi", 'Π'),
    ("mupPsi", 'Ψ'),
    ("mupRho", 'Ρ'),
    ("mupSigma", 'Σ'),
    ("mupTau", 'Τ'),
    ("mupTheta", 'Θ'),
    ("mupUpsilon", 'Υ'),
    ("mupXi", 'Ξ'),
    ("mupZeta", 'Ζ'),
    ("mupalpha", 'α'),
    ("mupbeta", 'β'),
    ("mupchi", 'χ'),
    ("mupdelta", 'δ'),
    ("mupepsilon", 'ϵ'),
    ("mupeta", 'η'),
    ("mupgamma", 'γ'),
    ("mupiota", 'ι'),
    ("mupkappa", 'κ'),
    ("muplambda", 'λ'),
    ("mupmu", 'μ'),
    ("mupnu", 'ν'),
    ("mupomega", 'ω'),
    ("mupomicron", 'ο'),
    ("mupphi", 'ϕ'),
    ("muppi", 'π'),
    ("muppsi", 'ψ'),
    ("muprho", 'ρ'),
    ("mupsigma", 'σ'),
    ("muptau", 'τ'),
    ("muptheta", 'θ'),
    ("mupupsilon", 'υ'),
    ("mupvarTheta", 'ϴ'),
    ("mupvarepsilon", 'ε'),
    ("mupvarkappa", 'ϰ'),
    ("mupvarphi", 'φ'),
    ("mupvarpi", 'ϖ'),
    ("mupvarrho", 'ϱ'),
    ("mupvarsigma", 'ς'),
    ("mupvartheta", 'ϑ'),
    ("mupxi", 'ξ'),
    ("mupzeta", 'ζ'),
    ("nHdownarrow", '⇟'),
    ("nHuparrow", '⇞'),
    ("nLeftarrow", '⇍'),
    ("nLeftrightarrow", '⇎'),
    ("nRightarrow", '⇏'),
    ("nVDash", '⊯'),
    ("nVdash", '⊮'),
    ("nVleftarrow", '⇺'),
    ("nVleftarrowtail", '⬺'),
    ("nVleftrightarrow", '⇼'),
    ("nVrightarrow", '⇻'),
    ("nVrightarrowtail", '⤕'),
    ("nVtwoheadleftarrow", '⬵'),
    ("nVtwoheadleftarrowtail", '⬽'),
    ("nVtwoheadrightarrow", '⤁'),
    ("nVtwoheadrightarrowtail", '⤘'),
    ("nabla", '∇'),
    ("napprox", '≉'),
    ("nasymp", '≭'),
    ("natural", '♮'),
    ("ncong", '≇'),
    ("ne", '≠'),
    ("nearrow", '↗'),
    ("neg", '¬'),
    ("neovnwarrow", '⤱'),
    ("neovsearrow", '⤮'),
    ("nequiv", '≢'),
    ("neswarrow", '⤢'),
    ("neuter", '⚲'),
    ("nexists", '∄'),
    ("ngeq", '≱'),
    ("ngtr", '≯'),
    ("ngtrless", '≹'),
    ("ngtrsim", '≵'),
    ("nhVvert", '⫵'),
    ("nhpar", '⫲'),
    ("ni", '∋'),
    ("niobar", '⋾'),
    ("nis", '⋼'),
    ("nisd", '⋺'),
    ("nleftarrow", '↚'),
    ("nleftrightarrow", '↮'),
    ("nleq", '≰'),
    ("nless", '≮'),
    ("nlessgtr", '≸'),
    ("nlesssim", '≴'),
    ("nmid", '∤'),
    ("nni", '∌'),
    ("notaccent", '\u{338}'),
    ("notin", '∉'),
    ("nparallel", '∦'),
    ("npolint", '⨔'),
    ("nprec", '⊀'),
    ("npreccurlyeq", '⋠'),
    ("nrightarrow", '↛'),
    ("nsim", '≁'),
    ("nsime", '≄'),
    ("nsimeq", '≄'),
    ("nsqsubseteq", '⋢'),
    ("nsqsupseteq", '⋣'),
    ("nsubset", '⊄'),
    ("nsubseteq", '⊈'),
    ("nsucc", '⊁'),
    ("nsucccurlyeq", '⋡'),
    ("nsupset", '⊅'),
    ("nsupseteq", '⊉'),
    ("ntrianglelefteq", '⋬'),
    ("ntrianglerighteq", '⋭'),
    ("nvDash", '⊭'),
    ("nvLeftarrow", '⤂'),
    ("nvLeftrightarrow", '⤄'),
    ("nvRightarrow", '⤃'),
    ("nvartriangleleft", '⋪'),
    ("nvartriangleright", '⋫'),
    ("nvdash", '⊬'),
    ("nvinfty", '⧞'),
    ("nvleftarrow", '⇷'),
    ("nvleftarrowtail", '⬹'),
    ("nvleftrightarrow", '⇹'),
    ("nvrightarrow", '⇸'),
    ("nvrightarrowtail", '⤔'),
    ("nvtwoheadleftarrow", '⬴'),
    ("nvtwoheadleftarrowtail", '⬼'),
    ("nvtwoheadrightarrow", '⤀'),
    ("nvtwoheadrightarrowtail", '⤗'),
    ("nwarrow", '↖'),
    ("nwovnearrow", '⤲'),
    ("nwsearrow", '⤡'),
    ("obar", '⌽'),
    ("obot", '⦺'),
    ("obrbrak", '⏠'),
    ("obslash", '⦸'),
    ("ocirc", '\u{30a}'),
    ("ocommatopright", '\u{315}'),
    ("odiv", '⨸'),
    ("odot", '⊙'),
    ("odotslashdot", '⦼'),
    ("ogreaterthan", '⧁'),
    ("oiiint", '∰'),
    ("oiint", '∯'),
    ("oint", '∮'),
    ("ointctrclockwise", '∳'),
    ("olcross", '⦻'),
    ("olessthan", '⧀'),
    ("ominus", '⊖'),
    ("operp", '⦹'),
    ("oplus", '⊕'),
    ("opluslhrim", '⨭'),
    ("oplusrhrim", '⨮'),
    ("origof", '⊶'),
    ("oslash", '⊘'),
    ("otimes", '⊗'),
    ("otimeshat", '⨶'),
    ("otimeslhrim", '⨴'),
    ("otimesrhrim", '⨵'),
    ("oturnedcomma", '\u{312}'),
    ("overbar", '\u{305}'),
    ("overbrace", '⏞'),
    ("overbracket", '⎴'),
    ("overleftarrow", '\u{20d6}'),
    ("overleftharpoon", '\u{20d0}'),
    ("overleftrightarrow", '\u{20e1}'),
    ("overparen", '⏜'),
    ("overrightarrow", '\u{20d7}'),
    ("overrightharpoon", '\u{20d1}'),
    ("ovhook", '\u{309}'),
    ("parallel", '∥'),
    ("parallelogram", '▱'),
    ("parallelogramblack", '▰'),
    ("parsim", '⫳'),
    ("partial", '∂'),
    ("partialmeetcontraction", '⪣'),
    ("pentagon", '⬠'),
    ("pentagonblack", '⬟'),
    ("perp", '⟂'),
    ("perps", '⫡'),
    ("pitchfork", '⋔'),
    ("plusdot", '⨥'),
    ("pluseqq", '⩲'),
    ("plushat", '⨣'),
    ("plussim", '⨦'),
    ("plussubtwo", '⨧'),
    ("plustrif", '⨨'),
    ("pm", '±'),
    ("pointint", '⨕'),
    ("postalmark", '〒'),
    ("prec", '≺'),
    ("precapprox", '⪷'),
    ("preccurlyeq", '≼'),
    ("preceq", '⪯'),
    ("preceqq", '⪳'),
    ("precnapprox", '⪹'),
    ("precneq", '⪱'),
    ("precneqq", '⪵'),
    ("precnsim", '⋨'),
    ("precsim", '≾'),
    ("prime", '′'),
    ("prod", '∏'),
    ("profline", '⌒'),
    ("profsurf", '⌓'),
    ("propto", '∝'),
    ("prurel", '⊰'),
    ("pullback", '⟓'),
    ("pushout", '⟔'),
    ("qprime", '⁗'),
    ("quarternote", '♩'),
    ("questeq", '≟'),
    ("rAngle", '⟫'),
    ("rBrace", '⦄'),
    ("rBrack", '⟧'),
    ("rParen", '⦆'),
    ("rangle", '⟩'),
    ("rangledot", '⦒'),
    ("rangledownzigzagarrow", '⍼'),
    ("rbag", '⟆'),
    ("rblkbrbrak", '⦘'),
    ("rbrace", '}'),
    ("rbracelend", '⎭'),
    ("rbracemid", '⎬'),
    ("rbraceuend", '⎫'),
    ("rbrack", ']'),
    ("rbrackextender", '⎥'),
    ("rbracklend", '⎦'),
    ("rbracklrtick", '⦎'),
    ("rbrackubar", '⦌'),
    ("rbrackuend", '⎤'),
    ("rbrackurtick", '⦐'),
    ("rbrbrak", '❳'),
    ("rceil", '⌉'),
    ("rcurvyangle", '⧽'),
    ("rdiagovfdiag", '⤫'),
    ("rdiagovsearrow", '⤰'),
    ("revangle", '⦣'),
    ("revangleubar", '⦥'),
    ("revemptyset", '⦰'),
    ("revnmid", '⫮'),
    ("rfbowtie", '⧒'),
    ("rfloor", '⌋'),
    ("rftimes", '⧕'),
    ("rgroup", '⟯'),
    ("rightangle", '∟'),
    ("rightanglemdot", '⦝'),
    ("rightanglesqr", '⦜'),
    ("rightarrow", '→'),
    ("rightarrowapprox", '⥵'),
    ("rightarrowbackapprox", '⭈'),
    ("rightarrowbar", '⇥'),
    ("rightarrowbsimilar", '⭌'),
    ("rightarrowdiamond", '⤞'),
    ("rightarrowgtr", '⭃'),
    ("rightarrowonoplus", '⟴'),
    ("rightarrowplus", '⥅'),
    ("rightarrowshortleftarrow", '⥂'),
    ("rightarrowsimilar", '⥴'),
    ("rightarrowsupset", '⭄'),
    ("rightarrowtail", '↣'),
    ("rightarrowtriangle", '⇾'),
    ("rightarrowx", '⥇'),
    ("rightbkarrow", '⤍'),
    ("rightcurvedarrow", '⤳'),
    ("rightdasharrow", '⇢'),
    ("rightdbltail", '⤜'),
    ("rightdotarrow", '⤑'),
    ("rightdowncurvedarrow", '⤷'),
    ("rightfishtail", '⥽'),
    ("rightharpoonaccent", '\u{20d1}'),
    ("rightharpoondown", '⇁'),
    ("rightharpoondownbar", '⥗'),
    ("rightharpoonsupdown", '⥤'),
    ("rightharpoonup", '⇀'),
    ("rightharpoonupbar", '⥓'),
    ("rightharpoonupdash", '⥬'),
    ("rightimply", '⥰'),
    ("rightleftarrows", '⇄'),
    ("rightleftharpoons", '⇌'),
    ("rightleftharpoonsdown", '⥩'),
    ("rightleftharpoonsup", '⥨'),
    ("rightmoon", '☽'),
    ("rightouterjoin", '⟖'),
    ("rightpentagon", '⭔'),
    ("rightpentagonblack", '⭓'),
    ("rightrightarrows", '⇉'),
    ("rightsquigarrow", '⇝'),
    ("righttail", '⤚'),
    ("rightthreearrows", '⇶'),
    ("rightthreetimes", '⋌'),
    ("rightwavearrow", '↝'),
    ("rightwhitearrow", '⇨'),
    ("ringplus", '⨢'),
    ("risingdotseq", '≓'),
    ("rmoustache", '⎱'),
    ("rparen", ')'),
    ("rparenextender", '⎟'),
    ("rparengtr", '⦔'),
    ("rparenlend", '⎠'),
    ("rparenuend", '⎞'),
    ("rppolint", '⨒'),
    ("rrangle", '⦊'),
    ("rrparenthesis", '⦈'),
    ("rsolbar", '⧷'),
    ("rsqhook", '⫎'),
    ("rsub", '⩥'),
    ("rtimes", '⋊'),
    ("rtriltri", '⧎'),
    ("ruledelayed", '⧴'),
    ("rvboxline", '⎹'),
    ("rvzigzag", '⧙'),
    ("sansLmirrored", '⅃'),
    ("sansLturned", '⅂'),
    ("scpolint", '⨓'),
    ("scurel", '⊱'),
    ("searrow", '↘'),
    ("seovnearrow", '⤭'),
    ("setminus", '⧵'),
    ("sharp", '♯'),
    ("shortdowntack", '⫟'),
    ("shortlefttack", '⫞'),
    ("shortrightarrowleftarrow", '⥄'),
    ("shortuptack", '⫠'),
    ("shuffle", '⧢'),
    ("sim", '∼'),
    ("sime", '≃'),
    ("simeq", '≃'),
    ("simgE", '⪠'),
    ("simgtr", '⪞'),
    ("similarleftarrow", '⭉'),
    ("similarrightarrow", '⥲'),
    ("simlE", '⪟'),
    ("simless", '⪝'),
    ("simminussim", '⩬'),
    ("simneqq", '≆'),
    ("simplus", '⨤'),
    ("simrdots", '⩫'),
    ("sinewave", '∿'),
    ("smallblacktriangleleft", '◂'),
    ("smallblacktriangleright", '▸'),
    ("smallin", '∊'),
    ("smallni", '∍'),
    ("smallsetminus", '∖'),
    ("smalltriangleleft", '◃'),
    ("smalltriangleright", '▹'),
    ("smashtimes", '⨳'),
    ("smblkcircle", '•'),
    ("smblkdiamond", '⬩'),
    ("smblklozenge", '⬪'),
    ("smblksquare", '▪'),
    ("smeparsl", '⧤'),
    ("smile", '⌣'),
    ("smt", '⪪'),
    ("smte", '⪬'),
    ("smwhitestar", '⭒'),
    ("smwhtcircle", '◦'),
    ("smwhtdiamond", '⋄'),
    ("smwhtlozenge", '⬫'),
    ("smwhtsquare", '▫'),
    ("spadesuit", '♠'),
    ("sphericalangle", '∢'),
    ("sphericalangleup", '⦡'),
    ("sqcap", '⊓'),
    ("sqcup", '⊔'),
    ("sqint", '⨖'),
    ("sqlozenge", '⌑'),
    ("sqrt", '√'),
    ("sqrtbottom", '⎷'),
    ("sqsubset", '⊏'),
    ("sqsubseteq", '⊑'),
    ("sqsubsetneq", '⋤'),
    ("sqsupset", '⊐'),
    ("sqsupseteq", '⊒'),
    ("sqsupsetneq", '⋥'),
    ("squarebotblack", '⬓'),
    ("squarecrossfill", '▩'),
    ("squarehfill", '▤'),
    ("squarehvfill", '▦'),
    ("squareleftblack", '◧'),
    ("squarellblack", '⬕'),
    ("squarellquad", '◱'),
    ("squarelrblack", '◪'),
    ("squarelrquad", '◲'),
    ("squareneswfill", '▨'),
    ("squarenwsefill", '▧'),
    ("squarerightblack", '◨'),
    ("squaretopblack", '⬒'),
    ("squareulblack", '◩'),
    ("squareulquad", '◰'),
    ("squareurblack", '⬔'),
    ("squareurquad", '◳'),
    ("squarevfill", '▥'),
    ("squoval", '▢'),
    ("sslash", '⫽'),
    ("star", '⋆'),
    ("stareq", '≛'),
    ("strns", '⏤'),
    ("subedot", '⫃'),
    ("submult", '⫁'),
    ("subrarr", '⥹'),
    ("subset", '⊂'),
    ("subsetapprox", '⫉'),
    ("subsetcirc", '⟃'),
    ("subsetdot", '⪽'),
    ("subseteq", '⊆'),
    ("subseteqq", '⫅'),
    ("subsetneq", '⊊'),
    ("subsetneqq", '⫋'),
    ("subsetplus", '⪿'),
    ("subsim", '⫇'),
    ("subsub", '⫕'),
    ("subsup", '⫓'),
    ("succ", '≻'),
    ("succapprox", '⪸'),
    ("succcurlyeq", '≽'),
    ("succeq", '⪰'),
    ("succeqq", '⪴'),
    ("succnapprox", '⪺'),
    ("succneq", '⪲'),
    ("succneqq", '⪶'),
    ("succnsim", '⋩'),
    ("succsim", '≿'),
    ("sum", '∑'),
    ("sumbottom", '⎳'),
    ("sumint", '⨋'),
    ("sumtop", '⎲'),
    ("sun", '☼'),
    ("supdsub", '⫘'),
    ("supedot", '⫄'),
    ("suphsol", '⟉'),
    ("suphsub", '⫗'),
    ("suplarr", '⥻'),
    ("supmult", '⫂'),
    ("supset", '⊃'),
    ("supsetapprox", '⫊'),
    ("supsetcirc", '⟄'),
    ("supsetdot", '⪾'),
    ("supseteq", '⊇'),
    ("supseteqq", '⫆'),
    ("supsetneq", '⊋'),
    ("supsetneqq", '⫌'),
    ("supsetplus", '⫀'),
    ("supsim", '⫈'),
    ("supsub", '⫔'),
    ("supsup", '⫖'),
    ("surd", '√'),
    ("swarrow", '↙'),
    ("talloblong", '⫾'),
    ("therefore", '∴'),
    ("thermod", '⧧'),
    ("threedangle", '⟀'),
    ("threedotcolon", '⫶'),
    ("threeunderdot", '\u{20e8}'),
    ("tieconcat", '⁀'),
    ("tieinfty", '⧝'),
    ("tilde", '\u{303}'),
    ("times", '×'),
    ("timesbar", '⨱'),
    ("tminus", '⧿'),
    ("toea", '⤨'),
    ("tona", '⤧'),
    ("top", '⊤'),
    ("topbot", '⌶'),
    ("topcir", '⫱'),
    ("topfork", '⫚'),
    ("topsemicircle", '◠'),
    ("tosa", '⤩'),
    ("towa", '⤪'),
    ("tplus", '⧾'),
    ("trapezium", '⏢'),
    ("trianglecdot", '◬'),
    ("triangledown", '▿'),
    ("triangleleft", '◁'),
    ("triangleleftblack", '◭'),
    ("trianglelefteq", '⊴'),
    ("triangleminus", '⨺'),
    ("triangleodot", '⧊'),
    ("triangleplus", '⨹'),
    ("triangleq", '≜'),
    ("triangleright", '▷'),
    ("trianglerightblack", '◮'),
    ("trianglerighteq", '⊵'),
    ("triangles", '⧌'),
    ("triangleserifs", '⧍'),
    ("triangletimes", '⨻'),
    ("triangleubar", '⧋'),
    ("tripleplus", '⧻'),
    ("trprime", '‴'),
    ("trslash", '⫻'),
    ("turnangle", '⦢'),
    ("turnediota", '℩'),
    ("turnednot", '⌙'),
    ("twocaps", '⩋'),
    ("twocups", '⩊'),
    ("twoheaddownarrow", '↡'),
    ("twoheadleftarrow", '↞'),
    ("twoheadleftarrowtail", '⬻'),
    ("twoheadleftdbkarrow", '⬷'),
    ("twoheadmapsfrom", '⬶'),
    ("twoheadmapsto", '⤅'),
    ("twoheadrightarrow", '↠'),
    ("twoheadrightarrowtail", '⤖'),
    ("twoheaduparrow", '↟'),
    ("twoheaduparrowcircle", '⥉'),
    ("twolowline", '‗'),
    ("twonotes", '♫'),
    ("typecolon", '⦂'),
    ("ubrbrak", '⏡'),
    ("ularc", '◜'),
    ("ulblacktriangle", '◤'),
    ("ulcorner", '⌜'),
    ("ultriangle", '◸'),
    ("uminus", '⩁'),
    ("underbrace", '⏟'),
    ("underbracket", '⎵'),
    ("underleftarrow", '\u{20ee}'),
    ("underleftharpoondown", '\u{20ed}'),
    ("underleftrightarrow", '\u{34d}'),
    ("underparen", '⏝'),
    ("underrightarrow", '\u{20ef}'),
    ("underrightharpoondown", '\u{20ec}'),
    ("unicodecdots", '⋯'),
    ("unicodeellipsis", '…'),
    ("upDigamma", 'Ϝ'),
    ("upand", '⅋'),
    ("uparrow", '↑'),
    ("uparrowbarred", '⤉'),
    ("uparrowoncircle", '⦽'),
    ("upbackepsilon", '϶'),
    ("updasharrow", '⇡'),
    ("updigamma", 'ϝ'),
    ("updownarrow", '↕'),
    ("updownarrowbar", '↨'),
    ("updownarrows", '⇅'),
    ("updownharpoonleftleft", '⥑'),
    ("updownharpoonleftright", '⥍'),
    ("updownharpoonrightleft", '⥌'),
    ("updownharpoonrightright", '⥏'),
    ("updownharpoonsleftright", '⥮'),
    ("upfishtail", '⥾'),
    ("upharpoonleft", '↿'),
    ("upharpoonleftbar", '⥠'),
    ("upharpoonright", '↾'),
    ("upharpoonrightbar", '⥜'),
    ("upharpoonsleftright", '⥣'),
    ("upin", '⟒'),
    ("upint", '⨛'),
    ("uplus", '⊎'),
    ("uprightcurvearrow", '⤴'),
    ("upuparrows", '⇈'),
    ("upwhitearrow", '⇧'),
    ("urarc", '◝'),
    ("urblacktriangle", '◥'),
    ("urcorner", '⌝'),
    ("urtriangle", '◹'),
    ("vBar", '⫨'),
    ("vBarv", '⫩'),
    ("vDash", '⊨'),
    ("vDdash", '⫢'),
    ("varVdash", '⫦'),
    ("varbarwedge", '⌅'),
    ("varcarriagereturn", '⏎'),
    ("varclubsuit", '♧'),
    ("vardiamondsuit", '♦'),
    ("vardoublebarwedge", '⌆'),
    ("varheartsuit", '♥'),
    ("varhexagon", '⬡'),
    ("varhexagonblack", '⬢'),
    ("varhexagonlrbonds", '⌬'),
    ("varisinobar", '⋶'),
    ("varisins", '⋳'),
    ("varlrtriangle", '⊿'),
    ("varniobar", '⋽'),
    ("varnis", '⋻'),
    ("varnothing", '∅'),
    ("varointclockwise", '∲'),
    ("varspadesuit", '♤'),
    ("varstar", '✶'),
    ("vartriangle", '▵'),
    ("vartriangleleft", '⊲'),
    ("vartriangleright", '⊳'),
    ("varveebar", '⩡'),
    ("vbraceextender", '⎪'),
    ("vbrtri", '⧐'),
    ("vdash", '⊢'),
    ("vdots", '⋮'),
    ("vec", '\u{20d7}'),
    ("vectimes", '⨯'),
    ("vee", '∨'),
    ("veebar", '⊻'),
    ("veedot", '⟇'),
    ("veedoublebar", '⩣'),
    ("veeeq", '≚'),
    ("veemidvert", '⩛'),
    ("veeodot", '⩒'),
    ("veeonvee", '⩖'),
    ("veeonwedge", '⩙'),
    ("vert", '|'),
    ("vertoverlay", '\u{20d2}'),
    ("viewdata", '⌗'),
    ("vlongdash", '⟝'),
    ("vrectangle", '▯'),
    ("vrectangleblack", '▮'),
    ("vysmblkcircle", '∙'),
    ("vysmblksquare", '⬝'),
    ("vysmwhtcircle", '∘'),
    ("vysmwhtsquare", '⬞'),
    ("vzigzag", '⦚'),
    ("wedge", '∧'),
    ("wedgebar", '⩟'),
    ("wedgedot", '⟑'),
    ("wedgedoublebar", '⩠'),
    ("wedgemidvert", '⩚'),
    ("wedgeodot", '⩑'),
    ("wedgeonwedge", '⩕'),
    ("wedgeq", '≙'),
    ("whitearrowupfrombar", '⇪'),
    ("whiteinwhitetriangle", '⟁'),
    ("whitepointerleft", '◅'),
    ("whitepointerright", '▻'),
    ("whitesquaretickleft", '⟤'),
    ("whitesquaretickright", '⟥'),
    ("whthorzoval", '⬭'),
    ("whtvertoval", '⬯'),
    ("wideangledown", '⦦'),
    ("wideangleup", '⦧'),
    ("widebreve", '\u{306}'),
    ("widebridgeabove", '\u{20e9}'),
    ("widecheck", '\u{30c}'),
    ("widehat", '\u{302}'),
    ("wideoverbar", '\u{305}'),
    ("widetilde", '\u{303}'),
    ("wideutilde", '\u{330}'),
    ("wp", '℘'),
    ("wr", '≀'),
    ("xbsol", '⧹'),
    ("xsol", '⧸'),
    ("zcmp", '⨟'),
    ("zpipe", '⨠'),
    ("zproject", '⨡'),
];
