use super::CharClassification;

pub const CHAR_CLASSIFICATION: [(u32, CharClassification); 1692] = [
    (0, CharClassification::Ignore),
    (' ' as u32, CharClassification::Space),
    ('!' as u32, CharClassification::Normal),
    ('!' as u32 + 1, CharClassification::Ignore),
    ('#' as u32, CharClassification::Normal),
    ('$' as u32, CharClassification::Normal),
    ('%' as u32, CharClassification::Normal),
    ('&' as u32, CharClassification::Normal),
    ('&' as u32 + 1, CharClassification::Ignore),
    ('(' as u32, CharClassification::Opening),
    (')' as u32, CharClassification::Closing),
    ('*' as u32, CharClassification::Normal),
    ('+' as u32, CharClassification::Vary),
    (',' as u32, CharClassification::Punct),
    ('-' as u32, CharClassification::Normal),
    ('.' as u32, CharClassification::Punct),
    ('/' as u32, CharClassification::Binary),
    ('0' as u32, CharClassification::Normal),
    (':' as u32, CharClassification::Punct),
    (';' as u32, CharClassification::Punct),
    ('<' as u32, CharClassification::Relation),
    ('=' as u32, CharClassification::Relation),
    ('>' as u32, CharClassification::Relation),
    ('?' as u32, CharClassification::Punct),
    ('@' as u32, CharClassification::Normal),
    ('A' as u32, CharClassification::Alphabetic),
    ('[' as u32, CharClassification::Opening),
    ('\\' as u32, CharClassification::Binary),
    (']' as u32, CharClassification::Closing),
    ('^' as u32, CharClassification::Normal),
    ('_' as u32, CharClassification::Normal),
    ('`' as u32, CharClassification::Diacritic),
    ('a' as u32, CharClassification::Alphabetic),
    ('{' as u32, CharClassification::Opening),
    ('|' as u32, CharClassification::Fence),
    ('}' as u32, CharClassification::Closing),
    ('~' as u32, CharClassification::Normal),
    ('~' as u32 + 1, CharClassification::Ignore),
    ('\u{a0}' as u32, CharClassification::Space),
    ('¡' as u32, CharClassification::Punct),
    ('¢' as u32, CharClassification::Normal),
    ('£' as u32, CharClassification::Normal),
    ('¤' as u32, CharClassification::Normal),
    ('¥' as u32, CharClassification::Normal),
    ('¦' as u32, CharClassification::Normal),
    ('§' as u32, CharClassification::Normal),
    ('¨' as u32, CharClassification::Diacritic),
    ('¨' as u32 + 1, CharClassification::Ignore),
    ('¬' as u32, CharClassification::Unary),
    ('¬' as u32 + 1, CharClassification::Ignore),
    ('¯' as u32, CharClassification::Diacritic),
    ('°' as u32, CharClassification::Normal),
    ('±' as u32, CharClassification::Vary),
    ('²' as u32, CharClassification::Normal),
    ('³' as u32, CharClassification::Normal),
    ('´' as u32, CharClassification::Normal),
    ('µ' as u32, CharClassification::Normal),
    ('¶' as u32, CharClassification::Normal),
    ('·' as u32, CharClassification::Binary),
    ('·' as u32 + 1, CharClassification::Ignore),
    ('¹' as u32, CharClassification::Normal),
    ('¹' as u32 + 1, CharClassification::Ignore),
    ('¼' as u32, CharClassification::Normal),
    ('½' as u32, CharClassification::Normal),
    ('¾' as u32, CharClassification::Normal),
    ('¿' as u32, CharClassification::Punct),
    ('¿' as u32 + 1, CharClassification::Ignore),
    ('×' as u32, CharClassification::Binary),
    ('×' as u32 + 1, CharClassification::Ignore),
    ('÷' as u32, CharClassification::Binary),
    ('÷' as u32 + 1, CharClassification::Ignore),
    ('ı' as u32, CharClassification::Alphabetic),
    ('ı' as u32 + 1, CharClassification::Ignore),
    ('ȷ' as u32, CharClassification::Alphabetic),
    ('ȷ' as u32 + 1, CharClassification::Ignore),
    ('ˆ' as u32, CharClassification::Diacritic),
    ('ˇ' as u32, CharClassification::Diacritic),
    ('ˇ' as u32 + 1, CharClassification::Ignore),
    ('˘' as u32, CharClassification::Diacritic),
    ('˙' as u32, CharClassification::Diacritic),
    ('˚' as u32, CharClassification::Diacritic),
    ('˚' as u32 + 1, CharClassification::Ignore),
    ('˜' as u32, CharClassification::Diacritic),
    ('˜' as u32 + 1, CharClassification::Ignore),
    ('\u{300}' as u32, CharClassification::Diacritic),
    ('\u{301}' as u32, CharClassification::Diacritic),
    ('\u{302}' as u32, CharClassification::Diacritic),
    ('\u{303}' as u32, CharClassification::Diacritic),
    ('\u{304}' as u32, CharClassification::Diacritic),
    ('\u{305}' as u32, CharClassification::Diacritic),
    ('\u{306}' as u32, CharClassification::Diacritic),
    ('\u{307}' as u32, CharClassification::Diacritic),
    ('\u{308}' as u32, CharClassification::Diacritic),
    ('\u{308}' as u32 + 1, CharClassification::Ignore),
    ('\u{30a}' as u32, CharClassification::Diacritic),
    ('\u{30a}' as u32 + 1, CharClassification::Ignore),
    ('\u{30c}' as u32, CharClassification::Diacritic),
    ('\u{30c}' as u32 + 1, CharClassification::Ignore),
    ('\u{311}' as u32, CharClassification::Diacritic),
    ('\u{311}' as u32 + 1, CharClassification::Ignore),
    ('\u{323}' as u32, CharClassification::Diacritic),
    ('\u{323}' as u32 + 1, CharClassification::Ignore),
    ('\u{32c}' as u32, CharClassification::Diacritic),
    ('\u{32d}' as u32, CharClassification::Diacritic),
    ('\u{32e}' as u32, CharClassification::Diacritic),
    ('\u{32f}' as u32, CharClassification::Diacritic),
    ('\u{330}' as u32, CharClassification::Diacritic),
    ('\u{331}' as u32, CharClassification::Diacritic),
    ('\u{332}' as u32, CharClassification::Diacritic),
    ('\u{333}' as u32, CharClassification::Diacritic),
    ('\u{333}' as u32 + 1, CharClassification::Ignore),
    ('\u{338}' as u32, CharClassification::Diacritic),
    ('\u{338}' as u32 + 1, CharClassification::Ignore),
    ('\u{33a}' as u32, CharClassification::Diacritic),
    ('\u{33a}' as u32 + 1, CharClassification::Ignore),
    ('\u{33f}' as u32, CharClassification::Diacritic),
    ('\u{33f}' as u32 + 1, CharClassification::Ignore),
    ('\u{346}' as u32, CharClassification::Diacritic),
    ('\u{346}' as u32 + 1, CharClassification::Ignore),
    ('Α' as u32, CharClassification::Alphabetic),
    ('Β' as u32, CharClassification::Alphabetic),
    ('Γ' as u32, CharClassification::Alphabetic),
    ('Δ' as u32, CharClassification::Alphabetic),
    ('Ε' as u32, CharClassification::Alphabetic),
    ('Ζ' as u32, CharClassification::Alphabetic),
    ('Η' as u32, CharClassification::Alphabetic),
    ('Θ' as u32, CharClassification::Alphabetic),
    ('Ι' as u32, CharClassification::Alphabetic),
    ('Κ' as u32, CharClassification::Alphabetic),
    ('Λ' as u32, CharClassification::Alphabetic),
    ('Μ' as u32, CharClassification::Alphabetic),
    ('Ν' as u32, CharClassification::Alphabetic),
    ('Ξ' as u32, CharClassification::Alphabetic),
    ('Ο' as u32, CharClassification::Alphabetic),
    ('Π' as u32, CharClassification::Alphabetic),
    ('Ρ' as u32, CharClassification::Alphabetic),
    ('Ρ' as u32 + 1, CharClassification::Ignore),
    ('Σ' as u32, CharClassification::Alphabetic),
    ('Τ' as u32, CharClassification::Alphabetic),
    ('Τ' as u32 + 1, CharClassification::Ignore),
    ('Φ' as u32, CharClassification::Alphabetic),
    ('Χ' as u32, CharClassification::Alphabetic),
    ('Ψ' as u32, CharClassification::Alphabetic),
    ('Ω' as u32, CharClassification::Alphabetic),
    ('Ω' as u32 + 1, CharClassification::Ignore),
    ('α' as u32, CharClassification::Alphabetic),
    ('β' as u32, CharClassification::Alphabetic),
    ('γ' as u32, CharClassification::Alphabetic),
    ('δ' as u32, CharClassification::Alphabetic),
    ('ε' as u32, CharClassification::Alphabetic),
    ('ζ' as u32, CharClassification::Alphabetic),
    ('η' as u32, CharClassification::Alphabetic),
    ('θ' as u32, CharClassification::Alphabetic),
    ('ι' as u32, CharClassification::Alphabetic),
    ('κ' as u32, CharClassification::Alphabetic),
    ('λ' as u32, CharClassification::Alphabetic),
    ('μ' as u32, CharClassification::Alphabetic),
    ('ν' as u32, CharClassification::Alphabetic),
    ('ξ' as u32, CharClassification::Alphabetic),
    ('ο' as u32, CharClassification::Alphabetic),
    ('π' as u32, CharClassification::Alphabetic),
    ('ρ' as u32, CharClassification::Alphabetic),
    ('ρ' as u32 + 1, CharClassification::Ignore),
    ('σ' as u32, CharClassification::Alphabetic),
    ('τ' as u32, CharClassification::Alphabetic),
    ('υ' as u32, CharClassification::Alphabetic),
    ('φ' as u32, CharClassification::Alphabetic),
    ('χ' as u32, CharClassification::Alphabetic),
    ('ψ' as u32, CharClassification::Alphabetic),
    ('ω' as u32, CharClassification::Alphabetic),
    ('ω' as u32 + 1, CharClassification::Ignore),
    ('ϐ' as u32, CharClassification::Alphabetic),
    ('ϑ' as u32, CharClassification::Alphabetic),
    ('ϒ' as u32, CharClassification::Alphabetic),
    ('ϒ' as u32 + 1, CharClassification::Ignore),
    ('ϕ' as u32, CharClassification::Alphabetic),
    ('ϖ' as u32, CharClassification::Alphabetic),
    ('ϖ' as u32 + 1, CharClassification::Ignore),
    ('Ϙ' as u32, CharClassification::Normal),
    ('ϙ' as u32, CharClassification::Normal),
    ('Ϛ' as u32, CharClassification::Alphabetic),
    ('ϛ' as u32, CharClassification::Alphabetic),
    ('Ϝ' as u32, CharClassification::Alphabetic),
    ('ϝ' as u32, CharClassification::Alphabetic),
    ('ϝ' as u32 + 1, CharClassification::Ignore),
    ('Ϡ' as u32, CharClassification::Alphabetic),
    ('ϡ' as u32, CharClassification::Alphabetic),
    ('ϡ' as u32 + 1, CharClassification::Ignore),
    ('ϰ' as u32, CharClassification::Alphabetic),
    ('ϱ' as u32, CharClassification::Alphabetic),
    ('ϱ' as u32 + 1, CharClassification::Ignore),
    ('ϴ' as u32, CharClassification::Alphabetic),
    ('ϵ' as u32, CharClassification::Alphabetic),
    ('϶' as u32, CharClassification::Normal),
    ('϶' as u32 + 1, CharClassification::Ignore),
    ('Ш' as u32, CharClassification::Alphabetic),
    ('Ш' as u32 + 1, CharClassification::Ignore),
    ('؆' as u32, CharClassification::Large),
    ('؇' as u32, CharClassification::Large),
    ('؈' as u32, CharClassification::Alphabetic),
    ('؈' as u32 + 1, CharClassification::Ignore),
    ('\u{2000}' as u32, CharClassification::Space),
    ('\u{2001}' as u32, CharClassification::Space),
    ('\u{2002}' as u32, CharClassification::Space),
    ('\u{2003}' as u32, CharClassification::Space),
    ('\u{2004}' as u32, CharClassification::Space),
    ('\u{2005}' as u32, CharClassification::Space),
    ('\u{2006}' as u32, CharClassification::Space),
    ('\u{2007}' as u32, CharClassification::Space),
    ('\u{2007}' as u32 + 1, CharClassification::Ignore),
    ('\u{2009}' as u32, CharClassification::Space),
    ('\u{200a}' as u32, CharClassification::Space),
    ('\u{200b}' as u32, CharClassification::Space),
    ('\u{200b}' as u32 + 1, CharClassification::Ignore),
    ('‐' as u32, CharClassification::Punct),
    ('‐' as u32 + 1, CharClassification::Ignore),
    ('‒' as u32, CharClassification::Punct),
    ('–' as u32, CharClassification::Punct),
    ('—' as u32, CharClassification::Punct),
    ('—' as u32 + 1, CharClassification::Ignore),
    ('‖' as u32, CharClassification::Fence),
    ('‖' as u32 + 1, CharClassification::Ignore),
    ('†' as u32, CharClassification::Relation),
    ('‡' as u32, CharClassification::Relation),
    ('•' as u32, CharClassification::Binary),
    ('•' as u32 + 1, CharClassification::Ignore),
    ('…' as u32, CharClassification::Normal),
    ('…' as u32 + 1, CharClassification::Ignore),
    ('′' as u32, CharClassification::Normal),
    ('″' as u32, CharClassification::Normal),
    ('‴' as u32, CharClassification::Normal),
    ('‵' as u32, CharClassification::Normal),
    ('‶' as u32, CharClassification::Normal),
    ('‷' as u32, CharClassification::Normal),
    ('‷' as u32 + 1, CharClassification::Ignore),
    ('※' as u32, CharClassification::Normal),
    ('‼' as u32, CharClassification::Normal),
    ('‼' as u32 + 1, CharClassification::Ignore),
    ('⁀' as u32, CharClassification::Binary),
    ('⁀' as u32 + 1, CharClassification::Ignore),
    ('⁄' as u32, CharClassification::Binary),
    ('⁄' as u32 + 1, CharClassification::Ignore),
    ('⁎' as u32, CharClassification::Binary),
    ('⁏' as u32, CharClassification::Relation),
    ('⁐' as u32, CharClassification::Relation),
    ('⁑' as u32, CharClassification::Normal),
    ('⁒' as u32, CharClassification::Normal),
    ('⁒' as u32 + 1, CharClassification::Ignore),
    ('⁗' as u32, CharClassification::Normal),
    ('⁗' as u32 + 1, CharClassification::Ignore),
    ('\u{205f}' as u32, CharClassification::Space),
    ('\u{205f}' as u32 + 1, CharClassification::Ignore),
    ('\u{2061}' as u32, CharClassification::Binary),
    ('\u{2062}' as u32, CharClassification::Binary),
    ('\u{2063}' as u32, CharClassification::Punct),
    ('\u{2064}' as u32, CharClassification::Special),
    ('\u{2064}' as u32 + 1, CharClassification::Ignore),
    ('⁺' as u32, CharClassification::Normal),
    ('⁾' as u32 + 1, CharClassification::Ignore),
    ('₊' as u32, CharClassification::Normal),
    ('₎' as u32 + 1, CharClassification::Ignore),
    ('\u{20d0}' as u32, CharClassification::Diacritic),
    ('\u{20d1}' as u32, CharClassification::Diacritic),
    ('\u{20d2}' as u32, CharClassification::Diacritic),
    ('\u{20d3}' as u32, CharClassification::Special),
    ('\u{20d4}' as u32, CharClassification::Diacritic),
    ('\u{20d5}' as u32, CharClassification::Diacritic),
    ('\u{20d6}' as u32, CharClassification::Diacritic),
    ('\u{20d7}' as u32, CharClassification::Diacritic),
    ('\u{20d8}' as u32, CharClassification::Diacritic),
    ('\u{20d9}' as u32, CharClassification::Diacritic),
    ('\u{20da}' as u32, CharClassification::Diacritic),
    ('\u{20db}' as u32, CharClassification::Diacritic),
    ('\u{20dc}' as u32, CharClassification::Diacritic),
    ('\u{20dd}' as u32, CharClassification::Diacritic),
    ('\u{20de}' as u32, CharClassification::Diacritic),
    ('\u{20df}' as u32, CharClassification::Diacritic),
    ('\u{20df}' as u32 + 1, CharClassification::Ignore),
    ('\u{20e1}' as u32, CharClassification::Diacritic),
    ('\u{20e1}' as u32 + 1, CharClassification::Ignore),
    ('\u{20e4}' as u32, CharClassification::Diacritic),
    ('\u{20e5}' as u32, CharClassification::Diacritic),
    ('\u{20e6}' as u32, CharClassification::Diacritic),
    ('\u{20e7}' as u32, CharClassification::Diacritic),
    ('\u{20e8}' as u32, CharClassification::Diacritic),
    ('\u{20e9}' as u32, CharClassification::Diacritic),
    ('\u{20ea}' as u32, CharClassification::Diacritic),
    ('\u{20eb}' as u32, CharClassification::Diacritic),
    ('\u{20ec}' as u32, CharClassification::Diacritic),
    ('\u{20ed}' as u32, CharClassification::Diacritic),
    ('\u{20ee}' as u32, CharClassification::Diacritic),
    ('\u{20ef}' as u32, CharClassification::Diacritic),
    ('\u{20ef}' as u32 + 1, CharClassification::Ignore),
    ('ℂ' as u32, CharClassification::Alphabetic),
    ('ℂ' as u32 + 1, CharClassification::Ignore),
    ('ℇ' as u32, CharClassification::Normal),
    ('ℇ' as u32 + 1, CharClassification::Ignore),
    ('ℊ' as u32, CharClassification::Alphabetic),
    ('ℋ' as u32, CharClassification::Alphabetic),
    ('ℌ' as u32, CharClassification::Alphabetic),
    ('ℍ' as u32, CharClassification::Alphabetic),
    ('ℎ' as u32, CharClassification::Normal),
    ('ℏ' as u32, CharClassification::Normal),
    ('ℐ' as u32, CharClassification::Alphabetic),
    ('ℑ' as u32, CharClassification::Alphabetic),
    ('ℒ' as u32, CharClassification::Alphabetic),
    ('ℓ' as u32, CharClassification::Alphabetic),
    ('ℓ' as u32 + 1, CharClassification::Ignore),
    ('ℕ' as u32, CharClassification::Alphabetic),
    ('ℕ' as u32 + 1, CharClassification::Ignore),
    ('℘' as u32, CharClassification::Alphabetic),
    ('ℙ' as u32, CharClassification::Alphabetic),
    ('ℚ' as u32, CharClassification::Alphabetic),
    ('ℛ' as u32, CharClassification::Alphabetic),
    ('ℜ' as u32, CharClassification::Alphabetic),
    ('ℝ' as u32, CharClassification::Alphabetic),
    ('ℝ' as u32 + 1, CharClassification::Ignore),
    ('ℤ' as u32, CharClassification::Alphabetic),
    ('ℤ' as u32 + 1, CharClassification::Ignore),
    ('Ω' as u32, CharClassification::Normal),
    ('℧' as u32, CharClassification::Normal),
    ('ℨ' as u32, CharClassification::Alphabetic),
    ('℩' as u32, CharClassification::Normal),
    ('℩' as u32 + 1, CharClassification::Ignore),
    ('Å' as u32, CharClassification::Alphabetic),
    ('ℬ' as u32, CharClassification::Alphabetic),
    ('ℭ' as u32, CharClassification::Alphabetic),
    ('ℭ' as u32 + 1, CharClassification::Ignore),
    ('ℯ' as u32, CharClassification::Alphabetic),
    ('ℰ' as u32, CharClassification::Alphabetic),
    ('ℱ' as u32, CharClassification::Alphabetic),
    ('Ⅎ' as u32, CharClassification::Normal),
    ('ℳ' as u32, CharClassification::Alphabetic),
    ('ℴ' as u32, CharClassification::Alphabetic),
    ('ℵ' as u32, CharClassification::Alphabetic),
    ('ℶ' as u32, CharClassification::Alphabetic),
    ('ℷ' as u32, CharClassification::Alphabetic),
    ('ℸ' as u32, CharClassification::Alphabetic),
    ('ℸ' as u32 + 1, CharClassification::Ignore),
    ('ℼ' as u32, CharClassification::Alphabetic),
    ('ℽ' as u32, CharClassification::Alphabetic),
    ('ℾ' as u32, CharClassification::Normal),
    ('ℿ' as u32, CharClassification::Alphabetic),
    ('⅀' as u32, CharClassification::Large),
    ('⅁' as u32, CharClassification::Normal),
    ('⅂' as u32, CharClassification::Normal),
    ('⅃' as u32, CharClassification::Normal),
    ('⅄' as u32, CharClassification::Normal),
    ('ⅅ' as u32, CharClassification::Normal),
    ('ⅆ' as u32, CharClassification::Normal),
    ('ⅇ' as u32, CharClassification::Normal),
    ('ⅈ' as u32, CharClassification::Normal),
    ('ⅉ' as u32, CharClassification::Normal),
    ('ⅉ' as u32 + 1, CharClassification::Ignore),
    ('⅋' as u32, CharClassification::Normal),
    ('⅋' as u32 + 1, CharClassification::Ignore),
    ('←' as u32, CharClassification::Relation),
    ('↳' as u32 + 1, CharClassification::Ignore),
    ('↶' as u32, CharClassification::Relation),
    ('↷' as u32, CharClassification::Relation),
    ('↷' as u32 + 1, CharClassification::Ignore),
    ('↺' as u32, CharClassification::Relation),
    ('∀' as u32, CharClassification::Unary),
    ('∁' as u32, CharClassification::Unary),
    ('∂' as u32, CharClassification::Normal),
    ('∃' as u32, CharClassification::Unary),
    ('∄' as u32, CharClassification::Unary),
    ('∅' as u32, CharClassification::Normal),
    ('∆' as u32, CharClassification::Unary),
    ('∇' as u32, CharClassification::Unary),
    ('∈' as u32, CharClassification::Relation),
    ('∉' as u32, CharClassification::Relation),
    ('∊' as u32, CharClassification::Relation),
    ('∋' as u32, CharClassification::Relation),
    ('∌' as u32, CharClassification::Relation),
    ('∍' as u32, CharClassification::Relation),
    ('∎' as u32, CharClassification::Normal),
    ('∏' as u32, CharClassification::Large),
    ('∐' as u32, CharClassification::Large),
    ('∑' as u32, CharClassification::Large),
    ('−' as u32, CharClassification::Vary),
    ('∓' as u32, CharClassification::Vary),
    ('∔' as u32, CharClassification::Binary),
    ('∕' as u32, CharClassification::Binary),
    ('∖' as u32, CharClassification::Binary),
    ('∗' as u32, CharClassification::Binary),
    ('∘' as u32, CharClassification::Binary),
    ('∙' as u32, CharClassification::Binary),
    ('√' as u32, CharClassification::Large),
    ('∛' as u32, CharClassification::Large),
    ('∜' as u32, CharClassification::Large),
    ('∝' as u32, CharClassification::Relation),
    ('∞' as u32, CharClassification::Normal),
    ('∟' as u32, CharClassification::Normal),
    ('∠' as u32, CharClassification::Normal),
    ('∡' as u32, CharClassification::Normal),
    ('∢' as u32, CharClassification::Normal),
    ('∣' as u32, CharClassification::Relation),
    ('∤' as u32, CharClassification::Relation),
    ('∥' as u32, CharClassification::Relation),
    ('∦' as u32, CharClassification::Relation),
    ('∧' as u32, CharClassification::Binary),
    ('∨' as u32, CharClassification::Binary),
    ('∩' as u32, CharClassification::Binary),
    ('∪' as u32, CharClassification::Binary),
    ('∫' as u32, CharClassification::Large),
    ('∬' as u32, CharClassification::Large),
    ('∭' as u32, CharClassification::Large),
    ('∮' as u32, CharClassification::Large),
    ('∯' as u32, CharClassification::Large),
    ('∰' as u32, CharClassification::Large),
    ('∱' as u32, CharClassification::Large),
    ('∲' as u32, CharClassification::Large),
    ('∳' as u32, CharClassification::Large),
    ('∴' as u32, CharClassification::Relation),
    ('∵' as u32, CharClassification::Relation),
    ('∶' as u32, CharClassification::Relation),
    ('∷' as u32, CharClassification::Relation),
    ('∸' as u32, CharClassification::Binary),
    ('∹' as u32, CharClassification::Relation),
    ('∺' as u32, CharClassification::Relation),
    ('∻' as u32, CharClassification::Relation),
    ('∼' as u32, CharClassification::Relation),
    ('∽' as u32, CharClassification::Relation),
    ('∾' as u32, CharClassification::Binary),
    ('∿' as u32, CharClassification::Normal),
    ('≀' as u32, CharClassification::Binary),
    ('≁' as u32, CharClassification::Relation),
    ('≂' as u32, CharClassification::Relation),
    ('≃' as u32, CharClassification::Relation),
    ('≄' as u32, CharClassification::Relation),
    ('≅' as u32, CharClassification::Relation),
    ('≆' as u32, CharClassification::Relation),
    ('≇' as u32, CharClassification::Relation),
    ('≈' as u32, CharClassification::Relation),
    ('≉' as u32, CharClassification::Relation),
    ('≊' as u32, CharClassification::Relation),
    ('≋' as u32, CharClassification::Relation),
    ('≌' as u32, CharClassification::Relation),
    ('≍' as u32, CharClassification::Relation),
    ('≎' as u32, CharClassification::Relation),
    ('≏' as u32, CharClassification::Relation),
    ('≐' as u32, CharClassification::Relation),
    ('≑' as u32, CharClassification::Relation),
    ('≒' as u32, CharClassification::Relation),
    ('≓' as u32, CharClassification::Relation),
    ('≔' as u32, CharClassification::Relation),
    ('≕' as u32, CharClassification::Relation),
    ('≖' as u32, CharClassification::Relation),
    ('≗' as u32, CharClassification::Relation),
    ('≘' as u32, CharClassification::Relation),
    ('≙' as u32, CharClassification::Relation),
    ('≚' as u32, CharClassification::Relation),
    ('≛' as u32, CharClassification::Relation),
    ('≜' as u32, CharClassification::Relation),
    ('≝' as u32, CharClassification::Relation),
    ('≞' as u32, CharClassification::Relation),
    ('≟' as u32, CharClassification::Relation),
    ('≠' as u32, CharClassification::Relation),
    ('≡' as u32, CharClassification::Relation),
    ('≢' as u32, CharClassification::Relation),
    ('≣' as u32, CharClassification::Relation),
    ('≤' as u32, CharClassification::Relation),
    ('≥' as u32, CharClassification::Relation),
    ('≦' as u32, CharClassification::Relation),
    ('≧' as u32, CharClassification::Relation),
    ('≨' as u32, CharClassification::Relation),
    ('≩' as u32, CharClassification::Relation),
    ('≪' as u32, CharClassification::Relation),
    ('≫' as u32, CharClassification::Relation),
    ('≬' as u32, CharClassification::Relation),
    ('≭' as u32, CharClassification::Relation),
    ('≮' as u32, CharClassification::Relation),
    ('≯' as u32, CharClassification::Relation),
    ('≰' as u32, CharClassification::Relation),
    ('≱' as u32, CharClassification::Relation),
    ('≲' as u32, CharClassification::Relation),
    ('≳' as u32, CharClassification::Relation),
    ('≴' as u32, CharClassification::Relation),
    ('≵' as u32, CharClassification::Relation),
    ('≶' as u32, CharClassification::Relation),
    ('≷' as u32, CharClassification::Relation),
    ('≸' as u32, CharClassification::Relation),
    ('≹' as u32, CharClassification::Relation),
    ('≺' as u32, CharClassification::Relation),
    ('≻' as u32, CharClassification::Relation),
    ('≼' as u32, CharClassification::Relation),
    ('≽' as u32, CharClassification::Relation),
    ('≾' as u32, CharClassification::Relation),
    ('≿' as u32, CharClassification::Relation),
    ('⊀' as u32, CharClassification::Relation),
    ('⊁' as u32, CharClassification::Relation),
    ('⊂' as u32, CharClassification::Relation),
    ('⊃' as u32, CharClassification::Relation),
    ('⊄' as u32, CharClassification::Relation),
    ('⊅' as u32, CharClassification::Relation),
    ('⊆' as u32, CharClassification::Relation),
    ('⊇' as u32, CharClassification::Relation),
    ('⊈' as u32, CharClassification::Relation),
    ('⊉' as u32, CharClassification::Relation),
    ('⊊' as u32, CharClassification::Relation),
    ('⊋' as u32, CharClassification::Relation),
    ('⊌' as u32, CharClassification::Binary),
    ('⊍' as u32, CharClassification::Binary),
    ('⊎' as u32, CharClassification::Binary),
    ('⊏' as u32, CharClassification::Relation),
    ('⊐' as u32, CharClassification::Relation),
    ('⊑' as u32, CharClassification::Relation),
    ('⊒' as u32, CharClassification::Relation),
    ('⊓' as u32, CharClassification::Binary),
    ('⊔' as u32, CharClassification::Binary),
    ('⊕' as u32, CharClassification::Binary),
    ('⊖' as u32, CharClassification::Binary),
    ('⊗' as u32, CharClassification::Binary),
    ('⊘' as u32, CharClassification::Binary),
    ('⊙' as u32, CharClassification::Binary),
    ('⊚' as u32, CharClassification::Binary),
    ('⊛' as u32, CharClassification::Binary),
    ('⊜' as u32, CharClassification::Binary),
    ('⊝' as u32, CharClassification::Binary),
    ('⊞' as u32, CharClassification::Binary),
    ('⊟' as u32, CharClassification::Binary),
    ('⊠' as u32, CharClassification::Binary),
    ('⊡' as u32, CharClassification::Binary),
    ('⊢' as u32, CharClassification::Relation),
    ('⊣' as u32, CharClassification::Relation),
    ('⊤' as u32, CharClassification::Normal),
    ('⊥' as u32, CharClassification::Relation),
    ('⊦' as u32, CharClassification::Relation),
    ('⊧' as u32, CharClassification::Relation),
    ('⊨' as u32, CharClassification::Relation),
    ('⊩' as u32, CharClassification::Relation),
    ('⊪' as u32, CharClassification::Relation),
    ('⊫' as u32, CharClassification::Relation),
    ('⊬' as u32, CharClassification::Relation),
    ('⊭' as u32, CharClassification::Relation),
    ('⊮' as u32, CharClassification::Relation),
    ('⊯' as u32, CharClassification::Relation),
    ('⊰' as u32, CharClassification::Relation),
    ('⊱' as u32, CharClassification::Relation),
    ('⊲' as u32, CharClassification::Relation),
    ('⊳' as u32, CharClassification::Relation),
    ('⊴' as u32, CharClassification::Relation),
    ('⊵' as u32, CharClassification::Relation),
    ('⊶' as u32, CharClassification::Relation),
    ('⊷' as u32, CharClassification::Relation),
    ('⊸' as u32, CharClassification::Relation),
    ('⊹' as u32, CharClassification::Binary),
    ('⊺' as u32, CharClassification::Binary),
    ('⊻' as u32, CharClassification::Binary),
    ('⊼' as u32, CharClassification::Binary),
    ('⊽' as u32, CharClassification::Binary),
    ('⊾' as u32, CharClassification::Normal),
    ('⊿' as u32, CharClassification::Normal),
    ('⋀' as u32, CharClassification::Large),
    ('⋁' as u32, CharClassification::Large),
    ('⋂' as u32, CharClassification::Large),
    ('⋃' as u32, CharClassification::Large),
    ('⋄' as u32, CharClassification::Binary),
    ('⋅' as u32, CharClassification::Binary),
    ('⋆' as u32, CharClassification::Binary),
    ('⋇' as u32, CharClassification::Binary),
    ('⋈' as u32, CharClassification::Relation),
    ('⋉' as u32, CharClassification::Binary),
    ('⋊' as u32, CharClassification::Binary),
    ('⋋' as u32, CharClassification::Binary),
    ('⋌' as u32, CharClassification::Binary),
    ('⋍' as u32, CharClassification::Relation),
    ('⋎' as u32, CharClassification::Binary),
    ('⋏' as u32, CharClassification::Binary),
    ('⋐' as u32, CharClassification::Relation),
    ('⋑' as u32, CharClassification::Relation),
    ('⋒' as u32, CharClassification::Binary),
    ('⋓' as u32, CharClassification::Binary),
    ('⋔' as u32, CharClassification::Relation),
    ('⋕' as u32, CharClassification::Relation),
    ('⋖' as u32, CharClassification::Relation),
    ('⋗' as u32, CharClassification::Relation),
    ('⋘' as u32, CharClassification::Relation),
    ('⋙' as u32, CharClassification::Relation),
    ('⋚' as u32, CharClassification::Relation),
    ('⋛' as u32, CharClassification::Relation),
    ('⋜' as u32, CharClassification::Relation),
    ('⋝' as u32, CharClassification::Relation),
    ('⋞' as u32, CharClassification::Relation),
    ('⋟' as u32, CharClassification::Relation),
    ('⋠' as u32, CharClassification::Relation),
    ('⋡' as u32, CharClassification::Relation),
    ('⋢' as u32, CharClassification::Relation),
    ('⋣' as u32, CharClassification::Relation),
    ('⋤' as u32, CharClassification::Relation),
    ('⋥' as u32, CharClassification::Relation),
    ('⋦' as u32, CharClassification::Relation),
    ('⋧' as u32, CharClassification::Relation),
    ('⋨' as u32, CharClassification::Relation),
    ('⋩' as u32, CharClassification::Relation),
    ('⋪' as u32, CharClassification::Relation),
    ('⋫' as u32, CharClassification::Relation),
    ('⋬' as u32, CharClassification::Relation),
    ('⋭' as u32, CharClassification::Relation),
    ('⋮' as u32, CharClassification::Relation),
    ('⋯' as u32, CharClassification::Relation),
    ('⋰' as u32, CharClassification::Relation),
    ('⋱' as u32, CharClassification::Relation),
    ('⋲' as u32, CharClassification::Relation),
    ('⋳' as u32, CharClassification::Relation),
    ('⋴' as u32, CharClassification::Relation),
    ('⋵' as u32, CharClassification::Relation),
    ('⋶' as u32, CharClassification::Relation),
    ('⋷' as u32, CharClassification::Relation),
    ('⋸' as u32, CharClassification::Relation),
    ('⋹' as u32, CharClassification::Relation),
    ('⋺' as u32, CharClassification::Relation),
    ('⋻' as u32, CharClassification::Relation),
    ('⋼' as u32, CharClassification::Relation),
    ('⋽' as u32, CharClassification::Relation),
    ('⋾' as u32, CharClassification::Relation),
    ('⋿' as u32, CharClassification::Relation),
    ('⌀' as u32, CharClassification::Normal),
    ('⌀' as u32 + 1, CharClassification::Ignore),
    ('⌂' as u32, CharClassification::Normal),
    ('⌂' as u32 + 1, CharClassification::Ignore),
    ('⌅' as u32, CharClassification::Binary),
    ('⌆' as u32, CharClassification::Binary),
    ('⌆' as u32 + 1, CharClassification::Ignore),
    ('⌈' as u32, CharClassification::Opening),
    ('⌉' as u32, CharClassification::Closing),
    ('⌊' as u32, CharClassification::Opening),
    ('⌋' as u32, CharClassification::Closing),
    ('⌋' as u32 + 1, CharClassification::Ignore),
    ('⌐' as u32, CharClassification::Normal),
    ('⌑' as u32, CharClassification::Normal),
    ('⌑' as u32 + 1, CharClassification::Ignore),
    ('⌙' as u32, CharClassification::Normal),
    ('⌙' as u32 + 1, CharClassification::Ignore),
    ('⌜' as u32, CharClassification::Opening),
    ('⌝' as u32, CharClassification::Closing),
    ('⌞' as u32, CharClassification::Opening),
    ('⌟' as u32, CharClassification::Closing),
    ('⌠' as u32, CharClassification::GlyphPart),
    ('⌢' as u32, CharClassification::Relation),
    ('⌣' as u32, CharClassification::Relation),
    ('⌣' as u32 + 1, CharClassification::Ignore),
    ('⌶' as u32, CharClassification::Normal),
    ('⌶' as u32 + 1, CharClassification::Ignore),
    ('⌽' as u32, CharClassification::Binary),
    ('⌽' as u32 + 1, CharClassification::Ignore),
    ('⌿' as u32, CharClassification::Relation),
    ('⌿' as u32 + 1, CharClassification::Ignore),
    ('⍼' as u32, CharClassification::Relation),
    ('⍼' as u32 + 1, CharClassification::Ignore),
    ('⎔' as u32, CharClassification::Normal),
    ('⎔' as u32 + 1, CharClassification::Ignore),
    ('⎛' as u32, CharClassification::GlyphPart),
    ('⎰' as u32, CharClassification::Relation),
    ('⎱' as u32, CharClassification::Relation),
    ('⎲' as u32, CharClassification::GlyphPart),
    ('⎴' as u32, CharClassification::Normal),
    ('⎵' as u32, CharClassification::Normal),
    ('⎶' as u32, CharClassification::Normal),
    ('⎷' as u32, CharClassification::GlyphPart),
    ('⎷' as u32 + 1, CharClassification::Ignore),
    ('⏐' as u32, CharClassification::GlyphPart),
    ('⏐' as u32 + 1, CharClassification::Ignore),
    ('⏜' as u32, CharClassification::Normal),
    ('⏝' as u32, CharClassification::Normal),
    ('⏞' as u32, CharClassification::Normal),
    ('⏟' as u32, CharClassification::Normal),
    ('⏠' as u32, CharClassification::Normal),
    ('⏡' as u32, CharClassification::Normal),
    ('⏢' as u32, CharClassification::Normal),
    ('⏣' as u32, CharClassification::Normal),
    ('⏤' as u32, CharClassification::Normal),
    ('⏥' as u32, CharClassification::Normal),
    ('⏦' as u32, CharClassification::Normal),
    ('⏧' as u32, CharClassification::Normal),
    ('⏧' as u32 + 1, CharClassification::Ignore),
    ('Ⓢ' as u32, CharClassification::Normal),
    ('Ⓢ' as u32 + 1, CharClassification::Ignore),
    ('■' as u32, CharClassification::Normal),
    ('□' as u32, CharClassification::Normal),
    ('□' as u32 + 1, CharClassification::Ignore),
    ('▪' as u32, CharClassification::Normal),
    ('▫' as u32, CharClassification::Normal),
    ('▫' as u32 + 1, CharClassification::Ignore),
    ('▭' as u32, CharClassification::Normal),
    ('▮' as u32, CharClassification::Normal),
    ('▯' as u32, CharClassification::Normal),
    ('▰' as u32, CharClassification::Normal),
    ('▱' as u32, CharClassification::Normal),
    ('▲' as u32, CharClassification::Binary),
    ('△' as u32, CharClassification::Binary),
    ('▴' as u32, CharClassification::Binary),
    ('▵' as u32, CharClassification::Binary),
    ('▶' as u32, CharClassification::Binary),
    ('▷' as u32, CharClassification::Binary),
    ('▸' as u32, CharClassification::Binary),
    ('▹' as u32, CharClassification::Binary),
    ('▹' as u32 + 1, CharClassification::Ignore),
    ('▼' as u32, CharClassification::Binary),
    ('▽' as u32, CharClassification::Binary),
    ('▾' as u32, CharClassification::Binary),
    ('▿' as u32, CharClassification::Binary),
    ('◀' as u32, CharClassification::Binary),
    ('◁' as u32, CharClassification::Binary),
    ('◂' as u32, CharClassification::Binary),
    ('◃' as u32, CharClassification::Binary),
    ('◄' as u32, CharClassification::Binary),
    ('◅' as u32, CharClassification::Binary),
    ('◆' as u32, CharClassification::Normal),
    ('◇' as u32, CharClassification::Normal),
    ('◈' as u32, CharClassification::Normal),
    ('◉' as u32, CharClassification::Normal),
    ('◊' as u32, CharClassification::Binary),
    ('○' as u32, CharClassification::Binary),
    ('○' as u32 + 1, CharClassification::Ignore),
    ('◎' as u32, CharClassification::Normal),
    ('●' as u32, CharClassification::Normal),
    ('◐' as u32, CharClassification::Normal),
    ('◓' as u32 + 1, CharClassification::Ignore),
    ('◖' as u32, CharClassification::Normal),
    ('◗' as u32, CharClassification::Normal),
    ('◗' as u32 + 1, CharClassification::Ignore),
    ('◢' as u32, CharClassification::Normal),
    ('◣' as u32, CharClassification::Normal),
    ('◤' as u32, CharClassification::Normal),
    ('◥' as u32, CharClassification::Normal),
    ('◦' as u32, CharClassification::Binary),
    ('◧' as u32, CharClassification::Normal),
    ('◫' as u32, CharClassification::Binary),
    ('◬' as u32, CharClassification::Binary),
    ('◬' as u32 + 1, CharClassification::Ignore),
    ('◯' as u32, CharClassification::Normal),
    ('◯' as u32 + 1, CharClassification::Ignore),
    ('◸' as u32, CharClassification::Binary),
    ('◹' as u32, CharClassification::Binary),
    ('◺' as u32, CharClassification::Binary),
    ('◻' as u32, CharClassification::Binary),
    ('◼' as u32, CharClassification::Binary),
    ('◽' as u32, CharClassification::Binary),
    ('◾' as u32, CharClassification::Binary),
    ('◿' as u32, CharClassification::Binary),
    ('◿' as u32 + 1, CharClassification::Ignore),
    ('★' as u32, CharClassification::Binary),
    ('☆' as u32, CharClassification::Binary),
    ('☆' as u32 + 1, CharClassification::Ignore),
    ('☉' as u32, CharClassification::Normal),
    ('☉' as u32 + 1, CharClassification::Ignore),
    ('☌' as u32, CharClassification::Normal),
    ('☌' as u32 + 1, CharClassification::Ignore),
    ('☽' as u32, CharClassification::Normal),
    ('☾' as u32, CharClassification::Normal),
    ('☿' as u32, CharClassification::Normal),
    ('♀' as u32, CharClassification::Normal),
    ('♁' as u32, CharClassification::Normal),
    ('♂' as u32, CharClassification::Normal),
    ('♃' as u32, CharClassification::Normal),
    ('♄' as u32, CharClassification::Normal),
    ('♄' as u32 + 1, CharClassification::Ignore),
    ('♆' as u32, CharClassification::Normal),
    ('♇' as u32, CharClassification::Normal),
    ('♈' as u32, CharClassification::Normal),
    ('♉' as u32, CharClassification::Normal),
    ('♉' as u32 + 1, CharClassification::Ignore),
    ('♠' as u32, CharClassification::Normal),
    ('♡' as u32, CharClassification::Normal),
    ('♢' as u32, CharClassification::Normal),
    ('♣' as u32, CharClassification::Normal),
    ('♤' as u32, CharClassification::Normal),
    ('♥' as u32, CharClassification::Normal),
    ('♦' as u32, CharClassification::Normal),
    ('♧' as u32, CharClassification::Normal),
    ('♧' as u32 + 1, CharClassification::Ignore),
    ('♩' as u32, CharClassification::Normal),
    ('♩' as u32 + 1, CharClassification::Ignore),
    ('♭' as u32, CharClassification::Normal),
    ('♮' as u32, CharClassification::Normal),
    ('♯' as u32, CharClassification::Normal),
    ('♯' as u32 + 1, CharClassification::Ignore),
    ('⚀' as u32, CharClassification::Normal),
    ('⚁' as u32, CharClassification::Normal),
    ('⚂' as u32, CharClassification::Normal),
    ('⚃' as u32, CharClassification::Normal),
    ('⚄' as u32, CharClassification::Normal),
    ('⚅' as u32, CharClassification::Normal),
    ('⚆' as u32, CharClassification::Normal),
    ('⚇' as u32, CharClassification::Normal),
    ('⚈' as u32, CharClassification::Normal),
    ('⚉' as u32, CharClassification::Normal),
    ('⚉' as u32 + 1, CharClassification::Ignore),
    ('⚪' as u32, CharClassification::Normal),
    ('⚫' as u32, CharClassification::Normal),
    ('⚬' as u32, CharClassification::Normal),
    ('⚬' as u32 + 1, CharClassification::Ignore),
    ('⚲' as u32, CharClassification::Normal),
    ('⚲' as u32 + 1, CharClassification::Ignore),
    ('✓' as u32, CharClassification::Normal),
    ('✓' as u32 + 1, CharClassification::Ignore),
    ('✗' as u32, CharClassification::Normal),
    ('✗' as u32 + 1, CharClassification::Ignore),
    ('✠' as u32, CharClassification::Normal),
    ('✠' as u32 + 1, CharClassification::Ignore),
    ('✪' as u32, CharClassification::Normal),
    ('✪' as u32 + 1, CharClassification::Ignore),
    ('✶' as u32, CharClassification::Normal),
    ('✶' as u32 + 1, CharClassification::Ignore),
    ('❲' as u32, CharClassification::Opening),
    ('❳' as u32, CharClassification::Closing),
    ('❳' as u32 + 1, CharClassification::Ignore),
    ('⟀' as u32, CharClassification::Normal),
    ('⟁' as u32, CharClassification::Normal),
    ('⟂' as u32, CharClassification::Relation),
    ('⟃' as u32, CharClassification::Relation),
    ('⟄' as u32, CharClassification::Relation),
    ('⟅' as u32, CharClassification::Relation),
    ('⟆' as u32, CharClassification::Relation),
    ('⟇' as u32, CharClassification::Relation),
    ('⟈' as u32, CharClassification::Relation),
    ('⟉' as u32, CharClassification::Relation),
    ('⟊' as u32, CharClassification::Relation),
    ('⟋' as u32, CharClassification::Relation),
    ('⟌' as u32, CharClassification::Large),
    ('⟍' as u32, CharClassification::Relation),
    ('⟎' as u32, CharClassification::Binary),
    ('⟏' as u32, CharClassification::Binary),
    ('⟐' as u32, CharClassification::Normal),
    ('⟑' as u32, CharClassification::Binary),
    ('⟒' as u32, CharClassification::Relation),
    ('⟓' as u32, CharClassification::Relation),
    ('⟔' as u32, CharClassification::Relation),
    ('⟕' as u32, CharClassification::Large),
    ('⟖' as u32, CharClassification::Large),
    ('⟗' as u32, CharClassification::Large),
    ('⟘' as u32, CharClassification::Large),
    ('⟙' as u32, CharClassification::Large),
    ('⟚' as u32, CharClassification::Relation),
    ('⟛' as u32, CharClassification::Relation),
    ('⟜' as u32, CharClassification::Relation),
    ('⟝' as u32, CharClassification::Relation),
    ('⟞' as u32, CharClassification::Relation),
    ('⟟' as u32, CharClassification::Relation),
    ('⟠' as u32, CharClassification::Binary),
    ('⟡' as u32, CharClassification::Binary),
    ('⟢' as u32, CharClassification::Binary),
    ('⟣' as u32, CharClassification::Binary),
    ('⟤' as u32, CharClassification::Binary),
    ('⟥' as u32, CharClassification::Binary),
    ('⟦' as u32, CharClassification::Opening),
    ('⟧' as u32, CharClassification::Closing),
    ('⟨' as u32, CharClassification::Opening),
    ('⟩' as u32, CharClassification::Closing),
    ('⟪' as u32, CharClassification::Opening),
    ('⟫' as u32, CharClassification::Closing),
    ('⟬' as u32, CharClassification::Opening),
    ('⟭' as u32, CharClassification::Closing),
    ('⟮' as u32, CharClassification::Opening),
    ('⟯' as u32, CharClassification::Closing),
    ('⟰' as u32, CharClassification::Relation),
    ('⟱' as u32, CharClassification::Relation),
    ('⟲' as u32, CharClassification::Relation),
    ('⟳' as u32, CharClassification::Relation),
    ('⟴' as u32, CharClassification::Relation),
    ('⟵' as u32, CharClassification::Relation),
    ('⟶' as u32, CharClassification::Relation),
    ('⟷' as u32, CharClassification::Relation),
    ('⟸' as u32, CharClassification::Relation),
    ('⟹' as u32, CharClassification::Relation),
    ('⟺' as u32, CharClassification::Relation),
    ('⟻' as u32, CharClassification::Relation),
    ('⟼' as u32, CharClassification::Relation),
    ('⟽' as u32, CharClassification::Relation),
    ('⟾' as u32, CharClassification::Relation),
    ('⟿' as u32, CharClassification::Relation),
    ('⟿' as u32 + 1, CharClassification::Ignore),
    ('⤀' as u32, CharClassification::Relation),
    ('⤁' as u32, CharClassification::Relation),
    ('⤂' as u32, CharClassification::Relation),
    ('⤃' as u32, CharClassification::Relation),
    ('⤄' as u32, CharClassification::Relation),
    ('⤅' as u32, CharClassification::Relation),
    ('⤆' as u32, CharClassification::Relation),
    ('⤇' as u32, CharClassification::Relation),
    ('⤈' as u32, CharClassification::Relation),
    ('⤉' as u32, CharClassification::Relation),
    ('⤊' as u32, CharClassification::Relation),
    ('⤋' as u32, CharClassification::Relation),
    ('⤌' as u32, CharClassification::Relation),
    ('⤍' as u32, CharClassification::Relation),
    ('⤎' as u32, CharClassification::Relation),
    ('⤏' as u32, CharClassification::Relation),
    ('⤐' as u32, CharClassification::Relation),
    ('⤑' as u32, CharClassification::Relation),
    ('⤒' as u32, CharClassification::Relation),
    ('⤓' as u32, CharClassification::Relation),
    ('⤔' as u32, CharClassification::Relation),
    ('⤕' as u32, CharClassification::Relation),
    ('⤖' as u32, CharClassification::Relation),
    ('⤗' as u32, CharClassification::Relation),
    ('⤘' as u32, CharClassification::Relation),
    ('⤙' as u32, CharClassification::Relation),
    ('⤚' as u32, CharClassification::Relation),
    ('⤛' as u32, CharClassification::Relation),
    ('⤜' as u32, CharClassification::Relation),
    ('⤝' as u32, CharClassification::Relation),
    ('⤞' as u32, CharClassification::Relation),
    ('⤟' as u32, CharClassification::Relation),
    ('⤠' as u32, CharClassification::Relation),
    ('⤡' as u32, CharClassification::Relation),
    ('⤢' as u32, CharClassification::Relation),
    ('⤣' as u32, CharClassification::Relation),
    ('⤤' as u32, CharClassification::Relation),
    ('⤥' as u32, CharClassification::Relation),
    ('⤦' as u32, CharClassification::Relation),
    ('⤧' as u32, CharClassification::Relation),
    ('⤨' as u32, CharClassification::Relation),
    ('⤩' as u32, CharClassification::Relation),
    ('⤪' as u32, CharClassification::Relation),
    ('⤫' as u32, CharClassification::Relation),
    ('⤬' as u32, CharClassification::Relation),
    ('⤭' as u32, CharClassification::Relation),
    ('⤮' as u32, CharClassification::Relation),
    ('⤯' as u32, CharClassification::Relation),
    ('⤰' as u32, CharClassification::Relation),
    ('⤱' as u32, CharClassification::Relation),
    ('⤲' as u32, CharClassification::Relation),
    ('⤳' as u32, CharClassification::Relation),
    ('⤴' as u32, CharClassification::Relation),
    ('⤵' as u32, CharClassification::Relation),
    ('⤶' as u32, CharClassification::Relation),
    ('⤷' as u32, CharClassification::Relation),
    ('⤸' as u32, CharClassification::Relation),
    ('⤹' as u32, CharClassification::Relation),
    ('⤺' as u32, CharClassification::Relation),
    ('⤻' as u32, CharClassification::Relation),
    ('⤼' as u32, CharClassification::Relation),
    ('⤽' as u32, CharClassification::Relation),
    ('⤾' as u32, CharClassification::Relation),
    ('⤿' as u32, CharClassification::Relation),
    ('⥀' as u32, CharClassification::Relation),
    ('⥁' as u32, CharClassification::Relation),
    ('⥂' as u32, CharClassification::Relation),
    ('⥃' as u32, CharClassification::Relation),
    ('⥄' as u32, CharClassification::Relation),
    ('⥅' as u32, CharClassification::Relation),
    ('⥆' as u32, CharClassification::Relation),
    ('⥇' as u32, CharClassification::Relation),
    ('⥈' as u32, CharClassification::Relation),
    ('⥉' as u32, CharClassification::Relation),
    ('⥊' as u32, CharClassification::Relation),
    ('⥋' as u32, CharClassification::Relation),
    ('⥌' as u32, CharClassification::Relation),
    ('⥍' as u32, CharClassification::Relation),
    ('⥎' as u32, CharClassification::Relation),
    ('⥏' as u32, CharClassification::Relation),
    ('⥐' as u32, CharClassification::Relation),
    ('⥑' as u32, CharClassification::Relation),
    ('⥒' as u32, CharClassification::Relation),
    ('⥓' as u32, CharClassification::Relation),
    ('⥔' as u32, CharClassification::Relation),
    ('⥕' as u32, CharClassification::Relation),
    ('⥖' as u32, CharClassification::Relation),
    ('⥗' as u32, CharClassification::Relation),
    ('⥘' as u32, CharClassification::Relation),
    ('⥙' as u32, CharClassification::Relation),
    ('⥚' as u32, CharClassification::Relation),
    ('⥛' as u32, CharClassification::Relation),
    ('⥜' as u32, CharClassification::Relation),
    ('⥝' as u32, CharClassification::Relation),
    ('⥞' as u32, CharClassification::Relation),
    ('⥟' as u32, CharClassification::Relation),
    ('⥠' as u32, CharClassification::Relation),
    ('⥡' as u32, CharClassification::Relation),
    ('⥢' as u32, CharClassification::Relation),
    ('⥣' as u32, CharClassification::Relation),
    ('⥤' as u32, CharClassification::Relation),
    ('⥥' as u32, CharClassification::Relation),
    ('⥦' as u32, CharClassification::Relation),
    ('⥧' as u32, CharClassification::Relation),
    ('⥨' as u32, CharClassification::Relation),
    ('⥩' as u32, CharClassification::Relation),
    ('⥪' as u32, CharClassification::Relation),
    ('⥫' as u32, CharClassification::Relation),
    ('⥬' as u32, CharClassification::Relation),
    ('⥭' as u32, CharClassification::Relation),
    ('⥮' as u32, CharClassification::Relation),
    ('⥯' as u32, CharClassification::Relation),
    ('⥰' as u32, CharClassification::Relation),
    ('⥱' as u32, CharClassification::Relation),
    ('⥲' as u32, CharClassification::Relation),
    ('⥳' as u32, CharClassification::Relation),
    ('⥴' as u32, CharClassification::Relation),
    ('⥵' as u32, CharClassification::Relation),
    ('⥶' as u32, CharClassification::Relation),
    ('⥷' as u32, CharClassification::Relation),
    ('⥸' as u32, CharClassification::Relation),
    ('⥹' as u32, CharClassification::Relation),
    ('⥺' as u32, CharClassification::Relation),
    ('⥻' as u32, CharClassification::Relation),
    ('⥼' as u32, CharClassification::Relation),
    ('⥽' as u32, CharClassification::Relation),
    ('⥾' as u32, CharClassification::Relation),
    ('⥿' as u32, CharClassification::Relation),
    ('⦀' as u32, CharClassification::Fence),
    ('⦁' as u32, CharClassification::Normal),
    ('⦂' as u32, CharClassification::Fence),
    ('⦃' as u32, CharClassification::Opening),
    ('⦄' as u32, CharClassification::Closing),
    ('⦅' as u32, CharClassification::Opening),
    ('⦆' as u32, CharClassification::Closing),
    ('⦇' as u32, CharClassification::Opening),
    ('⦈' as u32, CharClassification::Closing),
    ('⦉' as u32, CharClassification::Opening),
    ('⦊' as u32, CharClassification::Closing),
    ('⦋' as u32, CharClassification::Opening),
    ('⦌' as u32, CharClassification::Closing),
    ('⦍' as u32, CharClassification::Opening),
    ('⦎' as u32, CharClassification::Closing),
    ('⦏' as u32, CharClassification::Opening),
    ('⦐' as u32, CharClassification::Closing),
    ('⦑' as u32, CharClassification::Opening),
    ('⦒' as u32, CharClassification::Closing),
    ('⦓' as u32, CharClassification::Opening),
    ('⦔' as u32, CharClassification::Closing),
    ('⦕' as u32, CharClassification::Opening),
    ('⦖' as u32, CharClassification::Closing),
    ('⦗' as u32, CharClassification::Opening),
    ('⦘' as u32, CharClassification::Closing),
    ('⦙' as u32, CharClassification::Fence),
    ('⦚' as u32, CharClassification::Fence),
    ('⦛' as u32, CharClassification::Normal),
    ('⦜' as u32, CharClassification::Normal),
    ('⦝' as u32, CharClassification::Normal),
    ('⦞' as u32, CharClassification::Normal),
    ('⦟' as u32, CharClassification::Normal),
    ('⦠' as u32, CharClassification::Normal),
    ('⦡' as u32, CharClassification::Normal),
    ('⦢' as u32, CharClassification::Normal),
    ('⦣' as u32, CharClassification::Normal),
    ('⦤' as u32, CharClassification::Normal),
    ('⦥' as u32, CharClassification::Normal),
    ('⦦' as u32, CharClassification::Normal),
    ('⦧' as u32, CharClassification::Normal),
    ('⦨' as u32, CharClassification::Normal),
    ('⦩' as u32, CharClassification::Normal),
    ('⦪' as u32, CharClassification::Normal),
    ('⦫' as u32, CharClassification::Normal),
    ('⦬' as u32, CharClassification::Normal),
    ('⦭' as u32, CharClassification::Normal),
    ('⦮' as u32, CharClassification::Normal),
    ('⦯' as u32, CharClassification::Normal),
    ('⦰' as u32, CharClassification::Normal),
    ('⦱' as u32, CharClassification::Normal),
    ('⦲' as u32, CharClassification::Normal),
    ('⦳' as u32, CharClassification::Normal),
    ('⦴' as u32, CharClassification::Normal),
    ('⦵' as u32, CharClassification::Normal),
    ('⦶' as u32, CharClassification::Binary),
    ('⦷' as u32, CharClassification::Binary),
    ('⦸' as u32, CharClassification::Binary),
    ('⦹' as u32, CharClassification::Binary),
    ('⦺' as u32, CharClassification::Normal),
    ('⦻' as u32, CharClassification::Normal),
    ('⦼' as u32, CharClassification::Normal),
    ('⦽' as u32, CharClassification::Normal),
    ('⦾' as u32, CharClassification::Normal),
    ('⦿' as u32, CharClassification::Normal),
    ('⧀' as u32, CharClassification::Binary),
    ('⧁' as u32, CharClassification::Binary),
    ('⧂' as u32, CharClassification::Normal),
    ('⧃' as u32, CharClassification::Normal),
    ('⧄' as u32, CharClassification::Binary),
    ('⧅' as u32, CharClassification::Binary),
    ('⧆' as u32, CharClassification::Binary),
    ('⧇' as u32, CharClassification::Binary),
    ('⧈' as u32, CharClassification::Binary),
    ('⧉' as u32, CharClassification::Normal),
    ('⧊' as u32, CharClassification::Normal),
    ('⧋' as u32, CharClassification::Normal),
    ('⧌' as u32, CharClassification::Normal),
    ('⧍' as u32, CharClassification::Normal),
    ('⧎' as u32, CharClassification::Relation),
    ('⧏' as u32, CharClassification::Relation),
    ('⧐' as u32, CharClassification::Relation),
    ('⧑' as u32, CharClassification::Relation),
    ('⧒' as u32, CharClassification::Relation),
    ('⧓' as u32, CharClassification::Relation),
    ('⧔' as u32, CharClassification::Relation),
    ('⧕' as u32, CharClassification::Relation),
    ('⧖' as u32, CharClassification::Binary),
    ('⧗' as u32, CharClassification::Binary),
    ('⧘' as u32, CharClassification::Opening),
    ('⧙' as u32, CharClassification::Closing),
    ('⧚' as u32, CharClassification::Opening),
    ('⧛' as u32, CharClassification::Closing),
    ('⧜' as u32, CharClassification::Normal),
    ('⧝' as u32, CharClassification::Normal),
    ('⧞' as u32, CharClassification::Normal),
    ('⧟' as u32, CharClassification::Relation),
    ('⧠' as u32, CharClassification::Normal),
    ('⧡' as u32, CharClassification::Relation),
    ('⧢' as u32, CharClassification::Binary),
    ('⧣' as u32, CharClassification::Relation),
    ('⧤' as u32, CharClassification::Relation),
    ('⧥' as u32, CharClassification::Relation),
    ('⧦' as u32, CharClassification::Relation),
    ('⧧' as u32, CharClassification::Normal),
    ('⧨' as u32, CharClassification::Normal),
    ('⧩' as u32, CharClassification::Normal),
    ('⧪' as u32, CharClassification::Normal),
    ('⧫' as u32, CharClassification::Binary),
    ('⧬' as u32, CharClassification::Normal),
    ('⧭' as u32, CharClassification::Normal),
    ('⧮' as u32, CharClassification::Normal),
    ('⧯' as u32, CharClassification::Normal),
    ('⧰' as u32, CharClassification::Normal),
    ('⧱' as u32, CharClassification::Normal),
    ('⧲' as u32, CharClassification::Normal),
    ('⧳' as u32, CharClassification::Normal),
    ('⧴' as u32, CharClassification::Relation),
    ('⧵' as u32, CharClassification::Binary),
    ('⧶' as u32, CharClassification::Binary),
    ('⧷' as u32, CharClassification::Binary),
    ('⧸' as u32, CharClassification::Large),
    ('⧹' as u32, CharClassification::Large),
    ('⧺' as u32, CharClassification::Binary),
    ('⧻' as u32, CharClassification::Binary),
    ('⧼' as u32, CharClassification::Opening),
    ('⧽' as u32, CharClassification::Closing),
    ('⧾' as u32, CharClassification::Binary),
    ('⧿' as u32, CharClassification::Binary),
    ('⨀' as u32, CharClassification::Large),
    ('⨁' as u32, CharClassification::Large),
    ('⨂' as u32, CharClassification::Large),
    ('⨃' as u32, CharClassification::Large),
    ('⨄' as u32, CharClassification::Large),
    ('⨅' as u32, CharClassification::Large),
    ('⨆' as u32, CharClassification::Large),
    ('⨇' as u32, CharClassification::Large),
    ('⨈' as u32, CharClassification::Large),
    ('⨉' as u32, CharClassification::Large),
    ('⨊' as u32, CharClassification::Large),
    ('⨋' as u32, CharClassification::Large),
    ('⨌' as u32, CharClassification::Large),
    ('⨍' as u32, CharClassification::Large),
    ('⨎' as u32, CharClassification::Large),
    ('⨏' as u32, CharClassification::Large),
    ('⨐' as u32, CharClassification::Large),
    ('⨑' as u32, CharClassification::Large),
    ('⨒' as u32, CharClassification::Large),
    ('⨓' as u32, CharClassification::Large),
    ('⨔' as u32, CharClassification::Large),
    ('⨕' as u32, CharClassification::Large),
    ('⨖' as u32, CharClassification::Large),
    ('⨗' as u32, CharClassification::Large),
    ('⨘' as u32, CharClassification::Large),
    ('⨙' as u32, CharClassification::Large),
    ('⨚' as u32, CharClassification::Large),
    ('⨛' as u32, CharClassification::Large),
    ('⨜' as u32, CharClassification::Large),
    ('⨝' as u32, CharClassification::Large),
    ('⨞' as u32, CharClassification::Large),
    ('⨟' as u32, CharClassification::Large),
    ('⨠' as u32, CharClassification::Large),
    ('⨡' as u32, CharClassification::Large),
    ('⨢' as u32, CharClassification::Binary),
    ('⨣' as u32, CharClassification::Binary),
    ('⨤' as u32, CharClassification::Binary),
    ('⨥' as u32, CharClassification::Binary),
    ('⨦' as u32, CharClassification::Binary),
    ('⨧' as u32, CharClassification::Binary),
    ('⨨' as u32, CharClassification::Binary),
    ('⨩' as u32, CharClassification::Binary),
    ('⨪' as u32, CharClassification::Binary),
    ('⨫' as u32, CharClassification::Binary),
    ('⨬' as u32, CharClassification::Binary),
    ('⨭' as u32, CharClassification::Binary),
    ('⨮' as u32, CharClassification::Binary),
    ('⨯' as u32, CharClassification::Binary),
    ('⨰' as u32, CharClassification::Binary),
    ('⨱' as u32, CharClassification::Binary),
    ('⨲' as u32, CharClassification::Binary),
    ('⨳' as u32, CharClassification::Binary),
    ('⨴' as u32, CharClassification::Binary),
    ('⨵' as u32, CharClassification::Binary),
    ('⨶' as u32, CharClassification::Binary),
    ('⨷' as u32, CharClassification::Binary),
    ('⨸' as u32, CharClassification::Binary),
    ('⨹' as u32, CharClassification::Binary),
    ('⨺' as u32, CharClassification::Binary),
    ('⨻' as u32, CharClassification::Binary),
    ('⨼' as u32, CharClassification::Binary),
    ('⨽' as u32, CharClassification::Binary),
    ('⨾' as u32, CharClassification::Binary),
    ('⨿' as u32, CharClassification::Binary),
    ('⩀' as u32, CharClassification::Binary),
    ('⩁' as u32, CharClassification::Binary),
    ('⩂' as u32, CharClassification::Binary),
    ('⩃' as u32, CharClassification::Binary),
    ('⩄' as u32, CharClassification::Binary),
    ('⩅' as u32, CharClassification::Binary),
    ('⩆' as u32, CharClassification::Binary),
    ('⩇' as u32, CharClassification::Binary),
    ('⩈' as u32, CharClassification::Binary),
    ('⩉' as u32, CharClassification::Binary),
    ('⩊' as u32, CharClassification::Binary),
    ('⩋' as u32, CharClassification::Binary),
    ('⩌' as u32, CharClassification::Binary),
    ('⩍' as u32, CharClassification::Binary),
    ('⩎' as u32, CharClassification::Binary),
    ('⩏' as u32, CharClassification::Binary),
    ('⩐' as u32, CharClassification::Binary),
    ('⩑' as u32, CharClassification::Binary),
    ('⩒' as u32, CharClassification::Binary),
    ('⩓' as u32, CharClassification::Binary),
    ('⩔' as u32, CharClassification::Binary),
    ('⩕' as u32, CharClassification::Binary),
    ('⩖' as u32, CharClassification::Binary),
    ('⩗' as u32, CharClassification::Binary),
    ('⩘' as u32, CharClassification::Binary),
    ('⩙' as u32, CharClassification::Relation),
    ('⩚' as u32, CharClassification::Binary),
    ('⩛' as u32, CharClassification::Binary),
    ('⩜' as u32, CharClassification::Binary),
    ('⩝' as u32, CharClassification::Binary),
    ('⩞' as u32, CharClassification::Binary),
    ('⩟' as u32, CharClassification::Binary),
    ('⩠' as u32, CharClassification::Binary),
    ('⩡' as u32, CharClassification::Binary),
    ('⩢' as u32, CharClassification::Binary),
    ('⩣' as u32, CharClassification::Binary),
    ('⩤' as u32, CharClassification::Binary),
    ('⩥' as u32, CharClassification::Binary),
    ('⩦' as u32, CharClassification::Relation),
    ('⩧' as u32, CharClassification::Relation),
    ('⩨' as u32, CharClassification::Relation),
    ('⩩' as u32, CharClassification::Relation),
    ('⩪' as u32, CharClassification::Relation),
    ('⩫' as u32, CharClassification::Relation),
    ('⩬' as u32, CharClassification::Relation),
    ('⩭' as u32, CharClassification::Relation),
    ('⩮' as u32, CharClassification::Relation),
    ('⩯' as u32, CharClassification::Relation),
    ('⩰' as u32, CharClassification::Relation),
    ('⩱' as u32, CharClassification::Binary),
    ('⩲' as u32, CharClassification::Binary),
    ('⩳' as u32, CharClassification::Relation),
    ('⩴' as u32, CharClassification::Relation),
    ('⩵' as u32, CharClassification::Relation),
    ('⩶' as u32, CharClassification::Relation),
    ('⩷' as u32, CharClassification::Relation),
    ('⩸' as u32, CharClassification::Relation),
    ('⩹' as u32, CharClassification::Relation),
    ('⩺' as u32, CharClassification::Relation),
    ('⩻' as u32, CharClassification::Relation),
    ('⩼' as u32, CharClassification::Relation),
    ('⩽' as u32, CharClassification::Relation),
    ('⩾' as u32, CharClassification::Relation),
    ('⩿' as u32, CharClassification::Relation),
    ('⪀' as u32, CharClassification::Relation),
    ('⪁' as u32, CharClassification::Relation),
    ('⪂' as u32, CharClassification::Relation),
    ('⪃' as u32, CharClassification::Relation),
    ('⪄' as u32, CharClassification::Relation),
    ('⪅' as u32, CharClassification::Relation),
    ('⪆' as u32, CharClassification::Relation),
    ('⪇' as u32, CharClassification::Relation),
    ('⪈' as u32, CharClassification::Relation),
    ('⪉' as u32, CharClassification::Relation),
    ('⪊' as u32, CharClassification::Relation),
    ('⪋' as u32, CharClassification::Relation),
    ('⪌' as u32, CharClassification::Relation),
    ('⪍' as u32, CharClassification::Relation),
    ('⪎' as u32, CharClassification::Relation),
    ('⪏' as u32, CharClassification::Relation),
    ('⪐' as u32, CharClassification::Relation),
    ('⪑' as u32, CharClassification::Relation),
    ('⪒' as u32, CharClassification::Relation),
    ('⪓' as u32, CharClassification::Relation),
    ('⪔' as u32, CharClassification::Relation),
    ('⪕' as u32, CharClassification::Relation),
    ('⪖' as u32, CharClassification::Relation),
    ('⪗' as u32, CharClassification::Relation),
    ('⪘' as u32, CharClassification::Relation),
    ('⪙' as u32, CharClassification::Relation),
    ('⪚' as u32, CharClassification::Relation),
    ('⪛' as u32, CharClassification::Relation),
    ('⪜' as u32, CharClassification::Relation),
    ('⪝' as u32, CharClassification::Relation),
    ('⪞' as u32, CharClassification::Relation),
    ('⪟' as u32, CharClassification::Relation),
    ('⪠' as u32, CharClassification::Relation),
    ('⪡' as u32, CharClassification::Relation),
    ('⪢' as u32, CharClassification::Relation),
    ('⪣' as u32, CharClassification::Relation),
    ('⪤' as u32, CharClassification::Relation),
    ('⪥' as u32, CharClassification::Relation),
    ('⪦' as u32, CharClassification::Relation),
    ('⪧' as u32, CharClassification::Relation),
    ('⪨' as u32, CharClassification::Relation),
    ('⪩' as u32, CharClassification::Relation),
    ('⪪' as u32, CharClassification::Relation),
    ('⪫' as u32, CharClassification::Relation),
    ('⪬' as u32, CharClassification::Relation),
    ('⪭' as u32, CharClassification::Relation),
    ('⪮' as u32, CharClassification::Relation),
    ('⪯' as u32, CharClassification::Relation),
    ('⪰' as u32, CharClassification::Relation),
    ('⪱' as u32, CharClassification::Relation),
    ('⪲' as u32, CharClassification::Relation),
    ('⪳' as u32, CharClassification::Relation),
    ('⪴' as u32, CharClassification::Relation),
    ('⪵' as u32, CharClassification::Relation),
    ('⪶' as u32, CharClassification::Relation),
    ('⪷' as u32, CharClassification::Relation),
    ('⪸' as u32, CharClassification::Relation),
    ('⪹' as u32, CharClassification::Relation),
    ('⪺' as u32, CharClassification::Relation),
    ('⪻' as u32, CharClassification::Relation),
    ('⪼' as u32, CharClassification::Relation),
    ('⪽' as u32, CharClassification::Relation),
    ('⪾' as u32, CharClassification::Relation),
    ('⪿' as u32, CharClassification::Relation),
    ('⫀' as u32, CharClassification::Relation),
    ('⫁' as u32, CharClassification::Relation),
    ('⫂' as u32, CharClassification::Relation),
    ('⫃' as u32, CharClassification::Relation),
    ('⫄' as u32, CharClassification::Relation),
    ('⫅' as u32, CharClassification::Relation),
    ('⫆' as u32, CharClassification::Relation),
    ('⫇' as u32, CharClassification::Relation),
    ('⫈' as u32, CharClassification::Relation),
    ('⫉' as u32, CharClassification::Relation),
    ('⫊' as u32, CharClassification::Relation),
    ('⫋' as u32, CharClassification::Relation),
    ('⫌' as u32, CharClassification::Relation),
    ('⫍' as u32, CharClassification::Relation),
    ('⫎' as u32, CharClassification::Relation),
    ('⫏' as u32, CharClassification::Relation),
    ('⫐' as u32, CharClassification::Relation),
    ('⫑' as u32, CharClassification::Relation),
    ('⫒' as u32, CharClassification::Relation),
    ('⫓' as u32, CharClassification::Relation),
    ('⫔' as u32, CharClassification::Relation),
    ('⫕' as u32, CharClassification::Relation),
    ('⫖' as u32, CharClassification::Relation),
    ('⫗' as u32, CharClassification::Relation),
    ('⫘' as u32, CharClassification::Relation),
    ('⫙' as u32, CharClassification::Relation),
    ('⫚' as u32, CharClassification::Relation),
    ('⫛' as u32, CharClassification::Relation),
    ('⫝̸' as u32, CharClassification::Relation),
    ('⫝' as u32, CharClassification::Relation),
    ('⫞' as u32, CharClassification::Relation),
    ('⫟' as u32, CharClassification::Relation),
    ('⫠' as u32, CharClassification::Relation),
    ('⫡' as u32, CharClassification::Normal),
    ('⫢' as u32, CharClassification::Relation),
    ('⫣' as u32, CharClassification::Relation),
    ('⫤' as u32, CharClassification::Relation),
    ('⫥' as u32, CharClassification::Relation),
    ('⫦' as u32, CharClassification::Relation),
    ('⫧' as u32, CharClassification::Relation),
    ('⫨' as u32, CharClassification::Relation),
    ('⫩' as u32, CharClassification::Relation),
    ('⫪' as u32, CharClassification::Relation),
    ('⫫' as u32, CharClassification::Relation),
    ('⫬' as u32, CharClassification::Relation),
    ('⫭' as u32, CharClassification::Relation),
    ('⫮' as u32, CharClassification::Relation),
    ('⫯' as u32, CharClassification::Relation),
    ('⫰' as u32, CharClassification::Relation),
    ('⫱' as u32, CharClassification::Normal),
    ('⫲' as u32, CharClassification::Relation),
    ('⫳' as u32, CharClassification::Relation),
    ('⫴' as u32, CharClassification::Binary),
    ('⫵' as u32, CharClassification::Binary),
    ('⫶' as u32, CharClassification::Binary),
    ('⫷' as u32, CharClassification::Relation),
    ('⫸' as u32, CharClassification::Relation),
    ('⫹' as u32, CharClassification::Relation),
    ('⫺' as u32, CharClassification::Relation),
    ('⫻' as u32, CharClassification::Binary),
    ('⫼' as u32, CharClassification::Large),
    ('⫽' as u32, CharClassification::Binary),
    ('⫾' as u32, CharClassification::Binary),
    ('⫿' as u32, CharClassification::Large),
    ('⬀' as u32, CharClassification::Relation),
    ('⬒' as u32, CharClassification::Normal),
    ('⬓' as u32, CharClassification::Normal),
    ('⬔' as u32, CharClassification::Normal),
    ('⬕' as u32, CharClassification::Normal),
    ('⬖' as u32, CharClassification::Normal),
    ('⬗' as u32, CharClassification::Normal),
    ('⬘' as u32, CharClassification::Normal),
    ('⬙' as u32, CharClassification::Normal),
    ('⬙' as u32 + 1, CharClassification::Ignore),
    ('⬛' as u32, CharClassification::Normal),
    ('⬠' as u32, CharClassification::Normal),
    ('⬡' as u32, CharClassification::Normal),
    ('⬢' as u32, CharClassification::Normal),
    ('⬣' as u32, CharClassification::Normal),
    ('⬤' as u32, CharClassification::Normal),
    ('⬰' as u32, CharClassification::Relation),
    ('⭅' as u32, CharClassification::Relation),
    ('⭆' as u32, CharClassification::Relation),
    ('⭇' as u32, CharClassification::Relation),
    ('⭌' as u32 + 1, CharClassification::Ignore),
    ('⭐' as u32, CharClassification::Normal),
    ('⭔' as u32 + 1, CharClassification::Ignore),
    ('⮕' as u32, CharClassification::Relation),
    ('⮕' as u32 + 1, CharClassification::Ignore),
    ('⯂' as u32, CharClassification::Normal),
    ('⯈' as u32 + 1, CharClassification::Ignore),
    ('⯊' as u32, CharClassification::Normal),
    ('⯋' as u32, CharClassification::Normal),
    ('⯋' as u32 + 1, CharClassification::Ignore),
    ('〈' as u32, CharClassification::Special),
    ('〉' as u32, CharClassification::Special),
    ('〉' as u32 + 1, CharClassification::Ignore),
    ('〚' as u32, CharClassification::Special),
    ('〛' as u32, CharClassification::Special),
    ('〛' as u32 + 1, CharClassification::Ignore),
    ('の' as u32, CharClassification::Normal),
    ('の' as u32 + 1, CharClassification::Ignore),
    ('﬩' as u32, CharClassification::Special),
    ('﬩' as u32 + 1, CharClassification::Ignore),
    ('\u{fe00}' as u32, CharClassification::Diacritic),
    ('\u{fe00}' as u32 + 1, CharClassification::Ignore),
    ('﹡' as u32, CharClassification::Special),
    ('﹦' as u32 + 1, CharClassification::Ignore),
    ('﹨' as u32, CharClassification::Special),
    ('﹨' as u32 + 1, CharClassification::Ignore),
    ('＋' as u32, CharClassification::Special),
    ('＋' as u32 + 1, CharClassification::Ignore),
    ('＜' as u32, CharClassification::Special),
    ('＞' as u32 + 1, CharClassification::Ignore),
    ('＼' as u32, CharClassification::Special),
    ('＼' as u32 + 1, CharClassification::Ignore),
    ('＾' as u32, CharClassification::Special),
    ('＾' as u32 + 1, CharClassification::Ignore),
    ('｜' as u32, CharClassification::Special),
    ('｜' as u32 + 1, CharClassification::Ignore),
    ('～' as u32, CharClassification::Special),
    ('～' as u32 + 1, CharClassification::Ignore),
    ('￢' as u32, CharClassification::Special),
    ('￢' as u32 + 1, CharClassification::Ignore),
    ('￩' as u32, CharClassification::Special),
    ('￬' as u32 + 1, CharClassification::Ignore),
    ('𝐀' as u32, CharClassification::Alphabetic),
    ('𝑔' as u32 + 1, CharClassification::Ignore),
    ('𝑖' as u32, CharClassification::Alphabetic),
    ('𝒜' as u32, CharClassification::Alphabetic),
    ('𝒜' as u32 + 1, CharClassification::Ignore),
    ('𝒞' as u32, CharClassification::Alphabetic),
    ('𝒟' as u32, CharClassification::Alphabetic),
    ('𝒟' as u32 + 1, CharClassification::Ignore),
    ('𝒢' as u32, CharClassification::Alphabetic),
    ('𝒢' as u32 + 1, CharClassification::Ignore),
    ('𝒥' as u32, CharClassification::Alphabetic),
    ('𝒦' as u32, CharClassification::Alphabetic),
    ('𝒦' as u32 + 1, CharClassification::Ignore),
    ('𝒩' as u32, CharClassification::Alphabetic),
    ('𝒪' as u32, CharClassification::Alphabetic),
    ('𝒫' as u32, CharClassification::Alphabetic),
    ('𝒬' as u32, CharClassification::Alphabetic),
    ('𝒬' as u32 + 1, CharClassification::Ignore),
    ('𝒮' as u32, CharClassification::Alphabetic),
    ('𝒯' as u32, CharClassification::Alphabetic),
    ('𝒰' as u32, CharClassification::Alphabetic),
    ('𝒱' as u32, CharClassification::Alphabetic),
    ('𝒲' as u32, CharClassification::Alphabetic),
    ('𝒳' as u32, CharClassification::Alphabetic),
    ('𝒴' as u32, CharClassification::Alphabetic),
    ('𝒵' as u32, CharClassification::Alphabetic),
    ('𝒶' as u32, CharClassification::Alphabetic),
    ('𝒷' as u32, CharClassification::Alphabetic),
    ('𝒸' as u32, CharClassification::Alphabetic),
    ('𝒹' as u32, CharClassification::Alphabetic),
    ('𝒹' as u32 + 1, CharClassification::Ignore),
    ('𝒻' as u32, CharClassification::Alphabetic),
    ('𝒻' as u32 + 1, CharClassification::Ignore),
    ('𝒽' as u32, CharClassification::Alphabetic),
    ('𝒾' as u32, CharClassification::Alphabetic),
    ('𝒿' as u32, CharClassification::Alphabetic),
    ('𝓀' as u32, CharClassification::Alphabetic),
    ('𝓁' as u32, CharClassification::Alphabetic),
    ('𝓂' as u32, CharClassification::Alphabetic),
    ('𝓃' as u32, CharClassification::Alphabetic),
    ('𝓃' as u32 + 1, CharClassification::Ignore),
    ('𝓅' as u32, CharClassification::Alphabetic),
    ('𝓆' as u32, CharClassification::Alphabetic),
    ('𝓇' as u32, CharClassification::Alphabetic),
    ('𝓈' as u32, CharClassification::Alphabetic),
    ('𝓉' as u32, CharClassification::Alphabetic),
    ('𝓊' as u32, CharClassification::Alphabetic),
    ('𝓋' as u32, CharClassification::Alphabetic),
    ('𝓌' as u32, CharClassification::Alphabetic),
    ('𝓍' as u32, CharClassification::Alphabetic),
    ('𝓎' as u32, CharClassification::Alphabetic),
    ('𝓏' as u32, CharClassification::Alphabetic),
    ('𝓐' as u32, CharClassification::Alphabetic),
    ('𝔄' as u32, CharClassification::Alphabetic),
    ('𝔅' as u32, CharClassification::Alphabetic),
    ('𝔅' as u32 + 1, CharClassification::Ignore),
    ('𝔇' as u32, CharClassification::Alphabetic),
    ('𝔈' as u32, CharClassification::Alphabetic),
    ('𝔉' as u32, CharClassification::Alphabetic),
    ('𝔊' as u32, CharClassification::Alphabetic),
    ('𝔊' as u32 + 1, CharClassification::Ignore),
    ('𝔍' as u32, CharClassification::Alphabetic),
    ('𝔎' as u32, CharClassification::Alphabetic),
    ('𝔏' as u32, CharClassification::Alphabetic),
    ('𝔐' as u32, CharClassification::Alphabetic),
    ('𝔑' as u32, CharClassification::Alphabetic),
    ('𝔒' as u32, CharClassification::Alphabetic),
    ('𝔓' as u32, CharClassification::Alphabetic),
    ('𝔔' as u32, CharClassification::Alphabetic),
    ('𝔔' as u32 + 1, CharClassification::Ignore),
    ('𝔖' as u32, CharClassification::Alphabetic),
    ('𝔗' as u32, CharClassification::Alphabetic),
    ('𝔘' as u32, CharClassification::Alphabetic),
    ('𝔙' as u32, CharClassification::Alphabetic),
    ('𝔚' as u32, CharClassification::Alphabetic),
    ('𝔛' as u32, CharClassification::Alphabetic),
    ('𝔜' as u32, CharClassification::Alphabetic),
    ('𝔜' as u32 + 1, CharClassification::Ignore),
    ('𝔞' as u32, CharClassification::Alphabetic),
    ('𝔟' as u32, CharClassification::Alphabetic),
    ('𝔠' as u32, CharClassification::Alphabetic),
    ('𝔡' as u32, CharClassification::Alphabetic),
    ('𝔢' as u32, CharClassification::Alphabetic),
    ('𝔣' as u32, CharClassification::Alphabetic),
    ('𝔤' as u32, CharClassification::Alphabetic),
    ('𝔥' as u32, CharClassification::Alphabetic),
    ('𝔦' as u32, CharClassification::Alphabetic),
    ('𝔧' as u32, CharClassification::Alphabetic),
    ('𝔨' as u32, CharClassification::Alphabetic),
    ('𝔩' as u32, CharClassification::Alphabetic),
    ('𝔪' as u32, CharClassification::Alphabetic),
    ('𝔫' as u32, CharClassification::Alphabetic),
    ('𝔬' as u32, CharClassification::Alphabetic),
    ('𝔭' as u32, CharClassification::Alphabetic),
    ('𝔮' as u32, CharClassification::Alphabetic),
    ('𝔯' as u32, CharClassification::Alphabetic),
    ('𝔰' as u32, CharClassification::Alphabetic),
    ('𝔱' as u32, CharClassification::Alphabetic),
    ('𝔲' as u32, CharClassification::Alphabetic),
    ('𝔳' as u32, CharClassification::Alphabetic),
    ('𝔴' as u32, CharClassification::Alphabetic),
    ('𝔵' as u32, CharClassification::Alphabetic),
    ('𝔶' as u32, CharClassification::Alphabetic),
    ('𝔷' as u32, CharClassification::Alphabetic),
    ('𝔸' as u32, CharClassification::Alphabetic),
    ('𝔹' as u32, CharClassification::Alphabetic),
    ('𝔹' as u32 + 1, CharClassification::Ignore),
    ('𝔻' as u32, CharClassification::Alphabetic),
    ('𝔼' as u32, CharClassification::Alphabetic),
    ('𝔽' as u32, CharClassification::Alphabetic),
    ('𝔾' as u32, CharClassification::Alphabetic),
    ('𝔾' as u32 + 1, CharClassification::Ignore),
    ('𝕀' as u32, CharClassification::Alphabetic),
    ('𝕁' as u32, CharClassification::Alphabetic),
    ('𝕂' as u32, CharClassification::Alphabetic),
    ('𝕃' as u32, CharClassification::Alphabetic),
    ('𝕄' as u32, CharClassification::Alphabetic),
    ('𝕄' as u32 + 1, CharClassification::Ignore),
    ('𝕆' as u32, CharClassification::Alphabetic),
    ('𝕆' as u32 + 1, CharClassification::Ignore),
    ('𝕊' as u32, CharClassification::Alphabetic),
    ('𝕋' as u32, CharClassification::Alphabetic),
    ('𝕌' as u32, CharClassification::Alphabetic),
    ('𝕍' as u32, CharClassification::Alphabetic),
    ('𝕎' as u32, CharClassification::Alphabetic),
    ('𝕏' as u32, CharClassification::Alphabetic),
    ('𝕐' as u32, CharClassification::Alphabetic),
    ('𝕐' as u32 + 1, CharClassification::Ignore),
    ('𝕒' as u32, CharClassification::Alphabetic),
    ('𝕓' as u32, CharClassification::Alphabetic),
    ('𝕔' as u32, CharClassification::Alphabetic),
    ('𝕕' as u32, CharClassification::Alphabetic),
    ('𝕖' as u32, CharClassification::Alphabetic),
    ('𝕗' as u32, CharClassification::Alphabetic),
    ('𝕘' as u32, CharClassification::Alphabetic),
    ('𝕙' as u32, CharClassification::Alphabetic),
    ('𝕚' as u32, CharClassification::Alphabetic),
    ('𝕛' as u32, CharClassification::Alphabetic),
    ('𝕜' as u32, CharClassification::Alphabetic),
    ('𝕝' as u32, CharClassification::Alphabetic),
    ('𝕞' as u32, CharClassification::Alphabetic),
    ('𝕟' as u32, CharClassification::Alphabetic),
    ('𝕠' as u32, CharClassification::Alphabetic),
    ('𝕡' as u32, CharClassification::Alphabetic),
    ('𝕢' as u32, CharClassification::Alphabetic),
    ('𝕣' as u32, CharClassification::Alphabetic),
    ('𝕤' as u32, CharClassification::Alphabetic),
    ('𝕥' as u32, CharClassification::Alphabetic),
    ('𝕦' as u32, CharClassification::Alphabetic),
    ('𝕧' as u32, CharClassification::Alphabetic),
    ('𝕨' as u32, CharClassification::Alphabetic),
    ('𝕩' as u32, CharClassification::Alphabetic),
    ('𝕪' as u32, CharClassification::Alphabetic),
    ('𝕫' as u32, CharClassification::Alphabetic),
    ('𝕬' as u32, CharClassification::Alphabetic),
    ('𝚤' as u32, CharClassification::Alphabetic),
    ('𝚥' as u32, CharClassification::Alphabetic),
    ('𝚥' as u32 + 1, CharClassification::Ignore),
    ('𝚨' as u32, CharClassification::Alphabetic),
    ('𝟊' as u32, CharClassification::Alphabetic),
    ('𝟋' as u32, CharClassification::Alphabetic),
    ('𝟋' as u32 + 1, CharClassification::Ignore),
    ('𝟎' as u32, CharClassification::Normal),
    ('𝟿' as u32 + 1, CharClassification::Ignore),
    ('𞸀' as u32, CharClassification::Alphabetic),
    ('𞸃' as u32 + 1, CharClassification::Ignore),
    ('𞸅' as u32, CharClassification::Alphabetic),
    ('𞸟' as u32 + 1, CharClassification::Ignore),
    ('𞸡' as u32, CharClassification::Alphabetic),
    ('𞸢' as u32, CharClassification::Alphabetic),
    ('𞸢' as u32 + 1, CharClassification::Ignore),
    ('𞸤' as u32, CharClassification::Alphabetic),
    ('𞸤' as u32 + 1, CharClassification::Ignore),
    ('𞸧' as u32, CharClassification::Alphabetic),
    ('𞸧' as u32 + 1, CharClassification::Ignore),
    ('𞸩' as u32, CharClassification::Alphabetic),
    ('𞸲' as u32 + 1, CharClassification::Ignore),
    ('𞸴' as u32, CharClassification::Alphabetic),
    ('𞸷' as u32 + 1, CharClassification::Ignore),
    ('𞸹' as u32, CharClassification::Alphabetic),
    ('𞸹' as u32 + 1, CharClassification::Ignore),
    ('𞸻' as u32, CharClassification::Alphabetic),
    ('𞸻' as u32 + 1, CharClassification::Ignore),
    ('𞹂' as u32, CharClassification::Alphabetic),
    ('𞹂' as u32 + 1, CharClassification::Ignore),
    ('𞹇' as u32, CharClassification::Alphabetic),
    ('𞹇' as u32 + 1, CharClassification::Ignore),
    ('𞹉' as u32, CharClassification::Alphabetic),
    ('𞹉' as u32 + 1, CharClassification::Ignore),
    ('𞹋' as u32, CharClassification::Alphabetic),
    ('𞹋' as u32 + 1, CharClassification::Ignore),
    ('𞹍' as u32, CharClassification::Alphabetic),
    ('𞹏' as u32 + 1, CharClassification::Ignore),
    ('𞹑' as u32, CharClassification::Alphabetic),
    ('𞹒' as u32, CharClassification::Alphabetic),
    ('𞹒' as u32 + 1, CharClassification::Ignore),
    ('𞹔' as u32, CharClassification::Alphabetic),
    ('𞹔' as u32 + 1, CharClassification::Ignore),
    ('𞹗' as u32, CharClassification::Alphabetic),
    ('𞹗' as u32 + 1, CharClassification::Ignore),
    ('𞹙' as u32, CharClassification::Alphabetic),
    ('𞹙' as u32 + 1, CharClassification::Ignore),
    ('𞹛' as u32, CharClassification::Alphabetic),
    ('𞹛' as u32 + 1, CharClassification::Ignore),
    ('𞹝' as u32, CharClassification::Alphabetic),
    ('𞹝' as u32 + 1, CharClassification::Ignore),
    ('𞹟' as u32, CharClassification::Alphabetic),
    ('𞹟' as u32 + 1, CharClassification::Ignore),
    ('𞹡' as u32, CharClassification::Alphabetic),
    ('𞹢' as u32, CharClassification::Alphabetic),
    ('𞹢' as u32 + 1, CharClassification::Ignore),
    ('𞹤' as u32, CharClassification::Alphabetic),
    ('𞹤' as u32 + 1, CharClassification::Ignore),
    ('𞹧' as u32, CharClassification::Alphabetic),
    ('𞹪' as u32 + 1, CharClassification::Ignore),
    ('𞹬' as u32, CharClassification::Alphabetic),
    ('𞹲' as u32 + 1, CharClassification::Ignore),
    ('𞹴' as u32, CharClassification::Alphabetic),
    ('𞹷' as u32 + 1, CharClassification::Ignore),
    ('𞹹' as u32, CharClassification::Alphabetic),
    ('𞹼' as u32 + 1, CharClassification::Ignore),
    ('𞹾' as u32, CharClassification::Alphabetic),
    ('𞹾' as u32 + 1, CharClassification::Ignore),
    ('𞺀' as u32, CharClassification::Alphabetic),
    ('𞺉' as u32 + 1, CharClassification::Ignore),
    ('𞺋' as u32, CharClassification::Alphabetic),
    ('𞺛' as u32 + 1, CharClassification::Ignore),
    ('𞺡' as u32, CharClassification::Alphabetic),
    ('𞺣' as u32 + 1, CharClassification::Ignore),
    ('𞺥' as u32, CharClassification::Alphabetic),
    ('𞺩' as u32 + 1, CharClassification::Ignore),
    ('𞺫' as u32, CharClassification::Alphabetic),
    ('𞺻' as u32 + 1, CharClassification::Ignore),
    ('𞻰' as u32, CharClassification::Large),
    ('𞻱' as u32, CharClassification::Large),
    ('𞻱' as u32 + 1, CharClassification::Ignore),
    ('🞄' as u32, CharClassification::Normal),
    ('🞄' as u32 + 1, CharClassification::Ignore),
    ('🞌' as u32, CharClassification::Normal),
    ('🞍' as u32, CharClassification::Normal),
    ('🞍' as u32 + 1, CharClassification::Ignore),
    ('🞗' as u32, CharClassification::Normal),
    ('🞙' as u32 + 1, CharClassification::Ignore),
    ('🞝' as u32, CharClassification::Normal),
];
