[package]
name = "rustmath"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
tiny-skia = "0.11.0"
ttf-parser = "0.19.0"
