name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: wasm32-unknown-unknown
    - uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'
    - name: Build
      run: trunk build --release --public-url /math-demo demo/index.html
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: demo/dist
