name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: wasm32-unknown-unknown
    - uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'
    - name: Test
      run: cargo test
    - name: Build
      run: trunk build --release --public-url /math-demo demo/index.html
    - name: setup ssh keys
      if: github.ref == 'refs/heads/main'
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.DEMO_DEPLOY_KEY }}
    - name: deploy demo
      if: github.ref == 'refs/heads/main'
      run: python ci/deploy-demo.py
